날씨앱 [Step1] Mason, Logan
tasty-code/ios-weather-forecast pull request #1
Opened 2023-03-15 09:14 UTC by qwerty3345

> 안녕하세요 라자냐~! (@wonhee009) 최강 Team Melo의 Mason과 Logan입니다.!! 이번 5주동안의 기나긴 날씨앱 만들기 모험을 라자냐와 함께하게돼서 정말 반가워요~😊 앞으로 5주간 저희들의 여정을 이끌어 주시길 부탁드려요!!
> 

# ✅ 요구사항 & 체크리스트

- [x]  [Open Weather Map에서 제공하는 날씨 API](https://openweathermap.org/)의 데이터 형식을 고려하여 모델 타입을 구현합니다.
    - 현재 날씨를 받아오는 API와 5일 예보를 받아오는 API를 각각 구현합니다.
    - 앱에서는 현재 날씨를 보여주는 기능과 5일 예보를 보여주는 기능 모두 갖추고 있습니다.
- [x]  API를 통해 전달받은 JSON 데이터를 활용할 수 있도록 모델 타입을 구현합니다.
    
    > 제약사항
    > 
    - 날씨 정보를 받아오는 포멧은 JSON을 사용합니다.
    - 날씨 정보는 위도/경도를 사용하여 받아옵니다.
- [x]  [Open Weather Map에서 제공하는 날씨 API](https://openweathermap.org/)의 데이터를 실제로 받아올 수 있는 네트워킹 타입을 구현합니다.

## API 받아온 데이터 출력 예시
<img width="736" alt="스크린샷 2023-03-15 오후 5 48 43" src="https://user-images.githubusercontent.com/59835351/225261934-fd85cdff-a4a1-4a0a-9df9-1b7dc71fc605.png">

# **⁉️ 고민과 해결**

### 1️⃣ API 키 숨기기

- 앱 요구사항을 충족하기 위해 OpenWeather 의 API 키를 발급했고,
해당 키를 그대로 github에 노출하는 것은 위험하다는 판단이 들어 어떻게 key를 숨길 수 있을지 고민했습니다.
- `APIKey.xcconfig` 라는 파일을 생성하고, 해당 파일을 .gitignore에 추가한 뒤 
Info.plist 에서 해당 키값을 받아와서 `Bundle.main.object(forInfoDIctionaryKey:)` 방식으로 해당 값을 받아왔습니다.
- 하지만 이 방법으로 진행했을 때, 깃허브에 해당 파일이 없는 상태이기 때문에 저희가 서로 커밋을 주고 받을 때마다 로컬에 생성해놨던 `APIKey.xcconfig` 파일이 사라지는 현상이 발생했습니다. 
그에 따라서 프로젝트 Info에 등록해놨던 Configuration file 정보도 함께 초기화(none)가 되버리는 상황이라서 매번 pull을 할 때마다 매번 새로운 파일을 생성해야 하는 상황이 발생했습니다.
- 그래서 저희가 해결한 방식은, git이 추적하는 프로젝트 폴더 바로 바깥 폴더에 해당 configuration 파일을 두고, relative path (../../../APIKey.xcconfig) 로 설정 해 두었더니 매번 해당 파일을 삭제하지 않게 되어 문제가 해결되었습니다.

### 2️⃣ DTO 분류 기준

- 저희가 API를 활용하여 서버로부터 데이터를 받아 왔을때, 
DTO에 해당하는 `CurrentWeather`(하루 예보)와 `Forecast`(5일 데이터) 의 파라미터 모델 중, 겹치는 모델들이 존재하여 
저희는 해당 겹치는 모델들을 `CommonDTO`파일에 묶어서 따로 분리하였습니다.

> ❓ 이렇게 하나의 API 에서 다른 두가지의 요청을 했을 때 두 요청에서 받아온 데이터 중 겹치는 모델을 공통의 모델로 분리한 방식이 적절할까요?
>

2023-03-16 03:56 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요.

- 동일하게 사용되는 모델을 나눈건 좋습니다. 하지만 Common이라는 네이밍이 너무 제네럴한거 같습니다.

2023-03-16 03:56 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Model/NetworkError.swift
> +        case .networkingError:
`NetworkError.networkingError`는 어색한거 같은데 다른 이름이 있을까요?

enum명에서 error임이 충분히 드러나서 case들의 `error`는 없어도 의미 전달이 가능할거 같습니다.

2023-03-16 03:56 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Model/DTO/CommonDTO.swift
> +//  CommonDTO.swift
이 친구는 `-DTO`로 네이밍 되어 있는데 다른 친구들은 없는거 같습니다.
해당 postfix를 붙이는 기준이 있는걸까요?

2023-03-16 03:56 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Model/DTO/CommonDTO.swift
> +struct MainData: Decodable {
MainData라고 네이밍한 이유가 있을까요?
(메인에서 사용해서 메인 데이터인건지..?)
좀 더 명확한 네이밍이면 좋을거 같습니다.

2023-03-16 03:56 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Model/DTO/Forecast.swift
> +    let cnt: Int
네이밍하는데 있어서 줄임말은 지양하는게 좋습니다.
이곳말고도 전반적으로 줄임말 있는지 확인 부탁드립니다.

2023-03-16 03:56 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Model/DTO/Forecast.swift
> +//  Forecast.swift
해당 파일 명이 `Forecast`인데요. 해당 파일에 `Forecast`, `City`, `List`, `Rain`이 정의되어 있는거 같습니다.
이 친구들이 한 파일에 있어야하는 친구들인가요?

2023-03-16 03:56 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Repository/OpenWeatherRepository.swift
> +final class OpenWeatherRepository {
해당 Repository내에 네트워킹을 하기 위한 네트워크 작업도 포함되어 있는거 같습니다.
`Repository`를 어떤 역할로 사용하고 있는지 궁금하고, 네트워크 작업이 해당 파일 내에 정의되어야 하는지 궁금합니다.

2023-03-20 08:22 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Model/DTO/CommonDTO.swift
> +//  CommonDTO.swift
명확한 기준이 존재하지 않았어서, 폴더링을 DTO폴더 내부에 넣고 postfix는 모두 제거 해 주었습니다!

2023-03-20 08:23 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Model/DTO/Forecast.swift
> +//  Forecast.swift
파일별로 분리하였습니다!
> 해당 커밋: df538f1

2023-03-20 08:23 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Model/DTO/Forecast.swift
> +    let cnt: Int
Swift API Guideline에 맞게 서버에서 받아온 축약어를 모두 수정하였습니다!
> 해당 커밋: e443f6e

2023-03-20 08:24 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Model/DTO/CommonDTO.swift
> +struct MainData: Decodable {
수정하였습니다!
> 해당 커밋: e443f6e

2023-03-20 08:25 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Model/NetworkError.swift
> +        case .networkingError:
중복되는 네이밍을 제거하였습니다!
> 해당 커밋: 27ef37c

2023-03-20 08:27 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Repository/OpenWeatherRepository.swift
> +final class OpenWeatherRepository {
Architecture에 대해서 더 공부한 후, 
Repository의 역할과 Service의 역할은 분리되어야 함을 알게 되었습니다.

Repository가 의존성 주입으로 Service를 주입받아 네트워킹을 하도록 구현하였습니다.

한가지 의문은, Repository는 이름 그대로 "저장소"의 역할을 하는데...
저희가 구현한 방식이 Repository 라고 할 수 있는지 명확하지 않은 느낌이 있습니다. 혹시 의견을 주실 수 있으신가요?

> 해당 커밋: 27ef37c

2023-03-20 09:40 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Repository/OpenWeatherRepository.swift
> +final class OpenWeatherRepository {
제가 생각했던 부분은 repository나 service나 좀 더 서비스에 디펜던시가 있다고 생각했습니다. (openWheater을 가지고 온다와 같은 행위는 서비스 종속적이라고 생각합니다.)
따라서, 해당 파일 내에서 네트워킹을 하는 역할이 다른 파일로 떨어져 나와야한다고 생각했는데요. (네트워킹은 아무래도 좀 더 제네럴한 행위니까요.)
현재 코드 상으로는 이후 날씨뿐 아니라 영화 포스터를 가지고 오는 스펙이 추가된다면 `MoviePosterRepository`를 만들고 내부에 다시 네트워킹 역할을 채워넣던지, 해당 repository의 네트워킹을 같이 쓰던지의 선택지가 있을거 같아서요.

2023-03-20 11:43 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Repository/OpenWeatherRepository.swift
> +final class OpenWeatherRepository {
말씀하신 "서비스 종속적이다" 라는 부분이 잘 이해가 가지 않는데요 😅
Repository - Service에서의 서비스와는 다른 의미일까요?

현재 저희가 구현한 방식이 네트워킹 역할을 Service에게 위임하였는데, 
생각 해 보니 OpenWeather에만 종속되는 Service가 아니기에.. NetworkService 라고 네이밍 하는 것이 더 제네럴 하게 사용될 것 같아 변경하였습니다.

2023-03-21 03:14 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Repository/OpenWeatherRepository.swift
> +final class OpenWeatherRepository {
아핫 네넵 제가 위의 코멘트를 달때에는 repository 내에 네트워크 코드가 있어서 그걸 분리하는 방향을 설명하면서 남긴 코멘트인데요.
현재 구조 확인해보니 분리도 되어 있고 네이밍도 적절한거 같아 리졸브하겠습니다~

2023-03-21 03:15 UTC, wonhee009 approved these changes
수고하셨습니다~ 다음 스텝 진행해주세요.

2023-03-21 03:15 UTC, merged