WeatherForecast [Step2] Jason & Joo
tasty-code/ios-weather-forecast pull request #10
Opened 2023-03-24 12:09 UTC by JasonLee0223

안녕하세요 븨븨(@YebinKim)! 이번 날씨 앱 진행하게된 Jason, Joo입니다! 🙇🏻🙇🏻
저희는 이번 한 주동안 Step2을 구현하면서 아쉬웠던 부분이 많은 스텝이였습니다.

URLSession과 CoreLocation을 사용하면서 뭔가 원하는 방향대로 흘러가지 못한 것 같아 아쉽네요..
Step1에서 많은 부분을 진행하여 대부분 Refactoring 작업이 많았던 것 같습니다! 

PR을 작성하면서 다시 코드를 멀리서 바라보니 UserLocation의 address 메서드에서 사용하는 Result를 사용하는 것이 불필요한 거 같고, 
제대로 알지 못한 채 사용하다 느끼는 부분을 주말동안 더 깊게 공부하고 더 나은 코드로 사용되기 위해서 어떤 것을 해야되는지 고민을 하려고 해요
이번 스탭 리뷰 잘 부탁드리며 좋은 하루 보내시길 바라요 🪄🪄🪄

## 📌 Step 2 : 위치정보 확인 및 날씨 API 호출
- [x] 현재 위치의 위도와 경도를 알아냅니다.
- [x] 위도와 경도를 활용해 현재 위치의 주소를 알아냅니다.
- [x] 현재 위치의 날씨와 현재 위치의 5일 예보를 날씨 API를 통해 데이터를 요청하고 받아오는 기능을 구현합니다.

## 🚀 스텝 핵심 경험
- [x] CoreLocation을 통해 현재 좌표 가져오기
- [x] CoreLocation을 통해 주소 가져오기
- [x] URLSession을 통해 API 호출 (HTTP GET 메서드 명시적 호출)
- [x] 전달받은 JSON 데이터 파싱 및 모델에 매칭

## 🎯 API 사용 관련 스터디
- [x] Core Location을 사용하여 좌표 가져오기
- [x] CLGeocoder을 사용하여 경도/위도를 통한 위치 정보 가져오기
- [x] .xcconfig 파일로 APIKEY 숨기는 방법 변경
- [x] URLSession Result 타입 적용

## 🔖 부연 설명
### URLSession dataTask Result Type 적용
[The Result Type](https://www.swiftbysundell.com/basics/result/)

이번에 저희가 Step1에서 질의응답해주신 URLSession의 Error Handling 부분에서 Result 타입을 적용해보았습니다.
구현 과정중에서는 위 링크를 참고하여 진행해보았는데요.
기본적인 Result 타입에 대한 학습과 프로젝트에 적용해보면서 여러 방법으로 시도해보았습니다.
URLSession에 Result를 적용하여 보통 많이 쓰이는 코드는 아래와 같았습니다.
```Swift
func loadData(with: url, completion: @escaping Result<WeatherModel, Error>) -> Void)
```
```swift
dataTask(with: url) { data, response, error in
    guard let error == error else {
        completion(.failure(error))
    }
    ...
}.resume()
```
위 부분에서 dataTask 스코프({})안에서의 코드를 줄여보고자 함과 분리를 잘해보고싶어서 프로젝트에서는
**URLSession을 확장하여 dataTask 메서드를 만들어서 사용해보았습니다.**
여기에서 문제점은 `HTTPResponse`의 API 서버 요청 에러를 확인할 수 없었습니다. 
참고할만한 코드가 없어서 참고할만한 코드를 찾는데 어려움이 있었습니다.

저희가 상의하여 도출한 부분은 이번 Step에서 API와 연동되는 부분에대해서는 많이 학습하고 이해했다고 보여져 다음 Step들이 대부분 UI와 연결되는 점이 많아서
Low Level한 Network Service 영역은 프로젝트가 어느 정도 진행되면 `Refactoring`하는순으로 진행해보려고합니다.

## 🙋🏻 질문있습니다!
### 🅰️ CLGeocoder 주소 가져오기
CLGeocoder에서 존재하는 메서드로는 Step 3에서 보여지는 OO구를 표현할 수가 없어 Swift 11.0 이후 deprecated 된 `addressDictionary` 메서드를 사용하여 구현을 하였습니다. 
(deprecated되어 제공되는 주소를 가져오는데 필요한 프로퍼티들이 있지만 우리나라의 '구'를 표현하는 방법이 없었습니다...😂 
[reverseGeocodeLocation 주소 변환 Deprecated 된 것 수정하기](https://yb-ios-dev.tistory.com/10))

🤔 위도/경도를 사용하여 주소 값을 가져오는 다른 방법이 있는지 궁금합니다.

### 🅱️ CLLocationManager 구조를 싱글톤 객체로 생성
🤔 CLLocationManager의 delegate 및 권한 요청을 UserLocation이라는 싱글톤 객체를 만들어서 사용을 하였습니다. 이렇게 사용하는 게 괜찮은 지 궁금합니다.

2023-03-27 00:46 UTC, YebinKim requested changes
현재 앱을 최초 설치했을 때 위치 권한을 받아오는 동작이 이루어지지 않아 Request Changes 요청 드립니다~
(자세한 내용은 DM으로 얘기 나누었으며, 기록 용으로 코멘트 남겨두어요!)

2023-03-27 16:42 UTC, YebinKim requested changes
주, 제이슨 안녕하세요~
Step2 진행까지 고생 많으셨습니다 😆🙌

이번에 처음 URLSession과 CoreLocation을 사용해보면서 어려운 점이 많으셨을 거 같아요 😂
지금 느끼는 아쉬운 점들이나 어려움들을 잊기 전에 README 를 작성해둔다면 고난의 시간만큼 성장하는 씨앗이 될 수 있을 것이라 생각합니다 🌱

---

### 1. CLGeocoder 주소 가져오기
주소를 가져오는 다른 방법으로는 현재 위도/경도 값을 한국의 우편주소 안에서 검색하거나 서드파티를 쓰는 방법 등이 있겠지만, 그 이전에 `CLGeocoder` 로 표현되는 정보가 부족한 게 맞을지 의문이 들어요 🤔
저는 **현재 위치의 주소**를 파악하기 위해 [CLPlacemark ](https://developer.apple.com/documentation/corelocation/clplacemark) 의 [subLocality](https://developer.apple.com/documentation/corelocation/clplacemark/1423794-sublocality) 만큼의 정확성만 되어도 충분하다고 요구사항을 해석했는데, 두 분의 생각은 어떠실지 궁금합니다!
(문서와 실제 출력값을 보면 subLocality 는 현재 위경도에 따라 ~구 또는 ~동 을 보여주는 것으로 보여요)

### 2. CLLocationManager 구조를 싱글톤 객체로 생성
어떤 점에서 우려를 느끼셨을까요?
싱글톤으로서 더 잘 사용하고자 한다면 외부에서 인스턴스 프로퍼티, 인스턴스 메서드에 접근할 수 없도록 생성자를 private 선언해주면 좋을 거 같습니다.

### 3. Result
그리고 부연 설명에서 말씀해주신 `URLSession에 Result를 적용하여 보통 많이 쓰이는 코드` 에 대한 내용 중 **보통 많이 쓰인다**는 것은 어디의 기준일까요?

---

이번 스텝의 핵심 경험은 아래와 같았는데요.
<img width="452" alt="step2" src="https://user-images.githubusercontent.com/38066039/228007598-bc5ae902-7d36-4e46-9e34-8a0c45a617a6.png">

**CoreLocation을 통해 주소 가져오기** 와 **URLSession을 통해 API 호출 (HTTP GET 메서드 명시적 호출)** 에 대해 좀 더 얘기를 나눠보고,
p2 코멘트가 있어서 Request Changes 로 요청 드렸어요 😄

내일 오전-오후 중 디코에서 얘기 나누는 시간을 가져보았으면 하는데 일정은 DM으로 얘기 나눠보아요~
그리고 리뷰 코멘트와 관련해 궁금한 점이 있다면 언제든 질문 환영입니다!! ☺️🙌

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +    let session = URLSession.shared
p3;

외부에서 접근 가능한 프로퍼티일까요?
접근 가능하지 않다면 접근제어를 낮추는 게 필요해보여요!

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +        let task = session.dataTask(with: url) { [self] result in
질문;

`self` 캡쳐를 작성한 이유가 무엇일까요?

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +    case networkFailure(Error)
enum의 연관 값으로 에러를 전달하셨군요! 🤩
enum의 멋진 활용이라고 생각합니다 👍

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +        dataTask(with: url) { data, response, error in
p2;

`response` 는 사용을 하지 않는 변수가 맞을까요?
Step1 에서는 status code 를 체크했는데 리팩토링을 진행하면서 사라진 것으로 보이네요 🤔

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/URLPath.swift
> +        let unitsOfMeasurement = URLQueryItem(name: "units", value: "metric")
p3;

`URLQueryItem` 의 `name` 과 `value` 들이 일부 하드코딩되어 있는 것으로 보이네요 👀
하드코딩은 추후 수정을 어렵게(복잡해지게) 만드니 가능하면 사용을 지양해보는 게 어떨까요?

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/ViewController.swift
> +        UserLocation.shard.authorize()
p3;

해당 코드는 추후 UI 작업을 진행하면서 삭제될 코드가 맞을까요?
Human Interfaces Guidelines의 [Accessing private data](https://developer.apple.com/design/human-interface-guidelines/patterns/accessing-private-data/)에 따르면 앱의 민감 정보 접근 권한을 얻을 때는 가급적 해당 기능을 필요로 할 때 받아올 것을 권장하고 있다는 것을 리마인드 드립니다 😄

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/ViewController.swift
> +        //MARK: - 테스트용 출력
p5;

다른 종류의 #praga 주석을 활용해보아도 좋을 거 같아요!
FIXME, TODO 를 활용하면 좀 더 의미를 명확히 전달할 수 있을 것으로 보입니다 😊

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/ViewController.swift
> +            print(error)
질문;

`localizedDescription` 을 삭제한 이유가 무엇일까요?

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +    }
p2;

위치 권한을 받아오기 전 [현재 권한 상태](https://developer.apple.com/documentation/corelocation/clauthorizationstatus)에 대한 확인이 먼저 필요할 것으로 보여요 🤔

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +        geocoder.reverseGeocodeLocation(newLocation) { (placemark, error) in
p3;

`placemark` 는 배열 타입인 것으로 보이네요!
복수형의 네이밍이 필요할 거 같아요 👀

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +              let value = infomation.first else {
p2;

`infomation.first` 에 대한민국~ 으로 시작하는 주소가 항상 포함되어 있다고 보장할 수 있을까요? 🤔
(addressDictionary 를 사용하지 않는 것 자체를 권장드리고 싶긴 합니다 😅)

2023-03-27 16:42 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +    static let shard = UserLocation()
```suggestion
    static let shared = UserLocation()
```

p3;

오타가 있습니다! 👀

2023-03-28 02:19 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +    static let shard = UserLocation()
위 내용 반영하였습니다!

해당 커밋: db765d8

2023-03-28 02:22 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +              let value = infomation.first else {
addressDictionary가 `deprecated` 되어 다른 방법으로 처리할 수 있는지에 대한 질의에 대해
위에서 추천해주신 방법으로 `subLocality`를 적용하여 해결해보았습니다!

해당 커밋: 73f8c50

2023-03-28 02:33 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +        let task = session.dataTask(with: url) { [self] result in
클로저 안에서 loadJSON(weatherType: , weatherData: ) 메서드를 호출하다보니 
`self`키워드를 사용해야해서 `self`캡처를 사용하게 되었습니다. 
(메서드가 많이 호출될 때마다 self 키워드가 앞에 붙는 것이 가독성에 안좋아보여서 캡처를 주로 사용하게 된 것 같습니다.)

Step3 ~ 5까지 UI관련 작업이 많다보니 추후에 MVVM 패턴으로 리펙터링할 때 분리를 많이해서 [weak self]로 변경하고자
하는 생각도 있어 현재 `self` 캡처를 사용하게 된 이유도 있네요..😅

2023-03-28 02:37 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +    let session = URLSession.shared
앗! 접근 제어 부분을 놓쳤네요..😅 private로 엑세스 레벨 낮추었습니다!

해당 커밋: 41d80e5

2023-03-28 02:45 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +        dataTask(with: url) { data, response, error in
넵.. 사라진게 맞습니다...🥲
Result타입을 사용하여 리펙터링 과정에서 HTTPResponse를 확인할 수 있는 코드를 구현해보려고 노력하였는데
부연설명에서 말씀드린 부분처럼 URLSession을 확장하여 `dataTask`를 직접 구현하여 사용하였습니다.

이렇게 진행하다보니 Data와 Error에 관한 부분만 확인할 수 있어서 API 응답에 관한 코드를 추가적으로 작성해줘야했는데
`response` 로직을 분리하여 코드를 작성하는데 있어 아직 현재 지식으로는 구현에 어려움이 있어 진행하지 못하였습니다..🥲

Joo와 상의하여 PR을 보낼때는 추후에 한 번 도전해보자고 얘기되었는데 PR에서 사용하지 않는 프로퍼티여서 `_`로 바꿔야하는데
못바꾸었네요..
추후에 리펙터링을 진행하더라도 현재 사용하지 않음으로서 반영하여 수정하였습니다.

해당 커밋: 81662c4

2023-03-28 04:31 UTC, ohdair commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +        geocoder.reverseGeocodeLocation(newLocation) { (placemark, error) in
placemark에 대한 부분을 복수형으로 바꾸면서 단순하게 address를 부르는 과정에서 Result 타입으로 처리하는 것은 과하다 생각하였고 외부에서 부를 때에도 클로저 형태로 사용되는 게 깔끔하지 않아서 `async/await`으로 변경했습니다!

해당 커밋: [73f8c50](https://github.com/tasty-code/ios-weather-forecast/pull/10/commits/73f8c50cfd137cbb9cb7117b4f4bff2bda53a839)

2023-03-28 08:02 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/URLPath.swift
> +        let unitsOfMeasurement = URLQueryItem(name: "units", value: "metric")
위 하드코딩 되어 있던 부분들을 enum의 static property로 변경하였습니다.

해당 커밋: e475ae7

2023-03-28 08:04 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/ViewController.swift
> +        //MARK: - 테스트용 출력
위 내용은 리펙터링 과정에서 삭제되었네요! ㅎㅎ
#praga 는 검색해도 잘안나오네요..🥲 평소에 `//MARK: -`, `//TODO: -`식으로 사용하는데 동일한 의미일까요??

2023-03-28 08:08 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/ViewController.swift
> +            print(error)
위 내용은 CompletionHandler 및 Error 타입을 만들어 삭제하였습니다!

2023-03-28 08:12 UTC, ohdair commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +    }
권한 요청 시, 앱 권한 상태에 따른 요청하도록 변경했어요.

```swift
func authorize() {
    switch CLLocationManager.authorizationStatus() {
    case .denied:
        print("위치 정보 권한이 필요합니다")
    case .notDetermined, .restricted:
        sharedLocationManager.requestWhenInUseAuthorization()
    default:
        return
    }
}
```

2023-03-30 07:19 UTC, YebinKim commented on WeatherForecast/WeatherForecast/ViewController.swift
> +        //MARK: - 테스트용 출력
앗 제가 오타가 있었네요 😅
#pragma 주석을 말씀드린 것이었어요!

`MARK:`, `TODO:`, `FIXME:`, `!!!:`, `???:` 와 같은 종류의 pragma 주석을 활용하면 의미를 좀 더 명확히 전달할 수 있을 것으로 보입니다~

2023-03-30 07:29 UTC, YebinKim approved these changes
주, 제이슨 안녕하세요~
수정해주신 내용 및 코멘트 답변 확인했습니다!

이번 스텝에서의 핵심 경험은 모두 충족되었다고 생각해서 이대로 머지 진행할게요 😊
Step3 진행도 화이팅입니다 🔥💪

2023-03-30 07:29 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/URLPath.swift
> +        let latitude = URLQueryItem(name: OpenWeatherParameter.latitude, value: coordintate.latitude.description)
리뷰 코멘트 반영 고맙습니다! 😄

2023-03-30 07:29 UTC, merged

2023-03-30 07:46 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/URLPath.swift
> +        let latitude = URLQueryItem(name: OpenWeatherParameter.latitude, value: coordintate.latitude.description)
아닙니다! ㅎㅎ 매직 넘버를 사용하지 않으려고 했는데 까먹고 놓쳤었습니다...😂 감사합니다!! ㅎㅎ