WeatherForecast [STEP 2] d.o., Lust3r
tasty-code/ios-weather-forecast pull request #11
Opened 2023-03-28 05:07 UTC by llimental

## WeatherForecast [STEP 2] d.o., Lust3r
안녕하세요! 소대(@zdodev)! d.o., Lust3r입니다!

이번 스텝에서는 Core Location과 Geocoder를 어떻게 사용하면 좋을지, 그 데이터를 어떻게 전달하면 좋을지 각 기능을 한 번씩 써보면서 고민을 해보았습니다.
그 과정에서 사용자 경험을 위해 이런 기능이 있어야 하겠다-하는 생각이 든게 조금 있었는데, 다음 스텝에서 UI를 구현하면서 녹여보도록 하겠습니다!

이번 리뷰도 잘 부탁드립니다! 감사합니다! 🙇🏻🙇🏻

## 🧑🏼‍💻 작업 목록

**[ STEP 2 ] 위치정보 확인 및 날씨 API 호출**

- [x] 현재 위치의 위도와 경도를 알아냅니다
- [x] 위도와 경도를 활용해 현재 위치의 주소를 알아냅니다
- [x] 현재 위치의 날시와 현재 위치의 5일 예보를 날씨 API를 통해 데이터를 요청하고 받아오는 기능을 구현합니다.

## 📚 학습 키워드 및 학습 내용

### 1. Core Location

> 출처: Apple 공식문서 - [Core Location](https://developer.apple.com/documentation/corelocation)
> 
- 장치의 지리적 위치, 고도, 방향, 또는 주변 iBeacon 장치에 대한 상대적인 위치를 결정하는 서비스 제공
- Wi-Fi, GPS, Bluetooth, 자력계, 기압계 및 셀룰러 하드웨어를 포함, 장치에서 사용 가능한 모든 구성 요소를 사용하여 데이터 수집
- 이번 프로젝트에서는 이를 통해 시뮬레이터의 설정된 좌표를 불러오고, 그 좌표를 사용하여 geoCoder에 넘기거나 NetworkManager가 callAPI() 메서드를 사용하는데 이용할 수 있도록 했다.

### 2. Geocoder

> 출처: swift 공식문서 - [CLGeocoder](https://developer.apple.com/documentation/corelocation/clgeocoder)
> 
- 지리적 좌표와 장소 이름 사이를 변환하기 위한 인터페이스
- `Geocoder` 객체는 정방향 또는 역방향 지오코딩 방법을 사용하여 요청을 시작
- 정방향 지오코딩 요청은 사용자가 읽을 수 있는 주소를 사용하여 위도 및 경도를 찾음
- 역방향 지오코딩 요청은 위도 및 경도 값을 가져와 사용자가 읽을 수 있는 주소를 찾음
- 두 유형 모두 `CLPlacemark` 개체를 사용하여 결과 반환

### 3. CLPlacemark

> 출처: swift 공식문서 - [CLPlacemark](https://developer.apple.com/documentation/corelocation/clplacemark)
> 
- 지리적 좌표에 대한 사용자에게 친숙한 설명. 장소 이름, 주소 및 기타 관련 정보를 포함함
- `CLPlacemark` 객체는 지정된 위도 및 경도에 대한 장소 표시 데이터 저장
- `CLGeocoder` 개체를 사용하여 지리적 좌표를 역방향 지오코딩하면 해당 위치에 대한 설명 정보가 포함된 `CLPlacemark` 개체를 받게 됨
- 장소표시 세부정보를 가져올 때, 다음과 같은 프로퍼티를 사용할 수 있음
    - **thoroughfare**: 장소 표시와 연결된 상세 주소
    - **subThoroughfare**: 장소 표시에 대한 추가 도로 수준 정보
    - **locality**: 장소 표시와 연결된 도시
    - **subLocality**: 장소 표시에 대한 추가 도시 수준 정보
    - **administrativeArea**: 장소 표시와 연결된 시/도
    - **subAdministrativeArea**: 장소 표시에 대한 추가 관리 영역 정보
    - **postalCode**: 장소 표시와 연결된 우편 번호
- 이번 프로젝트에서는 위 항목을 각각 출력해 보았을 때, `administrativeArea`, `locality`, `sublocality`, `thoroughfare`, `subThoroughfare`가 적합하다 생각하여 선별하여 사용했습니다.

    ``` Swift
    geoCoder.reverseGeocodeLocation(location) { placemarks, error in
                guard let placemark = placemarks?.first else { return }
                var address = ""

                if let administrativeArea = placemark.administrativeArea { address += administrativeArea }

                if let locality = placemark.locality { address += " \(locality)" }

                if let subLocality = placemark.subLocality { address += " \(subLocality)" }

                if let thoroughfare = placemark.thoroughfare { address += " \(thoroughfare)" }

                if let subThoroughfare = placemark.subThoroughfare { address += " \(subThoroughfare)" }

                print("address: ", address)
            }
    ```

## 🤔 고민과 해결

### 1. 위치 정보 동의 문구
- 위치 정보 권한을 얻기 위해서는 동의 문구를 작성해야 했습니다. `Always and When In Use`, `When In Use` 두 개를 추가하는 예시만 있길래 전자가 항상 허용과 사용할 때 허용 두 케이스를 다 포함한다 생각하여 하나만 설정해도 되지 않을까 생각했습니다. 하지만 한 개만 했을 때는 아래와 같은 오류(민감한 데이터에 사용 설명 없이 접근하려 한다)가 발생했고, 두 조건이 반드시 포함되어야 한다고 명시되어 있어 그것을 근거로 작성하게 되었습니다.
![](https://i.imgur.com/ZN11pYl.png)

### 2. NotificationCenter
- LocationManager에서 받은 위도, 경도 데이터를 어떻게 `NetworkManager`에서 사용할까 고민하다 `NotificationCenter`를 사용하면 좋겠다고 생각했습니다. 두 객체를 직접 연결하기엔 부담스러웠으나 `Observer`를 통해 전달하는 것은 보다 낫다고 판단했고, 실제로 그렇게 구현하여 `callAPI()` 메서드를 재호출하여 데이터를 받아오는 것까지 성공하였습니다.

    ``` Swift
    init() {
            NotificationCenter.default.addObserver(self, selector: #selector(getCoordinate(notification:)), name: Notification.Name.location, object: nil)
        }

        // MARK: - Helper
        @objc func getCoordinate(notification: Notification) {
            guard let coordinate = notification.userInfo?[NotificationKey.coordinate] as? CLLocationCoordinate2D else { return }
            latitude = coordinate.latitude
            longitude = coordinate.longitude
            callAPI()
        }
    ```
### 3. 시뮬레이터 결과 문제
- 처음에 `Core Location`을 통해 주소를 불러올 때, 둘의 결과가 다른 문제가 있었습니다. d.o.는 주소가 경기도 고양시 에서 끝나 뒤에는 @로 마무리되었고, lust3r는 전체 주소가 다 나오는 등 동일한 결과를 볼 수 없었습니다.
이 문제는 저희 위치정보 정확성을 `kCLLocationAccuracyBest`로 했는데 시뮬레이터에서 각각 `정확한 위치` 옵션을 끔/켬 으로 다르게 했기 때문임을 알게 되어 해결하게 되었습니다.

### 4. errorDescription VS localizedDescription

- `error.localizedDescription`을 사용하기 위해 `LocalizedError` 프로토콜을 채택하고, 구현 요구사항인 `errorDescription: String?` 을 정의하였어요!
- “그렇다면 왜 `error.localizedDescription`은 옵셔널 값 `String?`을 리턴하지 않는가?” 하는 궁금점이 있었어요!
- ⁉️🙄 내가 정의한 속성은 `String?`인데 사용하는데서는 `String` 이 출력되는 이유는 뭐지? 했는데
- ‼️🫢 `errorDescription`과 `localizedDescription`은 다른 것이었다는 것을 알게 되었어요!

    ``` Swift
    public protocol LocalizedError : Error {

        /// A localized message describing what error occurred.
        var errorDescription: String? { get }

        /// A localized message describing the reason for the failure.
        var failureReason: String? { get }

        /// A localized message describing how one might recover from the failure.
        var recoverySuggestion: String? { get }

        /// A localized message providing "help" text if the user requests help.
        var helpAnchor: String? { get }
    }

    extension Error {

        /// Retrieve the localized description for this error.
        public var localizedDescription: String { get }
    }
    ```

## 🙋🏻 질문 거리

### 1. 시뮬레이터 결과가 다르게 나와요!
- 둘 다 같은 코드를 pull 받아 사용했음에도 시뮬레이터가 서로 다른 결과를 보여줬습니다. 앞서 고민과 해결 4번에서처럼 실행한 환경이 달라서 그런 것이면 해결이 되었을텐데, 똑같이 실행했는데도 문제가 발생했습니다.
가령 마지막 커밋 기준으로 lust3r의 시뮬레이터는 address 출력이 한 번, weather/forecast 요청이 각 2번(초기 호출 + 옵저버 호출)이뤄지는데
d.o.의 시뮬레이터는 address 출력이 두 번, weather/forecast 요청이 각 3번(초기 호출 + 옵저버 호출 + ?) 이뤄졌습니다.
시뮬레이터에 설치된 프로젝트 앱을 삭제도 해보고 이것저것 시도를 해봤는데도 해결이 되지 않았습니다.

### 2. 주소가 잘 나오지 않아요!
- `geoCoder`의 `reverseGeocodeLocation`을 사용했을 때, 그 하위요소로 주소를 표시할 수 있었습니다. 그런데 이전에는 주소가 잘 표현된 것으로 보이는데 지금은 도로명 주소로 바뀌어서인지, 아니면 버전이 올라가면서 변환 방식이 변경된 것인지 주소가 정확히 표시되지 않았습니다.
가령 저희 새싹 건물을 기준으로 코드는 '서울특별시 용산구 한강로3가 청파로 109'를 보여줘야 하는데, 실제 결과는 '서울특별시 서울특별시 한강로3가 청파로 109'를 보여줍니다. 애초에 데이터가 저렇게 들어왔나 싶어 `Placemark`, `description`을 출력해보니 위도 경도를 통해 들어온 데이터는 용산구가 들어가 있었습니다.
해결해보고자 `placemark`의 모든 정보를 출력해보고 메서드를 찾아보았지만 '용산구'를 끌어낼 수 없었습니다. 혹시 이걸 표시하게 할 수 있는 방법이 있을까요?

  ![](https://i.imgur.com/MrHBqDi.png)

2023-03-29 13:12 UTC, zdodev requested changes
안녕하세요. @llimental , @doshkor !

Step 2 구현 잘 진행해주셨습니다!
기능 요구사항을 잘 만족해주셨네요!👍

질문에 대한 제 생각을 적어보았습니다.

❓ 시뮬레이터 결과가 다르게 나와요!

- `Core Location` 을 사용해 주소를 가져오는 로직상에서는 문제는 없어보입니다.
- 코드 상에서 로케이션이 업데이트되면 날씨 API를 호출하게 되는데 d.o. 의 시뮬레이터에서 `address` 가 두번 출력되는 것으로 보아 옵저버 호출이 두번 이루어져 날씨 API도 두번 호출되지 않았을까 싶습니다. 시뮬레이터에서 `Location` 설정이 동일한지 다시 한번 확인이 필요할 것 같습니다!

❓ 주소가 잘 나오지 않아요!
 
- 해당 문제는 애플 사용하는 지도 데이터에 문제(도로명, 지번 등)가 있지 않을까 싶습니다. (시뮬레이터에 따라 다르게 동작하는 부분을 확인할 수 있었습니다.) 실제 기기에서도 같은 결과가 출력되는지 확인이 필요할 것 같습니다!

코멘트 확인 부탁드립니다!

2023-03-29 13:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +final class LocationManager: NSObject, CLLocationManagerDelegate {
로케이션 역할에 대한 타입을 별도로 구현해보셨네요!👍

2023-03-29 13:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +    private let geoCoder = CLGeocoder.init()
`init` 을 명시하여 초기화하신 이유가 궁금합니다!

2023-03-29 13:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +    }
`setUpLocationManager` 메서드가 다양한 역할을 수행하는 것 같습니다.
서비스 설정과 서비스 실행에 대한 역할을 나눠보는 것은 어떨까요?
초기 한번만 실행해도 무관한 부분은 초기화 생성자를 활용해보는 것도 좋을 것 같습니다!

2023-03-29 13:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +        NotificationCenter.default.post(name: Notification.Name.location, object: nil, userInfo: [NotificationKey.coordinate:location.coordinate])
`NotificationCenter` 를 활용해보셨네요!👍

2023-03-30 01:37 UTC, llimental commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +    private let geoCoder = CLGeocoder.init()
아래에서 setUp 메서드를 사용하면서 Manager에 대한 설정을 해주면서 locationManager와 geoCoder도 init을 썼던 것 같습니다.
이렇다 할 특별한 이유가 있지는 않아 변경하였습니다!

해당 커밋: 32ba904

2023-03-30 01:38 UTC, llimental commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +    }
설정과 실행에 대한 역할을 나누고, 그 각각을 viewController에서 호출하는 대신, 은닉화를 하고 그 메서드들을 묶은 startUpdatingLocation 메서드를 호출하도록 변경했습니다

해당 커밋: 4e4299b

2023-04-03 02:51 UTC, zdodev approved these changes
안녕하세요. @llimental , @doshkor !

궁금증에 대한 의견 및 개선된 코드 잘 확인하였습니다!

Step 2 진행하시느라 고생하셨습니다🎉

2023-04-03 02:51 UTC, zdodev commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +    }
좋습니다!👍

2023-04-03 02:52 UTC, merged