WeatherForecast [Step3] Jason & Joo
tasty-code/ios-weather-forecast pull request #16
Opened 2023-04-10 04:07 UTC by JasonLee0223

# WeatherForecast Jason & Joo

안녕하세요 븨븨(@YebinKim)🦜🦜 Jason, Joo입니다! 🙇🏻🙇🏻
이번 Step3를 구현하면서 생각보다 시간이 많이 걸렸네요...🥲
collectionView에 대해 학습을 많이 하고 들어가다보니 시간이 많이 소요됬던 것 같습니다.

요구사항의 구현 과정에서 문제가 발생하였을때 어디에서 이슈가 생기는 것인지 잘 파악하지 못하여
많이 돌아간 부분도 있는 것 같았습니다.
이번 스탭 리뷰 잘 부탁드리며 좋은 하루 보내시길 바라요 🪄🪄🪄

## 📌 Step 3 : UI구현
- [x] 앱의 UI를 구현합니다
- [x] 오토레이아웃을 활용하여 코드로만 구현
- [x] Collection View를 활용
- [x] Configuration을 활용
- [x] 화면을 위에서 아래로 끌었다 놓으면 정보를 새로고침합니다.

## 🚀 스텝 핵심 경험
- [x] collectionView HeaderView의 활용
- [x] collectionView Custom Cell의 구현
- [x] Refresh Control의 활용
- [x] collectionView 셀의 이미지 지연 로딩 문제 해결
- [x] DateFormatter 등을 활용한 날짜 표현

## 🎯 Step3 관련 스터디
- [x] collectionView
    - [x] Compositional Layout
    - [x] ListCell
    - [x] UIReusableView
    - [x] DiffableDataSource
    - [x] DataSource
- [x] DispatchGroup
    - [x] notify
    - [x] enter, leave

## 🔖 부연 설명
### 🤔 ViewModel 네이밍에 대한 고민
Step1에서 API를 통해 받아오는 데이터 타입을 Entity로 사용했습니다.    
View에 보여지는 부분을 담당하는 Model인 `ViewModel`을 로직을 넣어서 해결했어야하는데    
어떻게 네이밍을 지으면 좋을까 고민하다... `CurrentViewModel`와 `ForecastViewModel`이라고        
네이밍을 하게 되었습니다.
방학 기간을 통해 좀 더 MVVM Design Pattern을 학습하고 적용해볼 수 있도록 해야할 것 같습니다!

## 🔍 고민과 해결
### 🅰️ API 날짜 데이터
데이터를 받아와서 시간, 기온, 날씨 아이콘을 확인하는 과정에서 제대로 매칭이 되지 않은 것을 발견하였습니다.
아이콘 이미지를 비동기로 다운받는 과정에서 잘못되었다고 생각했지만,     
API에서 제공되는 데이터 dt_txt가 아닌 dt를 사용해야 되는 걸 깨닫고 변경하였습니다.
또한 DateFormatter를 변경하면서 데이터를 받아오는 타입이 Double로 받아서 이후 변환하는 게 더 편하도록 변경하였습니다.
```swift=
private extension DateFormatter {
    func convertWeatherForm(from numbericDate: Double) -> String {
        let date = Date(timeIntervalSince1970: numbericDate)
        self.dateFormat = "MM/dd(E) HH시"
        self.locale = Locale(identifier:"ko_KR")
        return self.string(from: date)
    }
}
```

### 🅱️ ListCell을 사용하는 방법
DiffableDataSource를 학습하며 공식문서 안에 있는 Sample Project를 많이 참고하게 되었습니다.
ListCell에 대한 학습은 잘하였는데 구현하는 방법이 `Configuration`을 사용하여 해결하는 방법이 많았었는데
생각보다 구현하는데 있어 필요 이상의 학습 내용이 많아서 `list(using:)` 메서드를 사용하여 해결하였습니다.
```Swift=
extension ViewController {
    private func configureCollectionView() -> UICollectionViewLayout {
        var configuration = UICollectionLayoutListConfiguration(appearance: .grouped)
        configuration.headerMode = .supplementary
        configuration.backgroundColor = UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 0.6)
        return UICollectionViewCompositionalLayout.list(using: configuration)
    }
}
```

### 🆑 CollectionLayoutListConfiguration에서 정해진 Layout
레이아웃으로 Header 높이를 설정하는 과정에서 오류가 발생이 되었습니다.
기본적으로 정해진 Layout과 겹치는 걸 알았고 해결하기 위해서 Priority를 통해서 우선순위를 주어 해결을 하였습니다.
```swift=
extension NSLayoutConstraint {
    func withPriority(_ priority: UILayoutPriority) -> Self {
        self.priority = priority
        return self
    }
}
```
## 🖥️ 실행결과
<img src = "https://user-images.githubusercontent.com/92699723/230823600-83c4112d-9a48-4c7e-87bd-6374810f1169.gif">

2023-04-10 19:52 UTC, YebinKim requested changes
제이슨, 주 안녕하세요 😄
UICollectionView 공부에 시간이 많이 걸리셨었군요..!! Step3 구현 완료까지 정말 고생 많으셨습니다! 👏👏 덕분에 저도 `UICollectionViewCompositionalLayout` 에 대해 알아갈 수 있었어요.

질문 주신 내용 중 *CollectionLayoutListConfiguration에서 정해진 Layout* 에 대한 내용은 `withPriority(_:)` 제가 수정해봤을 때 메서드를 사용하지 않더라도 UI 문제가 발생하지 않았는데 혹시 어떤 이슈가 있으셨던건지 알 수 있을까요?

또한, 현재 배경 이미지 파일의 이름이 `IMG_9695.jpg` 인 것으로 보이는데요! 의미있는 이름을 붙이면 파일 관리가 더 수월해질 거 같아요 😄

---

이번 스텝에서의 핵심 경험은 아래와 같았는데요.
<img width="306" alt="step3" src="https://user-images.githubusercontent.com/38066039/230985555-627c1ab8-159b-4e8a-b925-58ba113e9cdb.png">

학습에 어려움이 있었음에도 핵심 경험과 메인 동작 구현을 모두 달성해내느라 고생 많으셨습니다!! 😆👍
다만, 처음 프로젝트를 시작하며 디자인 패턴에 욕심을 내보기로 했어서 구조를 중심으로 코멘트를 달았는데 궁금증이 남는 부분도 있고 메모리 누수 문제가 있기도 해서 Request Changes 로 요청드렸어요~

코멘트와 관련해 궁금증이 있다면 언제든 질문 주세요 🙇🙌

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UseCase.swift
> +    private var cashedImage = NSCache<NSString, UIImage>()
```suggestion
    private var cachedImage = NSCache<NSString, UIImage>()
```
p2;

오타가 있네요! 👀

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UseCase.swift
> +                guard let icon = cashedImage.object(forKey: icon as NSString) else {
p3;

if 구문과 guard 구문이 연속되어 사용하고 있는데, 하나로 충분히 합칠 수 있을 것으로 보여요.
106번 라인과 같이 조건문을 하나로 통일해보면 어떨까요?

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/ViewController.swift
> +class ViewController: UIViewController {
p3;

해당 뷰컨트롤러가 현재 디폴트 이름인 `ViewController` 로 되어 있는데, 역할에 맞는 적절한 이름과 (상속의 가능성이 없다면) final 처리가 필요해보여요 👀

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/ViewController.swift
> +    private let useCase = UseCase()
질문;

데이터를 가져오는 비즈니스 로직(`Repository` 파일의 역할)을 소유한 `UseCase`를 ViewController가 가지고 있으며 `WeatherModelDelegate` 를 채택함으로써 모델을 업데이트하는 책임 또한 가진 것으로 보이네요 🤔
하지만 실제 코드를 확인해보면 `WeatherModelDelegate` 를 채택한 쪽이 아닌 위임을 하고자 하는 쪽에서 모델을 로딩하는 역할을 수행하고 있어서 역할 분리에 다소 혼란이 있는 거 같아요.

그리고 비즈니스 로직은 MVVM의 구조를 따를 때 VM이 가지는 것이 필요하다고 생각하는데 제이슨과 주는 어떻게 생각하실까요??

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/ViewModel/CurrentViewModel.swift
> +struct CurrentViewModel: WeatherViewModel {
질문;

현재 VM 은 데이터를 추상화하는 것 외에는 역할이 없는 것으로 보이는데, 어떤 책임과 역할을 가지도록 구현하신 걸까요? 🤔

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/ViewController.swift
> +        self.collectionView.reloadData()
p3;

UI 업데이트 작업은 메인 스레드에서 실행될 수 있도록 보장하는 것이 필요해보여요 👀

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/ViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.7) {
질문;

딜레이 시간을 준 이유가 무엇일까요? 🤔

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/ViewController.swift
> +        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
질문;

AutoresizingMask 를 사용하고자 한다면 21번 라인은 삭제가 필요해보여요! 👀
[translatesAutoresizingMaskIntoConstraints](https://developer.apple.com/documentation/uikit/uiview/1622572-translatesautoresizingmaskintoco)는 AutoresizingMask 를 사용하고자 한다면 값을 true 로 설정하는 것이 필요하다는 내용이 문서에서 설명되어 있습니다 😄
> If this property’s value is true, the system creates a set of constraints that duplicate the behavior specified by the view’s autoresizing mask.

또한, 현재 Safa Area가 지켜지지 않아서 콘텐츠가 상단바와 겹칠 때 잘 보이지 않는 문제가 있는데 해당 문제를 인지하고 계신지도 궁금합니다 🤔

<img src="https://user-images.githubusercontent.com/38066039/230968033-039ddb40-e34d-46ad-873c-32dca802644b.PNG" width="300px"/>

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +    var delegate: UserLocationDelegate?
p1;

메모리 누수가 발생하고 있네요!
메모리 누수에 대한 가능성을 알고 계셨을까요? 👀

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +        URLPath.iconList.forEach { iConElement in
p4;

다른곳에서는 iCon을 icon으로 표기하고 있는데 여기에서만 다르게 작성하고 있네요! 통일이 필요해보여요.

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/Cells/ForecastWeatherCell.swift
> +    private lazy var dateLabel: UILabel = {
질문;

lazy 를 사용한 이유가 있을까요? 👀

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Presentation/Cells/ForecastWeatherCell.swift
> +    lazy var stackView: UIStackView = {
p3;

외부에서 접근하지 않는 프로퍼티라면 private 처리가 필요해보여요.

2023-04-10 19:52 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Domain/UseCase.swift
> +            DispatchQueue.main.async {
질문;

메인 스레드에서의 실행을 보장한 이유가 무엇일까요??

2023-04-11 02:46 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/UseCase.swift
> +    private var cashedImage = NSCache<NSString, UIImage>()
넵! 오타 수정하였습니다!
해당 커밋: 5ba8e46, bfd2687

2023-04-11 02:46 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/UseCase.swift
> +                guard let icon = cashedImage.object(forKey: icon as NSString) else {
넵! 해당 부분 리펙토링하였습니다!
해당커밋: 26d0ade

2023-04-11 02:46 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Presentation/ViewController.swift
> +class ViewController: UIViewController {
적절한 네이밍으로 고민해보았는데 `ForecastWeather`, `CurrentWeather`모두 사용되어서 
`WeatherViewController`가 제일 나아보였는데 븨븨는 어떻게 생각하시나요?? 🤔

해당 커밋: ec3711b

2023-04-11 02:47 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/UserLocation.swift
> +    var delegate: UserLocationDelegate?
저희가 이 부분을 놓친 것 같습니다!

CompletionHandler에서 `@escaping`을 사용할 때 [weak self]를 통해 캡쳐할 때도 그렇고 delegate에서도 `weak`를 사용하여 메모리 누수를 신경써야했는데 아쉬운 부분이네요… 
구현 과정에서 신경을 좀 더 쓰도록 습관을 잘 들여봐야겠습니다!

추가적으로 `Instruments`를 사용해서 확인해보았습니다.

weak 키워드 사용 ❌
<img src="https://user-images.githubusercontent.com/92699723/231038873-f66610db-7eb7-49e2-b858-8a4370a6d9c6.png" width=60%>

weak 키워드 사용 ⭕️
<img src="https://user-images.githubusercontent.com/92699723/231038979-92e2bf72-a9e1-4e87-a3fe-94f7bf05c1e2.png" width=60%>

육안으로 보았을 때는 잘보이지 않았지만 항상 메모리 누수에 대해 인지하겠습니다!

2023-09-03 05:52 UTC, closed without merging