WeatherForecast [STEP 3] d.o., Lust3r
tasty-code/ios-weather-forecast pull request #17
Opened 2023-04-10 13:30 UTC by llimental

안녕하세요! 소대(@zdodev)! d.o., Lust3r입니다!

이번에는 collectionView를 구현하기까지 많은 것을 학습해야 했다보니 기간이 조금 오래 걸리게 되었습니다. 차근차근 준비해서 collectionView를 비롯 요구사항을 충족할 수 있었고, 그 과정에서 비동기 처리에 대한 고민도 해볼 수 있었습니다.

이번 리뷰도 잘 부탁드립니다! 감사합니다! 🙇🏻🙇🏻

</br>

## 📱 구현 화면
<img src = "https://user-images.githubusercontent.com/45708630/230910433-6e28a900-243b-48bb-b9a6-b3f415bb2f9c.gif" width = 300>

</br>

## 🧑🏼‍💻 작업 목록

**[ STEP 3 ] UI구현**

- [x] 앱의 UI 구현
    - [x] 오토레이아웃 활용하여 코드로만 구현
    - [x] Collection View 활용
    - [x] Configuration 활용
    - [x] 배경이미지 사용
- [x] Refresh Control 활용하여 새로고침 구현

</br>

## 📚 학습 키워드 및 학습 내용

### 1. CollectionView Header

> 출처: Apple 공식문서 - [ReusableSupplementaryView](https://developer.apple.com/documentation/uikit/uicollectionview/1618068-dequeuereusablesupplementaryview)
> 
- `Header`/`Footer`를 사용하기 위해서는 `collectionView`의 `ReusableSupplementaryView`를 사용해야 했습니다.
- `elementKind`에 `Header`인지 `Footer`인지 정해주고, `identifier`에는 `cell`과 같이 `Header`에 `static let`으로 생성한 `identifer`를 넣어주어 생성했습니다.

</br>

### 2. Refresh Control

> 출처: Apple 공식문서 - [Refresh Control](https://developer.apple.com/documentation/uikit/uirefreshcontrol)
> 
- A standard control that can initiate the refreshing of a scroll view’s contents.
``` swift
collectionView.refreshControl = UIRefreshControl()
collectionView.refreshControl?.addTarget(self, action: #selector(refreshData), for: .valueChanged)
    
@objc func refreshData() {
    locationManager.startUpdatingLocation()
    collectionView.refreshControl?.endRefreshing()
}
```
- `UIRefreshControl` 인스턴스를 `CollectionView`에 넣어준 후, `selector`에서 `locationManager`의 `startUpdatingLocation()` 메서드를 실행함으로써 새 위치 정보를 받아와 `fetchData()`까지 이뤄지도록 했습니다.

</br>

### 3. async/await

> 출처: swift 공식문서 - [Concurrency](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/)
> 
- 비동기 함수 또는 비동기 메서드는 실행 도중에 일시 중단될 수 있는 특별한 종류의 함수 또는 메서드입니다. 이는 완료될 때까지 실행되거나 오류가 발생하거나 반환되지 않는 일반적인 동기 함수 및 메서드와 대조됩니다.
- 기존 비동기 코드에서는 `URLSession`을 사용하는 코드와 그것으로부터 받아진 데이터를 활용한 아이콘 불러오기 메서드가 겹쳐 코드가 복잡했지만 `async/await`으로 비동기 함수 처리를 함으로써 간결한 구조를 만들 수 있었습니다.

</br>

### 4. DateFormatter

> 출처: Apple 공식문서 - [DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter)
> 
- 요구사항에 맞게 날짜 표시를 하기 위해서는 날짜 데이터를 `DateFormatter`를 사용하여 변환해주어야 했습니다.
```swift
let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "MM/dd(E) HH시"

let conversionTimeDataToDate = Date(timeIntervalSinceReferenceDate: TimeInterval(forecastData.timeOfData))

cell.timeLabel.text = dateFormatter.string(from: conversionTimeDataToDate)
```
- `dateFormatter` 인스턴스를 생성해준 후, 포맷을 출력하길 원하는 형식으로 맞춰주었습니다.
- 이후 `Date(timeIntervalSinceReferenceDate)`를 통해 날짜 정보를 `Date` 타입으로 변환해주었고, 앞서 맞춰준 `dateFormatter`의 양식으로 변환하여 `timeLabel`에 사용하였습니다.

</br>

## 🤔 고민과 해결

### 1. `NotificationCenter` VS `Delegate` VS `Completion`

네트워크 통신을 통해 받은 데이터를 객체 간 주고 받을 때 `NotificationCenter`를 사용했었는데요!

`post`, `addObserver`를 데이터 전송이 필요한 코드 사이에 직접 작성하기 때문에 파일이나 컴포넌트로 분리되지 않아요. 그로 인해 코드가 많아질수록 전송한 데이터를 어디서 받는지 확인하기 어려웠어요.

그래서 다른 방식으로 데이터를 전달할 수 있는 방법에 대해 알아보았어요!
- `NotificationCenter`
    - `NotificationCenter` 싱글턴 객체를 통해 이루어진다
    - 앱 내부에서 발생하는 이벤트에 대한 알림을 다수의 객체에 효과적으로 처리할 수 있다.
    - 런타임에 동작하기 때문에 컴파일 타임에 확인할 수 없는 예상하지 못한 문제점이 발생할 수 있다
</br>
- `delegate` 
    - `Protocol`을 통해 다른 객체와의 관계를 보다 의미있고 명확하게 전달할 수 있다
    - 구현해야 하는 코드가 많아진다
    - 메모리 누수에 대해 생각해야 한다
    - 하나의 객체가 여러 개의 `delegate`를 가질 수 없다
</br>
- `closure`
    - 다른 객체와의 의존성을 최소화할 수 있다
    - 객체와의 관계에 대한 이해를 코드를 통해 이해하기 어렵다

결론!
Location 데이터를 `delegate` 방식을 통해 dataTask 처리를 하였어요
또한 Network 요청 후 받은 데이터처리는 `closure를` 통해 전달하도록 구현해보았어요

</br>

### 2. Async/Await을 통한 동시성 프로그래밍
- 기존에는 Escaping Closure를 통해 weatherAPI, forecastAPI를 호출한 값과 그로부터 얻은 아이콘 정보를 가지고 이미지를 가져왔어요. 그러나 해당 방식은 여러 작업 간의 시점을 맞추기가 어렵고, 코드 들여쓰기가 많아져 가독성이 떨어지는 불편함이 있었어요.
- 이를 해결하기 위해 Async/Await을 사용하여 로직을 변경해 보았고, 기존 대비 더 효율적으로 코드를 작성할 수 있었어요.
- **기존 코드**
    ```swift
    private func callWeatherAPI()  {
        do {
            let weatherURLString = weatherURL(lat: latitude, lon: longitude)
            let weatherURL = try getURL(string: weatherURLString)
            var weatherURLRequest = URLRequest(url: weatherURL)
            weatherURLRequest.httpMethod = "GET"
            dataTask(URLRequest: weatherURLRequest, myType: Weather.self) { result in
                switch result {
                case .success(let data):
                    self.weatherData = data
                    print("(fetched)weatherData")
                case .failure(let error):
                    print("dataTask error: ", error)
                }
            }
        } catch {
            print(error.localizedDescription)
        }
    }
    ```
- **변경 코드**
    ```swift
    func callWeatherAPIConcurrency(latitude: Double, longitude: Double) async throws -> Weather? {
        let weatherURLString = weatherURL(lat: latitude, lon: longitude)
        let weatherURL = try getURL(string: weatherURLString)
        var weatherURLRequest = URLRequest(url: weatherURL)

        weatherURLRequest.httpMethod = "GET"

        let (data, _) = try await URLSession.shared.data(for: weatherURLRequest)
        let weather = try JSONDecoder().decode(Weather.self, from: data)
        print("[NetworkManager](fetched)weather")
        return weather
    }
    ```
- **ViewController+Extensions.swift**
    ```swift
    extension ViewController: LocationManagerDelegate {
        func fetchData() {
            guard let coordinate = locationManager.getCoordinate() else { return }
            Task {
                weather = try await networkManager.callWeatherAPIConcurrency(latitude: coordinate.latitude, longitude: coordinate.longitude)
                forecast = try await networkManager.callForecastAPIConcurrency(latitude: coordinate.latitude, longitude: coordinate.longitude)

                guard let weatherIconString = weather?.weather.first?.icon else { return }
                weatherIcon = try await networkManager.getWeatherIconCuncurrency(weatherStatus: weatherIconString)

                guard let forecastList = forecast?.list else { return }
                forecastIcons = try await networkManager.getForecastIconCuncurrency(forecastList: forecastList)
            }
        }
    }
    ```

</br>

## 🙋🏻 질문 거리

### 1. ViewController의 역할
- `weather`, `forecast` 인스턴스 말고도, iconData를 `collectionView`에서 사용해야 하다보니, `ViewController`에 아이콘 데이터를 갖는 인스턴스를 두 개 생성하였습니다(`weatherIcon`, `forecastIcons`). 이뿐만 아니라 각각은 데이터가 바뀌면 `collectionView`에 반영하기 위해 `collectionView reload`를 didset에서 하게 되는데 그러다보니 `ViewController`에서 하는게 많고 각각이 `reloadData()`를 수행하니 무겁다고도 느껴집니다. 그렇다고 분리하자니 작업이 이뤄지는 곳이 `ViewController`이기 때문에 고민이 됩니다. 혹시 이러한 구조 개선에 대한 소대의 의견 받을 수 있을까요?

</br>

### 2. 비동기 작업의 종료 시점 맞추기
- `ViewController+Extensions.swift` 에서 `fetchData()` 메서드를 통해 각 비동기 작업을 `Task`로 묶어 호출을 했고, 이렇게 받아진 데이터를 `CollectionView`의 각 항목을 구성하는데에 사용해봤어요. 그런데 실제로 실행해보면 첫 번째 실행에서는 일반적인 `weather`, `forecast` 데이터만 먼저 출력이 되고, `Header`와 `cell`의 `icon data`는 살짝 늦게 출력이 됨을 알 수 있었어요. 두 번째 부터는 앱에 대한 로딩이 빨라져서 그런지 거의 동시에 출력되긴 하지만 첫 실행에서도 동일하게 보여주기 위해서는 어떤 작업이 더 필요할 지 여쭤보고 싶어요!

</br>

### 3. LocationManager 권한 문제
```swift
func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
    switch manager.authorizationStatus {
    case .authorizedWhenInUse, .authorizedAlways:
        manager.requestLocation()
    default:
        manager.requestWhenInUseAuthorization()
    }
}
```
- 위 코드와 같이 `locationManagerDidChangeAuthorization(_ manager:)` 메서드를 사용하여 `locationManager`의 권한 상태가 사용할 때, 항상 허용이라면 위치정보를 요청하고, 그 외의 경우에는 권한을 요청하는 분기를 해주었어요.
- 하지만 처음 앱을 실행했을 때 권한 요청이 나오고, 여기서 허용을 하지 않으면 다음 번에 앱을 실행했을 때 권한을 요청하지 않았어요.
- 공식문서에서는
`Core Location`은 사용자의 작업이 인증 상태 변경을 초래하고 앱이 `CLLocationManager`의 인스턴스를 만들 때 앱이 포그라운드에서 실행되든 백그라운드에서 실행되든 항상 `locationManagerDidChangeAuthorization(_:)`을 호출합니다.
라고 되어 있어 시뮬레이터 상에서는 위치정보 동의 설정을 바꿀 수 없지만 앱을 껐다가 재실행하면 인스턴스를 만들 때 다시 요청할 것이라 생각했어요. 하지만 프로젝트를 다시 설치하지 않는 한 재요청이 이뤄지지 않아 이에 대해 여쭤보고 싶었어요!

2023-04-11 13:38 UTC, zdodev requested changes
안녕하세요. @llimental , @doshkor 

스텝 3 구현 잘 진행해주셨습니다!👍

먼저 질문에 대한 제 생각을 적어보았습니다.

❓ ViewController의 역할

- 매번 `reloadData()` 로 셀을 갱신하면 무겁다고 생각이 들 수 있을 것 같습니다. 이에 대해서 `reloadItems(at: [IndexPath])` 과 같은 메서드를 사용하여 업데이트가 필요한 부분만 사용하는 것이 좋을 수 있을 것 같습니다. 두 방법 다 장단점이 있어 확인해보면 좋을 것 같습니다!
- 아래 링크의 더 효율적이고 개선된 방식으로 컬렉션 뷰를 구현하는 것도 방법이 될 것 같습니다!
- [link](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/implementing_modern_collection_views)

❓ 비동기 작업의 종료 시점 맞추기

- `Swift Concurrency` 동작 원리에 대해 이해가 더 필요할 것 같습니다. Task 내 await 구문이 여러 개가 존재할 경우 어떻게 동작하는지 알아보면 질문과 같은 현상을 더 잘 이해할 수 있지 않을까 싶습니다!

❓ LocationManager 권한 문제

- iOS 앱 사용권한에 대해 알아보면 좋을 것 같습니다! 일반적으로 사용자 위치 권한은 요청할 당시 1번만 팝업이 출력됩니다. 그 이후에는 앱에 설정된 권한에 따라 동작하게 됩니다.
- `locationManagerDidChangeAuthorization` 메서드의 용도와 `authorizationStatus` 의 권한 종류들에 대해서 확인해보면 좋을 것 같습니다!

몇 가지 궁금증을 남겨보았습니다.
확인 부탁드립니다!

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Location/LocationManager.swift
> +    }
*get* 용어를 사용하는 것 보다는 명사형으로 이름을 짓는 것은 어떨까요?
```swift
func address() -> String
```
또는 단순히 address만 얻는다면 `private(set)` 을 활용해는 것도 좋을 것 같습니다!

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Location/LocationManager.swift
>      }
메서드의 반환 타입이 옵셔널이라면 옵셔널 바인딩을 하지 않고 `coordinate` 를 바로 반환해도 좋을 것 같습니다!
또는 `address` 처럼 `private(set)` 을 활용해는 것도 좋을 것 같습니다!

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Network/NetworkManager.swift
> +    func callWeatherAPIConcurrency(latitude: Double, longitude: Double) async throws -> Weather? {
Concurrency API 를 사용해보셨네요!👍
메서드 이름에 `Concurrency` 를 붙인 이유가 궁금합니다!

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Network/Protocol/NetworkTaskProtocol.swift
>  extension NetworkTaskProtcol {
`NetworkManager` 타입에서 네트워크 관련 코드를 변경하면서 `NetworkTaskProtcol` 프로토콜의 역할이 없어진 것 같습니다.
이 코드를 어떻게 하는 것을 좋을까요?

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/WeatherCollectionView.swift
> +//        layout.sectionInset = UIEdgeInsets(top: 200, left: 200, bottom: 200, right: 200) // 각 섹션의 마진
불필요한 주석은 제거하면 좋을 것 같습니다!

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/WeatherCollectionViewCell.swift
> +        addSubview(tempImage)
UICollectionViewCell 의 `contentView` 를 활용하지 않은 이유가 있을까요?

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/WeatherCollectionViewHeader.swift
> +        NSLayoutConstraint.activate([
헤더뷰에서 Layout Issues 가 발생하고 있습니다! 해결해볼 수 있을까요?
<img width="939" alt="스크린샷 2023-04-11 오후 9 33 05" src="https://user-images.githubusercontent.com/67548251/231179246-50c3d323-dc5e-419e-a7e7-94fa428eb347.png">

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +        collectionView.backgroundColor = UIColor(red: 0, green: 0.0, blue: 0.0, alpha: 0)
`UIColor.clear` 사용하면 더 깔끔할 것 같습니다!

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/ViewController+Extensions.swift
> +        }
셀 내부 프로퍼티에 직접 접근하여 설정하기 보다는 셀에게 역할을 넘기는 것은 어떨까요?

2023-04-11 13:38 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/ViewController+Extensions.swift
> +            }
셀 내부 프로퍼티에 직접 접근하여 설정하기 보다는 셀에게 역할을 넘기는 것은 어떨까요?

2023-04-13 04:17 UTC, doshkor commented on WeatherForecast/WeatherForecast/View/WeatherCollectionViewHeader.swift
> +        NSLayoutConstraint.activate([
`height` 혹은 `bottomAnchor` 속성 정의로 해결할 수 있었습니다.

2023-04-13 07:01 UTC, llimental commented on WeatherForecast/WeatherForecast/View/WeatherCollectionView.swift
> +//        layout.sectionInset = UIEdgeInsets(top: 200, left: 200, bottom: 200, right: 200) // 각 섹션의 마진
확인 후 제거하였습니다!

관련 커밋: [75383ab](https://github.com/tasty-code/ios-weather-forecast/pull/17/commits/75383ab413b8ccc64af838049c9c808f2da8dee4)

2023-04-13 07:04 UTC, llimental commented on WeatherForecast/WeatherForecast/Model/Network/Protocol/NetworkTaskProtocol.swift
>  extension NetworkTaskProtcol {
해당 프로토콜 내 메서드를 사용할 일이 없어 제거하였습니다!

관련 커밋: [de8288c](https://github.com/tasty-code/ios-weather-forecast/pull/17/commits/de8288c94860b1e1132e7354af7920528c7764ef)

2023-04-13 07:04 UTC, doshkor commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +        collectionView.backgroundColor = UIColor(red: 0, green: 0.0, blue: 0.0, alpha: 0)
clear 란 속성을 알게 되었어요👍

해당 커밋: 30c0b13

2023-04-13 07:05 UTC, doshkor commented on WeatherForecast/WeatherForecast/Controller/ViewController+Extensions.swift
> +        }
말씀하신대로 `view` 에 관련된 내용이라 `cell` 의 역할인게 더 자연스러운것 같아요!

해당 커밋: 197cc3a

2023-04-13 07:05 UTC, doshkor commented on WeatherForecast/WeatherForecast/Controller/ViewController+Extensions.swift
> +            }
위와 동일하게 처리하였습니다.!

2023-04-13 07:06 UTC, llimental commented on WeatherForecast/WeatherForecast/Model/Network/NetworkManager.swift
> +    func callWeatherAPIConcurrency(latitude: Double, longitude: Double) async throws -> Weather? {
동시성 의미를 강조하고자 붙였었는데, 뒤에 async가 있기 때문에 없어도 무방할 것 같습니다.
논의 후 메서드명 변경하는 쪽으로 진행했습니다!

관련 커밋: [bef6183](https://github.com/tasty-code/ios-weather-forecast/pull/17/commits/bef618331bf5b16240c87fa63ec1deab582e4c0f)

2023-04-13 07:09 UTC, llimental commented on WeatherForecast/WeatherForecast/Model/Location/LocationManager.swift
> +    }
private(set)의 정확한 의미에 대해 몰랐어서 학습 후 적용하였습니다.
원래 private로 하면 선언된 곳에서만 사용이 가능한 것에 반해, private(set)으로 설정하게 되면 변경을 하지 않는 이상 읽기는 선언한 곳 밖에서도 사용할 수 있음을 알게 되었습니다.

address에 적용하면서 아래에 코멘트 달아주신 coordinate도 적용해보았고, 메서드가 필요없어 제거할 수 있었습니다!

관련 커밋: [16775ee](https://github.com/tasty-code/ios-weather-forecast/pull/17/commits/16775eeed1ac4b74b18d1f2546f81e6ab0dbee79)

2023-04-13 07:09 UTC, doshkor commented on WeatherForecast/WeatherForecast/View/WeatherCollectionViewCell.swift
> +        addSubview(tempImage)
cell 에 `contentView` 라는 속성이 있고, 그 속성에 addSubview 해야 한다는 것을 알게 되었어요.!

해당커밋: 0c8e3d1

2023-04-13 13:21 UTC, zdodev approved these changes
안녕하세요. @llimental , @doshkor !

피드백에서 남긴 궁금증에 대해 적절하게 개선해보셨네요👍
Layout Issues 도 잘 해결해보셨네요!👍

코멘트만 확인하고 마무리하면 될 것 같습니다.
Step 3 진행하시느라 고생하셨습니다!

2023-04-13 13:21 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Location/LocationManager.swift
> +    private(set) var coordinate: CLLocationCoordinate2D?
👍

2023-04-13 13:21 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/ViewController+Extensions.swift
> +        }
모델을 두어 셀에게 전달하는 방식으로 구현하면 더욱 깔끔해질 것 같습니다!

2023-04-13 13:21 UTC, merged