WeatherForecast [Step1] Jason & Joo
tasty-code/ios-weather-forecast pull request #2
Opened 2023-03-16 12:15 UTC by JasonLee0223

안녕하세요 븨븨(@YebinKim)! 이번 날씨 앱 진행하게된 Jason, Joo입니다! 🙇🏻🙇🏻
저희는 이번 한 주동안 Step1을 구현하면서 다양한 공부를 진행할 수 있었습니다!

이번에는 API를 호출하여 데이터 모델을 만들어서 사용해볼 수 있는 첫 번째 프로젝트였습니다!
이전 프로젝트에서 MVC 디자인 패턴을 많이 사용해보아서 이번에 욕심을 좀 내서 MVC로 구현한 뒤 
MVVM으로 리펙터링 해보려고합니다. (그룹을 만들때는 MVVM패턴으로 적용하여 구현하였습니다.)

기한을 맞추다 보니 코드가 조금 더 분리할 수 있었는데 다 마무리하지 못한 점이 아쉽네요..🥲
이번 스탭 리뷰 잘 부탁드리며 좋은 하루 보내시길 바라요 😋

## 📌 Step 1 모델/네트워킹 타입 구현
### Step 1-1
- Open Weather Map에서 제공하는 날씨 API의 데이터 형식을 고려하여 모델 타입을 구현합니다.
    - Open Weather Map에서 제공하는 데이터 벌크를 활용해보세요.
- 현재 날씨를 받아오는 API와 5일 예보를 받아오는 API가 다릅니다.
    - https://api.openweathermap.org/data/2.5/weather
    - https://api.openweathermap.org/data/2.5/forecast
- 앱에서는 현재 날씨를 보여주는 기능과 5일 예보를 보여주는 기능 모두 갖추고 있습니다.
- API를 통해 전달받은 JSON 데이터를 활용할 수 있도록 모델 타입을 구현해봅니다.
    - Step 1-1에서는 API 서버와 실제 통신을 하지 않는 모델 타입만 구현합니다.
- 제약사항
    - 날씨 정보를 받아오는 포멧은 JSON을 사용합니다.
    - 날씨 정보는 위도/경도를 사용하여 받아옵니다.

### Step 1-2
- Open Weather Map에서 제공하는 날씨 API의 데이터를 실제로 받아올 수 있는 네트워킹 타입을 구현합니다.

## 🚀 스텝 핵심 경험
- 파싱한 JSON 데이터와 매핑할 모델 설계
- CodingKeys 프로토콜의 활용
- API 서버와 통신할 인스턴스 역할을 수행할 타입 구현
- 범용성과 재사용성, 유연성을 고려한 네트워킹 타입 구현
- 라이브러리 없이 URLSession을 활용하여 구현

## 🎯 API 사용 관련 스터디
### Postman을 사용한 내용 확인
- API 사용을 하기 위해서 API KEY 발급 및 쿼리 사용에 대해서 숙지했습니다

<img src="https://i.imgur.com/D8IAFr4.png" width="60%">

### postman을 활용하여 실제 데이터 확인
- API 사용에 대해서 숙지한 내용을 토대로 postman을 활용하여 데이터가 어떻게 들어오는지 확인을 했습니다

<img src="https://user-images.githubusercontent.com/79438622/225611333-391af8f1-50b2-4c76-911f-0a0234a22ea9.png">

### 🌝 🌚 APIKEY를 숨기는 방법
PR이 너무 길어질 것 같아 링크로 남깁니다! 진행하는 부분은 함께 해결하였습니다!
[🌐 APIKEY 숨기는 방법](https://github.com/JasonLee0223/TIL/blob/main/Project-Setting/HowToHideMyAPIKEY.md)

PR을 보낼 때 링크를 남기는 방법이 옳지 않다면 다음에는 고쳐보겠습니다!

## 🙋🏻 질문 있습니다!!
### 🟢 URLComponents를 이용한 쿼리 관리
현재 날씨와 5일 날씨 예보의 중복되는 코드를 줄이기 위하여 쿼리를 동일하게 관리 하기 위해 URLPath 타입을 만들고 URLComponents로 관리를 하였습니다. 
URLComponents를 제대로 만들지 못한다거나 URLComponenet에서 url을 반환하지 못 하는 경우, 형식이 잘못된 URL를 의미하는 URLError의 `.badURL`를 사용하였습니다. 
URLComponents에서도 URLError를 사용해도 괜찮은지 궁금합니다

### 🟡 dataTask에서 에러 처리
위 내용의 연장선으로 URLSession의 dataTask를 사용할 때, `data`, `response`, `error`에 대한 처리를 하기 위해서 guard문에서 에러 처리를 하는 과정에서 어떻게 해야 좋을지 궁금합니다. 
HTTP와 같이 단순하게 상태 코드를 반환하기 위해서 URLError를 이용한 반환으로 생각을 하였지만 옳은 판단인지 궁금합니다. 
사용자의 입장에서는 통신에 관련된 자세한 에러를 알려주는 건 무의미한 거 같은데, 븨븨는 어떻게 에러를 처리하는지 궁금합니다 🙄

### 🟢 API 프로퍼티의 중복 해결 방법
이번 프로젝트의 API를 확인해보니 중복되는 타입이 생각보다 많았고 어디에서는 사용하고 안쓰는 프로퍼티들이 많았습니다.
Step1-1의 Mock Entity를 구현하고나서 Step1-2의 네트워크 모델(Entity)를 구현할 때 중복되는 타입들로 인해 에러를 자주 마주쳤습니다.

하여 네이밍을 변경하여 사용하였는데 좀 더 효과적인 방법으로는 Target Membership을 해제하는 방법을 생각해보았습니다.
(Mock은 Test를 위해 사용된다고 판단되어 UnitTest에 사용될 목적으로 쓰여지게 Target을 바꾸면 되지않을까 생각했습니다.)

다른 좋은 방법이 있는지 알려주실 수 있을까요?? 🤔

### 🔴 Generic과 타입 추론?
Generic을 자주 사용하지 않았는데 이번에 CurrentWeather와 ForecastWeather 2가지 형태의 데이터 구조 모델을 사용하게 되어
좀 더 다형성을 주고자 Generic을 사용하여 모두 위 2개의 타입 모두 받아보려고 시도해보았습니다.
아래 코드는 구현과정에서 시도해보았던 코드입니다.

```Swift
class Repository {
    func loadData(type: URLPath, location: CLLocationCoordinate2D) {
        guard let url = try? URLPath.configureURL(coordintate: location, getPath: type) else {
            return
        }
        
        let session = URLSession.shared
        
        session.dataTask(with: url) { data, response, error in
            guard error == nil else {
                if (error as? URLError)?.code == .timedOut {
                    print(error?.localizedDescription ?? error.debugDescription)
                }
                return
            }
            
            guard let httpResponse = response as? HTTPURLResponse,
                  (200...299).contains(httpResponse.statusCode) else {
                print((response as? HTTPURLResponse)?.statusCode ?? 404)
                return
            }
            
            guard let data = data else {
                return
            }
            
            guard let wishData = loadJSON(weatherType: type.getWeatherMetaType, weatherData: data) else {
                return
            }
            print(wishData)
        }.resume()
    }
    
    private func loadJSON<T>(weatherType: WeatherModel.Type, weatherData: Data) -> T? where T: WeatherModel {
        let decoder = JSONDecoder()
        
        do {
            let wishData = try decoder.decode(weatherType, from: weatherData)
            return wishData as? T
        } catch {
            print("Unable to decode \(weatherData): (error)")
            return nil
        }
    }
}
```
위와 같이 작성하였을 때 아래의 에러 메세지를 확인하게 되었습니다.
> Generic의 'T'파라미터를 추론하지 못한다.
 
<img src= "https://user-images.githubusercontent.com/92699723/225604632-0b5c0d78-6bb0-45d0-85ad-4ee00e23f0a2.png">

처음에는 decodable 프로토콜을 채택해주었기에 `where T: Decodable` 라는 조건을 주어 타입을 추론할 수 있도록 해보았지만
실패하여 WeatherModel이라는 빈 프로토콜을 생성 후 채택하여 `where T: WeatherModel` 라는 조건으로 변경하여 진행하게 되면서
return 할 때 T로 다운캐스팅(?)해서 반환을 해야 하고 컴파일 단계에서는 타입을 추론하지 못 한다는 것을 확인하였고 이런 방식에서는 제네릭을 사용하면 안되는 건지 궁금합니다.

### ⚠️ MVVM패턴 적용을 위한 데이터 그룹화
이번 프로젝트에서는 조금 욕심을 내어 MVVM 패턴을 적용해보려고합니다!
아래의 링크들을 통해 학습중인데 CleanArchitecture + MVVM의 내용이 아직 많이 어렵게 느껴지네요..

[곰튀김님 강의](https://www.youtube.com/watch?v=M58LqynqQHc&t=1481s&ab_channel=%EA%B3%B0%ED%8A%80%EA%B9%80)
[CleanArchitecture + MVVM Blog](https://tech.olx.com/clean-architecture-and-mvvm-on-ios-c9d167d9f5b3)
[CleanArchitecture + MVVM GitHub Repo](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM)

- [x] 현재까지 이해한 부분으로는 Data의 3가지 형태
    - [x] Entity: 서버로부터 받은 원천 데이터
    - [x] Model: 비즈니스 로직에서 사용하는 근본 데이터
    - [x] ViewModel: 화면에 보이기 위한 화면 데이터

- [x] 데이터의 의존성 관계
    - [x] View -> Service -> Repository
    - [x] ViewModel -> Model -> Entity

- [x] Domain, Presentation, Data 각각의 Layer에 대한 이해
    - [x] Presentation Layer(MVVM) = ViewModel(Presenters) + Views(UI)
    - [x] Domain Layer = Entities + UseCases + Repositories Interfaces
    - [x] Data Repositories Layer = Repositories Implementation + API(Network) + Persistence DB

위 내용을 바탕으로 아래와 같이 이번 프로젝트에 적용해보았습니다.

<img src ="https://user-images.githubusercontent.com/92699723/225612008-32d91150-740a-4970-b852-9cfc6fcd3781.png" width="30%">

지금까지 MVC 패턴으로 프로젝트를 진행하면서 ViewController에게 너무 많은 역할을 부여하는 부분이 아쉬워 MVVM을 적용해보려고 했습니다.
Model과 View는 서로를 모르게 하는 것처럼 MVVM에 대한 큰 범주로는 이해가 되었지만 세부적인 내용에서 정말 많이 어려운 개념이구나...
느끼게되어 이번에 한 번 제대로 알고싶다는 욕심이 생기네요!

지금까지 학습한 내용을 바탕으로 Infrastructure는 외부 API를 받아와 Networking에 사용하게 될 때 필요한 구조라고 이해했는데
명확하게는 모르는 것 같아 질문드립니다! 그리고 Repository의 개념이 잘 이해가 안되네요.. 🥲
좋은 참고자료 혹은 조언 부탁드립니다!

## 💻 실행 결과
<img src = "https://user-images.githubusercontent.com/92699723/225599788-291a71eb-26e0-40c2-b68f-97359bed5e78.png" width="50%">

2023-03-16 21:43 UTC, YebinKim requested changes
제이슨, 주디 안녕하세요~
날씨 앱 프로젝트 리뷰를 함께하게 된 비비입니다 😄

폴더링 구조가 Clean Architecture에서 자주 사용하는 용어로 이루어져 있어서 처음 프로젝트를 열었을 때는 Clean Architecture 구현을 목표로 하신 줄 알았는데, 최종 목표는 MVVM이군요! 👀
아키텍쳐 구조에 신경쓰며 리뷰를 진행하겠습니다 ☺️

리뷰 코멘트 확인 전 아래 내용 한 번 확인 부탁드릴게요~

```
코멘트는 중요도에 따라 priority 1~5 로 등급을 매겨 작성하고 있습니다.
p1이 가장 수정을 위한 우선 순위가 높으며,
p5는 수정을 해도 OK, 안 해도 OK 정도로 우선 순위가 낮습니다.

또한, p1, p2 코멘트가 있을 때는 Request Changes 를 요청드리고 있습니다.
참고 부탁드려요 🙇
```

---

### 1. URLComponents를 이용한 쿼리 관리
`URLError` 를 사용함에 있어서 어떤 우려점이 있는지 잘 이해하지 못 했어요 🤔
사용하지 않아야 한다면 그 이유가 무엇이라고 생각하셨을까요?

### 2. dataTask에서 에러 처리
저도 사용자에게 에러의 내용을 자세히 알려주는 것은 무의미하다고 생각해요!
다만, 서비스에서 버그가 발생했을 때, 이를 문의하는 과정에서 **개발자에게 오류 상황을 정확히 전달할 수 있도록** 에러 코드 또는 미리 정의된 에러 메세지를 전달하는 것은 필요하며 이를 위해 에러 코드(상태 코드)를 반환하는 것은 유의미하다고 생각합니다 😄

저는 통신 중 에러를 처리할 때 [Result](https://developer.apple.com/documentation/swift/result) 타입을 자주 활용하는 편인데요.
이 타입을 활용하면 성공적으로 데이터를 받아왔을 때와 문제가 발생했을 때의 두 가지 상황 모두를 간편하게 결과 값으로써 반환할 수 있고, 에러 처리는 결과를 받아온 이후 개발자를 위한 로그와 사용자를 위한 얼럿을 적절히 띄우는 방식으로 작업하는 편입니다~

### 3. API 프로퍼티의 중복 해결 방법
제가 스텝 요구 사항을 읽어보면서 `Mock Entity` 가 왜 필요한지, 실제로 사용할 `Entity` 와 따로 구현해야 하는지 잘 이해하지 못 했어요 😅 
UnitTest 밖에서 사용할 일이 없고 일단 오류를 해결하고자 한다면 작성해주신 것 처럼 타겟을 분리하거나 아예 테스트 모듈에 해당 타입을 추가하는 방법 등으로 해결할 수 있겠지만.. **테스트의 목적은 실제로 사용할 타입이 잘 동작하는지 확인**하는 것이라고 생각하기 때문에  `Mock Entity` 의 필요성이 현재는 잘 이해되지 않아요 🤔 이 의문을 해결해야 정확한 답변이 가능할 거 같습니다 😄

### 4. Generic과 타입 추론?
요거 어떻게 설명해야 간단할지 엄청 고민했는데요..!!

이전에 작성하신 코드에서 오류가 발생한 이유는, `loadJson` 메서드에서 프로토콜을 반환하고 있기 때문에 `wishData` 가 WeatherModel 를 준수하는 타입(CurrentWeather 또는 ForecastWeather, 이를 **실존 타입**이라고 할게요)이 되어야 하는데, 이 타입이 결정되는 시점이 런타임이기 때문에 타입 추정을 할 수 없어서 컴파일 에러가 발생하고 있는 상황이에요.
작성하셨던 코드에서 간단히 에러를 해결하자면 아래와 같이 wishData 의 타입을 실존 타입으로 명시해주면 되는데요.
```swift
guard let wishData: CurrentWeather = self.loadJSON(weatherType: type.getWeatherMetaType, weatherData: data) else {
    return
}
```

현재 원하는 동작은 `wishData` 가 `WeatherModel` 을 준수하는 타입을 받고자 하는 것이기 때문에 이와 같이 CurrentWeather 타입으로 고정해버리면 원하는대로 동작이 되지 않겠죠 😇

그래서 프로토콜을 제네릭하게 사용하고자 한다면(실존 타입으로서 사용하지 않길 원한다면) 현재와 같이 메서드에 제네릭을 추가하는 것이 아닌 protocol associatedType 과 any 를 활용하는 것이 필요해요.
여기서 any 키워드는 실존 타입(existential type) 의 타입을 지워주는 역할을 하는 키워드를 얘기합니다 ([링크](https://github.com/apple/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md#type-erasing-resulting-values))
**실존 타입** 에 대한 얘기는 Swift 공식 [문서](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/protocols/#Protocols-as-Types)에서 확인할 수 있어요.

여기까지의 설명을 모두 이해하고 넘어갈 필요는 없다고 생각해요! 다만 혹시 추가로 궁금한 점이 있다면 추가로 질답 나눠보아요 😆 (DM 주세요!!)

---

Step1 진행 고생 많으셨어요~

이번 스텝에서의 핵심 경험은 아래와 같았는데요.
<img width="391" alt="step1" src="https://user-images.githubusercontent.com/38066039/225759110-71c2d848-eb15-47cc-9f7d-7e8e4a7f7ddc.png">

핵심 경험은 모두 충족했지만 네이밍과 관련해 p2 코멘트가 있어 Request Changes 로 요청드렸습니다 🙇

관련해서 궁금한 점 또는 그 외 프로젝트 진행 중 궁금한 점이 있으면 편히 질문 주세요~!! ☺️🙌
(그리고 현재 커밋 빈도가 한 명에게 치우친 것으로 보이는데 혹시 페어 프로그래밍 진행이 원활히 이루어지고 있을까요?? 👀)

2023-03-21 06:08 UTC, ohdair commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/URLPath.swift
> +        guard var components = URLComponents(string: "https://api.openweathermap.org/data/2.5/\(getPath.rawValue)") else {
아래와 같이 연산 프로퍼티를 추가하여 사용했습니다
```Swift
enum URLPath: String {
    case currentWeather
    case forecastWeather
    
        var path: String {
        switch self {
        case .currentWeather:
            return "weather"
        case .forecastWeather:
            return "forecast"
        }
    }
    // code
}
```

2023-03-21 06:29 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Configuration/Extension+APIKEY.swift
> +            return ""
위 내용은 디스코드로 질문드렸던 내용을 적용하여 .xcconfig 파일을 추가하여 진행하였습니다!
```Swift
guard let weatherAPIKEY = Bundle.main.object(forInfoDictionaryKey: "WeatherAPIKEY") as? String else {
    fatalError("Weather API KEY is E.M.P.T.Y !!")
}
...

let appid = URLQueryItem(name: "appid", value: weatherAPIKEY)
```
정상적으로 작동하는것까지 확인하였습니다. 이 부분에서는 KEY값을 받지 못하면 아예 실행할 수 없다고 판단하여
fatalError를 사용하였습니다..👀

2023-03-21 06:29 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/URLPath.swift
> +    var getWeatherMetaType: WeatherModel.Type {
```Swift
var weatherMetaType: WeatherModel.Type
```
PR보내기전에 좀 더 꼼꼼히 확인해보겠습니다! 집어주셔서 감사합니다! ㅎㅎ

2023-03-21 06:30 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/URLPath.swift
> +    static func configureURL(coordintate: CLLocationCoordinate2D, getPath: URLPath) throws -> URL {
자연스럽게 읽히기는 부분이 `caller`의 입장에서 느껴지는 부분이라고 학습했었는데 이 부분은 놓친 것 같네요..ㅎㅎ😅
아래 코멘트도 함께 수정하였습니다!
```Swift
static func configureURL(with coordintate: CLLocationCoordinate2D, getPath: URLPath) throws -> URL

func loadData(location: CLLocationCoordinate2D, path: URLPath) throws {
        let url = try URLPath.configureURL(with: location, getPath: path)
```

2023-03-21 06:46 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/Entities/NetworkEntity/CurrenctWeather.swift
> +    let weather: [Weather]
```Swift
let weathers: [Weather]
```
변경하였습니다!

2023-03-21 06:47 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/Entities/NetworkEntity/CurrenctWeather.swift
> +    let TimeOfDataCalculation: Double
```Swift
struct CurrentWeather: WeatherModel {
...
   let timeOfDataCalculation: Double
}
```
```Swift
struct WeatherData: Decodable {
    let timeOfDataCalculation: Double
...
}   
```
모두 변경하여 적용하였습니다! 프로퍼티가 너무 많아서 놓친 것 같습니다..🥲

2023-03-21 06:48 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Domain/Entities/NetworkEntity/SubEntity/WeatherData.swift
> +    let TimeOfDataCalculation: Double
위에 함께 수정하였습니다!

2023-03-21 06:53 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +                    print(error?.localizedDescription ?? error.debugDescription)
위 내용을 저희 질문사항에 dataTask의 에러처리를 Result 타입으로 구현하는 방법을 추천해주셔서 그렇게 진행해보려고합니다!
현재 로직이 크지 않아서 추후 Step2에서 함께 리펙터링을 진행해보려고하는데 괜찮을까요??

2023-03-21 06:53 UTC, JasonLee0223 commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +    func loadData(type: URLPath, location: CLLocationCoordinate2D) {
위 코멘트와 함께 처리하였습니다!

2023-03-21 06:53 UTC, ohdair commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +import CoreLocation
중복으로 프레임워크를 부르는 부분은 `import Foundation`를 삭제하였습니다

2023-03-21 06:55 UTC, ohdair commented on WeatherForecast/WeatherForecast/Domain/Entities/NetworkEntity/CurrenctWeather.swift
> +    let sys: WeatherSystem
말해주신 부분을 `sys`에서 `weatherSystem`으로 변경하여서 표현했습니다

2023-03-21 07:13 UTC, JasonLee0223 commented
### 1. URLComponents를 이용한 쿼리 관리
이 부분에 대해서는 URLError 타입이 URL을 통해 데이터를 Load하는 과정에서 나타나는 에러코드가 해당된다고 생각되었습니다.
`Components`를 통해 URL을 구성하는데 있어 URLError타입을 사용하는게 올바른지 모호하다고 생각되어 질문하게 된 부분이었습니다.
(URLError(.badURL) 사용에 있어 모호하다고 생각되었습니다.)
하여 리펙터링 과정에서 `URLComponentsError` 타입을 구현하여 해결하였습니다!

### 2. dataTask에서의 에러 처리
위 내용을 comment에서 언급해주셨어요! 
하여 `Result` 타입을 사용하여 처리하고자 하는데 아직 로직이 작아 다음 스텝에서 진행해보면 좀 더 명확하게 알 수 있지 않을까 싶습니다!

### 3. API 프로퍼티의 중복 해결 방법
요구사항에 데이터벌크를 사용하여 Mock 데이터 타입을 구현해보라는 내용이 있어 구현하였습니다.
Joo하고 상의한 결과 MockEntity로 표현되는 부분은 Test에 적합하다고 생각되어 Test 그룹으로 파일을 옮기고 
추후에 MockURLSession을 만들어 (기존 URLSession처럼 동작하는지 확인하는 Test방법이 있더라구요!) 경험해보려고합니다!

### 4. Generic과 타입 추론
알려주신 부분을 통해 Protocol에서 associatedType을 사용하여 여러 타입을 받을 수 있게 적용할 수 있다는 부분을 
야곰 책에서도 Generic 파트에서 확인할 수 있었어요! 아직 개념이 너무 어렵게 느껴져서 학습한 뒤에 적용해보려고 합니다...😂
좋은 의견주셔서 감사합니다!!

2023-03-21 17:06 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Infrastructure/Networking/Repository.swift
> +                    print(error?.localizedDescription ?? error.debugDescription)
네엡~! 이후 스텝에서 리팩토링 진행해보아요 😄

2023-03-21 23:04 UTC, YebinKim approved these changes
주, 제이슨 안녕하세요~
Step1 코멘트 확인해주셔서 감사하고, 수정까지 진행하느라 고생 많으셨습니다!

이번 스텝은 여기서 머지할게요 😄

---

### 1. URLComponents를 이용한 쿼리 관리
아하 URLError 를 통해 제공되는 에러 타입이 이번 프로젝트 API의 에러 타입과 잘 매칭되는지에 대한 질문이었군요!
저는 사용해도 문제가 없다고 생각하는데 이번엔 `URLComponentsError` 커스텀 타입을 구현했으니 이대로 활용해보아요 👀

### 2. dataTask에서의 에러 처리
확인했습니다~ Result 타입 활용 중 궁금한 점이 있으면 말씀해주세요 😄

### 3. API 프로퍼티의 중복 해결 방법
데이터벌크를 사용하여 Mock 데이터 타입을 구현해보라는 내용이 요구사항에 있었군요 🤔
MockEntity 를 사용해 테스트하고자 하는게 무엇인지 여전히 의문이 남는데 이 부분은 추후 스텝을 진행하며 활용하는 모습으로 확인해볼게요~ 확인 감사합니다 ☺️

### 4. Generic과 타입 추론
네엡! 이 부분은 다음에 다시 확인해보면 좋을 거 같아요 ㅎㅎ

2023-03-21 23:04 UTC, merged