날씨 앱 [STEP1] comdori, 뉴준성
tasty-code/ios-weather-forecast pull request #24
Opened 2023-11-22 08:43 UTC by comdori-wj

리뷰어: @forestjae

버드: @comdori-wj, @newJunsung

---

안녕하세요. 숲재! 

날씨 앱을 함께하게 되어 반갑습니다.
코드 리뷰 부탁드립니다 🙇🏼‍♂️
### 구현내용

- [x]  파싱한 `JSON` 데이터와 매핑할 모델 설계
- [x]  `CodingKeys` 프로토콜의 활용
- [x]  `API` 서버와 통신할 인스턴스 역할을 수행할 타입 구현
- [x]  범용성과 재사용성, 유연성을 고려한 네트워킹 타입 구현
- [x]  라이브러리 없이 `URLSession`을 활용하여 구현
- [x]  날씨 정보 `위도`/ `경도` 사용하기
- [x]  날씨 정보 받아오는 포멧 `JSON` 사용하기

## 스크린샷

- **불러오기 전**
![Simulator_Screenshot_-_iPhone_15_Pro_-_2023-11-22_at_17 22 02](https://github.com/tasty-code/ios-weather-forecast/assets/22284092/7b952939-2808-429d-82ea-44424d39da89)

- ********************불러온 후********************
![image](https://media.discordapp.net/attachments/1175971201479364639/1176800500948152411/Simulator_Screenshot_-_iPhone_15_Pro_-_2023-11-22_at_17.22.04.png?ex=65702fdf&is=655dbadf&hm=ec5ddec23d013bbc50822c75abe8643603537b064ba3856134e83d57f3172ee2&=&format=webp&width=432&height=936)

## 궁금한점

- 현업에서는 API키 값같은 중요한 정보들은 암호화를 해서 올리는지 아니면 아예 파일을 배제하고 올리지 않는지 궁금합니다.

2023-11-23 16:18 UTC, forestjae commented
고생 많으셨습니다! 남은 스텝도 파이팅입니다.

> 현업에서는 API키 값같은 중요한 정보들은 암호화를 해서 올리는지 아니면 아예 파일을 배제하고 올리지 않는지 궁금합니다.

현업에서는 계정 인증 정보를 기반으로 API 값을 서버에서 받아오는 방식을 많이 사용합니다. 개인적으로 프로젝트를 할때는 파일을 올리지 않는 방식을 많이 썼던 것 같아요.

2023-11-23 16:18 UTC, forestjae requested changes

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Extensions/HTTPClient.swift
> +                return (data, httpResponse)
guard 문이 실패하면 badSeverResponse라고 간주할 수 있나요? 

그리고 일반적으로 아래와 같은 형태로 쓰니 참고 바랍니다 ㅎㅎㅎ
```swift
guard condition else { return }
guard condition else { 
   return
}
```

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Extensions/HTTPClient.swift
> +    func publisher(request: URLRequest) -> AnyPublisher<(Data, HTTPURLResponse), Error>
AnyPublisher를 사용하신 이유가 궁금해요

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +    let system: Self.System
Self를 명시 해 주신 이유가 궁금해요

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Models/WeatherBases.swift
> +struct MainInfo: Decodable {
응답 모델 구조가 많이 복잡한데 잘 만들어 주셨네요 👍

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Models/WeatherBases.swift
> +}
이런 타입들을 파일 구분을 안하시고 전부 모아두신 이유가 있을까요?

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/WeatherClient.swift
> +            }
페이탈 에러를 발생시키는 건 너무 가혹한 것 같아요

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Networks/WeatherHTTPClient.swift
> +    static func publishForecast<T: Decodable>(from publisher: AnyPublisher<(Data, HTTPURLResponse), Error>, forecastType: T.Type) -> AnyPublisher<T, Error>  {
타입 메서드로 만드신 이유가 궁금합니다.

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Networks/WeatherURLManager.swift
> +        baseURL?.path = "/data/2.5/" + api.rawValue
path 랑 baseurl은 프로퍼티로 저장해 두는게 어떨까요?

2023-11-23 16:18 UTC, forestjae commented on WeatherForecast/WeatherForecast/Utils/Errors.swift
> +            return .other4XXError(statusCode: statusCode)
위에 케이스랑 구간이 겹치네요

2023-11-24 01:13 UTC, newJunsung commented on WeatherForecast/WeatherForecast/Networks/WeatherHTTPClient.swift
> +                    throw StatusCodeError.httpError(httpResponse.statusCode)
fatalError를 발생시키지 않고 새로 StatusCodeError 열거형을 정의해서 해당 Error를 던지게끔 수정했습니다.

2023-11-24 01:17 UTC, newJunsung commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +    let system: Self.System
`Forecast` 모델 안에서도 `System` 구조체가 내부에 존재하는데,
`Self`를 명시해주지 않는다면, 다른 사람이 봤을 때 헷갈릴 수도 있을 것 같아서
`Self`를 명시해줬습니다.

(물론 `Forecast` 내부의 `System`을 이용하려면 `Forecast.System`이라고 명시적으로 적어야 된다는 점은 알고 있습니다.)

2023-11-24 01:22 UTC, newJunsung commented on WeatherForecast/WeatherForecast/Networks/WeatherHTTPClient.swift
> +    static func publishForecast<T: Decodable>(from publisher: AnyPublisher<(Data, HTTPURLResponse), Error>, forecastType: T.Type) -> AnyPublisher<T, Error>  {
현재 기준으로, WeatherHTTPClient 내부에는 프로퍼티가 없어서 생성자를 굳이 만들어야 할 필요성을 못 느꼈습니다.
그렇다고 publishForecast를 다른 구조체 등에 포함하기에는, 다른 구조체들이 가진 기능들과 별개의 기능이라고 느꼈습니다.

따라서 별개의 기능을 구조체에 담되, 생성자를 많들지 않고 그 함수를 쓸 수 있는 방법이 타입 메서드이기에 타입 메서드로 만들었습니다.

2023-11-24 01:33 UTC, newJunsung commented on WeatherForecast/WeatherForecast/Extensions/HTTPClient.swift
> +    func publisher(request: URLRequest) -> AnyPublisher<(Data, HTTPURLResponse), Error>
`Publisher`에 `tryMap()`, `receive()` 등을 사용하고 반환되는 타입은 이전 `Publisher`의 타입을 중첩한 채로 반환을 합니다.
그렇기 때문에, `publisher`의 기능이 같음에도 불구하고, `tryMap`과 `receive` 등 함수의 호출 순서에 따라 반환타입도 바뀔 수 있습니다.

`protocol`의 `publisher(request: URLRequest)`의 구현 방식에 따라 반환타입이 달라질 수도 있기 때문에,
`.eraseToAnyPublisher()`를 이용하여 `AnyPublisher<(Data, HTTPURLResponse), Error>`로 반환하여
내부 구현 방식에 자율성을 주고자 `AnyPublisher<(Data, HTTPURLResponse), Error>`로 반환하게 했습니다.

2023-11-24 01:36 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Networks/WeatherURLManager.swift
> +        baseURL?.path = "/data/2.5/" + api.rawValue
네, `baseURL` , `makeURL` 프로퍼티를 만들었습니다.

2023-11-24 01:41 UTC, newJunsung commented on WeatherForecast/WeatherForecast/Models/WeatherBases.swift
> +}
WeatherBases의 내부 타입들은 현재 날씨와 5일 날씨 예보 모두에 사용되는 타입들입니다.
각각의 타입들을 분리하기엔 추가되는 파일이 너무 많아지기 때문에, 공통으로 사용되는 타입들은
한 파일 안에 모아두었습니다.

2023-11-24 01:49 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Utils/Errors.swift
> +            return .other4XXError(statusCode: statusCode)
겹치는 구간을 따로 분리하였습니다.

2023-11-24 03:36 UTC, merged