날씨 앱 [STEP1] Mango, 쫑
tasty-code/ios-weather-forecast pull request #25
Opened 2023-11-22 09:53 UTC by shlim0

# 날씨 앱

## 리뷰어
@jungseungyeo

## 팀원:busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/Dongjun-developer"><img src="https://avatars.githubusercontent.com/u/97822621?v=4" width="90" height="90"></a> | <a href="https://github.com/shlim0"><img src="https://avatars.githubusercontent.com/u/46235301?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@DongJun](https://github.com/Dongjun-developer) | [@JJong](https://github.com/shlim0) 
| in SeSAC | 망고 | 쫑

## 파일구조:file_folder:
```
WeatherForecast
├── Enums
│   └── WeatherType.swift
├── Errors
│   ├── APIError.swift
│   └── NetworkError.swift
├── Info.plist
├── Models
│   ├── CurrentWeatherDTO.swift
│   └── FiveDaysWeatherDTO.swift
├── Protocols
│   ├── DataTransferable.swift
│   └── Networkable.swift
├── Utilities
│   └── NetworkManager.swift
└── ViewController.swift
```

### 프로젝트 설명
1. `ViewController`에서 특정 `WeatherType`에 따라(의존성 주입) `NetworkManager` 인스턴스를 다루게 했습니다.

2. `NetworkManager` 내에서 `Result`을 사용해 completion handler를 정의했습니다. 
`Result`를 사용한 이유는 오류를 더 편리하게 다루기 위해 사용했습니다.

3. `weatherType.check()`을 통해 `CurrentWeatherDTO` `FiveDaysWeatherDTO`를 구분합니다. 해당 DTO들이 `DataTransferable`를 채택하게 하여 현재 날씨인지, 5일 예보인지를 `DataTransferable.Type`으로 return 합니다. 이후 Return 받은 DTO를 토대로 `NetworkManager`에서 JSON decoding 합니다.

### 궁금한점 / 고민하는 점
1. `CurrentWeatherDTO`와 `FiveDaysWeatherDTO`로 현재 날씨에 대한 모델과 5일 예보에 대한 모델을 만들었습니다.
날씨에 대한 정보를 담으려는 목적이 같기 때문에, 특정 프로퍼티는 중복되는 경우가 있는데요. 물론, 공통되는 프로퍼티만 따로 분리하여 관리할 수 있으나, `Open Weather Map API`에 의존적이기 때문에 최대한 API 형태에 맞게 두었습니다. 이에 대한 린생의 생각은 어떠신가요?

2. 현재 `ViewController`에서`weatherManager.fetch()` 호출하는데요. `ViewController`에서 해당 함수를 호출하는 것보다 내부에서 처리해주는게 좋을 것 같다고 생각합니다. `WeatherManager`에서 해당 함수를 정의해주기 때문에 `WeatherManager`가 아닌 다른 곳에서 처리를 해주어야 할 것 같습니다. 따로 파일을 만들어 처리를 해주는 것이 좋을까요?

2023-11-22 14:04 UTC, jungseungyeo requested changes
질문

1. CurrentWeatherDTO와 FiveDaysWeatherDTO로 현재 날씨에 대한 모델과 5일 예보에 대한 모델을 만들었습니다.
날씨에 대한 정보를 담으려는 목적이 같기 때문에, 특정 프로퍼티는 중복되는 경우가 있는데요. 물론, 공통되는 프로퍼티만 따로 분리하여 관리할 수 있으나, Open Weather Map API에 의존적이기 때문에 최대한 API 형태에 맞게 두었습니다. 이에 대한 린생의 생각은 어떠신가요?

`코멘트에 달아두긴 하였는데요. 저는 이러한 형태를 좋아하지는 않습니다. 첫번째는 DTO의 기능이 아닌거 같은데 DTO라는 네이밍이 작성되어 혼선이 있는거같습니다. 특정 모델로 변환이 되거나 전환을 하기 위한 역할로 DTO를 사용하는데요 지금 같은 경우는 순수하게 데이터를 저장하는 객체로 사용이 되는 거같습니다. 따라서 struct Model를 extention하여 사용하면 좋을거같습니다.`

2. 현재 ViewController에서weatherManager.fetch() 호출하는데요. ViewController에서 해당 함수를 호출하는 것보다 내부에서 처리해주는게 좋을 것 같다고 생각합니다. WeatherManager에서 해당 함수를 정의해주기 때문에 WeatherManager가 아닌 다른 곳에서 처리를 해주어야 할 것 같습니다. 따로 파일을 만들어 처리를 해주는 것이 좋을까요?

`흠.. 질문의 의도를 잘 파악하지는 못했는데요. ViewController에서 URLSession으로 호출하느거 보다 Networker 객체를 만들어서 사용하는게 좋을거같다는 말로 이해했습니다. 이 질문이 맞다면 저도 Networker 객체를 만들어서 거기서 요청을 하여 받아오는 방법으로 구현을 할 거같습니다. ㅎㅎ 좋은 방법인거같습니다. 그래도 networker의 내부를 코멘트에서 남긴거처럼 수정이 좀 필요해보입니다.`

3. JSON Decoding 중에 decoding을 하는 경우, 못 하는 경우가 번갈아 발생합니다. (The given data was not valid JSON.) 문제는 코드의 변화가 없으며, 해당 URL을 크롬 웹브라우저에서 직접 접근하는 데는 문제가 없는데요. 이러한 현상이 Xcode 문제인지 아니면 다른 문제인지 궁금합니다. -> [19:14 추가] DTO 파일에서 특정 프로퍼티를 옵셔널 처리하는 것으로 해결했습니다.

`이런 경우가 많이 존재하여 저는 모든 값을 옵셔널 처리를 하여 사용을 합니다. 서버가 내려줄거라고 보장을 한다고 하지만 실제로 안내려주는 경우도 실제 많이 경험을 하였고, 중복해서 내려주는 경우이 있어 저는 Decoding을 하는 경우 noneOptional하게 작성하지 않고 모두 optional하게 작성하여 처리를 하는 편입니다.`

코멘트에 전달 드린거처럼 DTO의 역할과, Networker의 기능을 수정을 부탁드립니다.
특히 Networker의 같은 경우 직접 함수 내부에서 URLSession을 사용하지 말고 의존성 주입을 통해서 주입을 받으면 좋은거 같아요 ㅎㅎ

2023-11-22 14:04 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Models/CurrentWeatherDTO.swift
> +struct CurrentWeatherDTO: Decodable {
네이밍을 DTO라고 하였는데 DTO가 무슨 역할인지 설명 가능한가요? DTO의 역할이 아닌거같아서요.

2023-11-22 14:04 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Models/CurrentWeatherDTO.swift
> +extension CurrentWeatherDTO {
개인적으로 Model의 역할로 인식이 되는데요 
Model 인스턴스를 생성하고 거기서 extension으로 구현하는 형태는 어떤가요? 

예를 들어 

``` swift
struct Model {}
```

``` swift
extension Model {
   strcut CurrentWeather: Decodable {
    ....
   }
}
```

위와 같이 작업이 된다면 외부에서 접근할때 `Model.CurrentWeather` 로 되어 Model인지 명확히 구분이 되어서 기능을 담당하는 객체인지 모델인지 휴먼에러가 적을거같아요.

2023-11-22 14:04 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Models/CurrentWeatherDTO.swift
> +extension CurrentWeatherDTO: DataTransferable {
DataTransferable 이 프로토콜의 역할이 크게 없는거 같은데.. 어떤 의도인가요?

2023-11-22 14:04 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Protocols/Networkable.swift
> +    var apiKey: String {
이건 별도의 protocol로 구현하면 좋을거같네요. 또 이 부분은 private하게 사용하면 좋을거같아요.

2023-11-22 14:04 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +        URLSession.shared.dataTask(with: url) { data, response, error in
URLSession.shared로 직접 접근하여 사용하면 URLSession.shared의 디펜던시가 생길거같아요. 의존성 주입을 통해 주입받아서 사용하여 fetch함수가 테스트가 가능한 구조로 설계가 되면 좋을거같아요.

2023-11-22 14:04 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +final class NetworkManager<T: DataTransferable>: Networkable {
DataTransferable -> Decodable가 되어도 문제가 없을거같은데. DataTransferable프로토콜이 되어야 하는 이유가 있을까요?

2023-11-22 14:04 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +            }
data, response, error의 값중 data만 상용하고 있는거같아요.

reponse의 status와 error코드를 같이 넘겨주는 코드가 작성되면 좋을거같아요. 모델이 맵핑이 되는 것으로 성공여부를 판단하기 보다는 status값과 error로 구분하면 좋을거같아요.

명확하게 
- 서버 통신이 안된 경우 
- 서버 통신이 되었지만 모델이 맴핑이 안된경우
- 서버에서 내려주는 에러 코드를 확인하여 전달 하는 코드
이렇게  3가지 정도가 구현이 더 필요해보여요

2023-11-23 01:15 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Models/CurrentWeatherDTO.swift
> +struct CurrentWeatherDTO: Decodable {
json을 받고, 비즈니스 로직이 없어 DTO라고 생각했습니다. 근데, data transfer object라는 이름을 생각해보니 client -> server, server -> client로 data를 전송할 때 사용되는 개념이지, client가 받은 data를 저장하는 의미로는 적합하지 않았던 것 같습니다. `-DTO` 접미사를 삭제했습니다.

2023-11-23 04:21 UTC, Dongjun-developer commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +            }
`response`와 `error`에 대해서도 예외발생 시에 `failure` 처리를 해주도록 반영했어요.

2023-11-23 04:33 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +final class NetworkManager<T: DataTransferable>: Networkable {
url을 만들 때, Model들이 `DataTransferable`을 채택하게 하여 

`url = try URL(string: "https://api.openweathermap.org/data/2.5/\(T.name)?lat=37.715122&lon=126.734086&appid=\(apiKey)"` 

에서 `T.name`으로 Model에 따라 "weather" or "forecast"으로 구분하여 url을 받아오도록 하려는 의도로 만들었습니다.

DataTransferable -> Decodable로 변경했습니다!

2023-11-23 04:34 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Models/CurrentWeatherDTO.swift
> +extension CurrentWeatherDTO: DataTransferable {
https://github.com/tasty-code/ios-weather-forecast/pull/25#discussion_r1402907543를 참고해주세요!

2023-11-23 04:41 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Models/CurrentWeatherDTO.swift
> +extension CurrentWeatherDTO {
해당 구조로 변경했습니다. 또, 각각의 `extension` 파일로 분리했습니다.

2023-11-23 12:01 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Protocols/Networkable.swift
> +    var apiKey: String {
`KeyAuthenticatable` 프로토콜을 만들어 다음과 같이 작성했습니다.

```
extension KeyAuthenticatable {
    private func checkAPIKey() -> Result<String, APIError> {
        guard let filePath = Bundle.main.path(forResource: "APIKeyList", ofType: "plist") else {
            return .failure(.noExistedAPIPlist)
        }
        
        if let plist = NSDictionary(contentsOfFile: filePath),
           let value = plist.object(forKey: "OPENWEATHERMAP_KEY") as? String {
            return .success(value)
        } else {
            return .failure(.noExistedAPIKey)
        }
    }
    
    var APIKey: String? {
        switch checkAPIKey() {
        case .success(let APIKey):
            return APIKey
        case .failure(let error):
            print(error)
            return nil
        }
    }
}
```

또한, 기존에 `NetworkManager`에서 `APIKey`를 사용했으나, 새로 추가된 `Network` 에서 사용하도록 했습니다.
```swift
extension Networker: KeyAuthenticatable {
    private func makeURL() -> URL? {
        guard let APIKey = APIKey else {
            return nil
        }
        
        guard let weatherType = T.weatherType else {
            return nil
        }
        
        let url = URL(string: "https://api.openweathermap.org/data/2.5/\(weatherType)?lat=37.715122&lon=126.734086&appid=\(APIKey)")
        return url
    }
}
```

2023-11-23 12:09 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +        URLSession.shared.dataTask(with: url) { data, response, error in
새로 생성한 `Networker`에서 `url`과 `session`을 주입하는 방식으로 변경했습니다.
다만, session은 여러 개 생길 필요가 없기 때문에(Apple 공식 문서에서 session이 종료되기 전까지 메모리를 점유하기 때문에 하나의 session으로 사용하도록 shared를 제공하는 것으로 알고 있습니다) `URLsession.shared`를 기본값으로 주고 session에 대한 의존성를 주입시 `Networker`에서 `func makeSession()` 같은 커스텀 함수를 만들어 session을 주입하도록 만들었습니다.

```swift
// ViewController.swift
let networker = Networker<Model.CurrentWeather>()
        networker.fetchWeatherData()
```

```swift
// Networker.swift
 private var networkManager: NetworkManager<T>?

    func fetchWeatherData() {
        let url = makeURL()
        
        networkManager = NetworkManager<T>(url: url)
```

```swift
// NetworkManager.swift
final class NetworkManager<T: Decodable>: Networkable {
    private let url: URL?
    private let session: URLSession
    
    init(url: URL?, session: URLSession = URLSession.shared) {
        self.url = url
        self.session = session
    }
```

2023-11-24 04:39 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +        URLSession.shared.dataTask(with: url) { data, response, error in
어제 화상 미팅으로 설명해주신 부분을 반영하였습니다.

단, mock 파일을 만드는 것은 현재 수준에서 시간이 걸릴 것 같아 반영하지 않았습니다.

```
//RequestSessionable.swift
import Foundation
protocol RequestSessionable {
    func dataTask(with url: URL, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask
}

// 기존 URLSession은 dataTask()가 구현되어 있기 때문에 수정이 필요 없음
// 단, MockURLSession을 만들어 테스트하는 경우 dataTask()를 구현해야 하며 원하는 방향으로 테스트 하도록 할 수 있음
extension URLSession: RequestSessionable {
    
}
```
```
// NetworkManager.swift
final class NetworkManager<T: Decodable>: Networkable {
    // request를 프로토콜로 추상화하여 일일 날씨, 5일치 날씨를 받을 수 있도록 함
    private let request: Requestable?
    // URLSession, MockURLSession을 받을 수 있도록 프로토콜로 추상화 함
    private let session: RequestSessionable
    
    init(request: Requestable?, session: RequestSessionable = URLSession.shared) {
        self.request = request
        self.session = session
    }
    
    func fetch(completion: @escaping (Result<T, NetworkError>) -> Void) {
        guard let path = self.request?.path else {
            return
        }
        
        guard let url = URL(string: path) else {
            return completion(.failure(.urlError(request)))
        }
   ...
```

2023-11-24 04:41 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Protocols/Networkable.swift
> +    var apiKey: String {
기존 `extension Networker: KeyAuthenticatable`를 삭제하고 다음과 같이 변경하였습니다.

```swift
 func fetchWeatherData() {
        networkManager = NetworkManager<T>(request: WeatherAPI.current)
        ...
```

2023-11-24 10:42 UTC, jungseungyeo approved these changes
망고, 쫑 고생하셨습니다.

step1에서 많은 수정이 있었는데요 그만큼 중요한 부분이라 수정을 요청했는데 잘 적용 된거같습니다.
고생하셨습니다. 다음 스텝 진행 부탁드립니다.

2023-11-24 10:42 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Model+Extension.swift
> +extension Model {
Model을 확장해서 사용했군요 ㅎㅎ 좋습니다

2023-11-24 10:42 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Models/Model.swift
> +struct Model {
너무 좋습니다.

2023-11-24 10:42 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Protocols/Networkable.swift
> +protocol Networkable {
Networkable를 사용했군요 ㅎㅎ 잘 적용하셨습니다.

2023-11-24 10:42 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Protocols/RequestSessionable.swift
> +extension URLSession: RequestSessionable {
의존성을 주는 부분을 해보니 어떤가요? 생각보다 어렵지 않죠?

2023-11-24 10:42 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/Enums/WeatherAPI.swift
> +extension WeatherAPI: Requestable, KeyAuthenticatable {
의종성주입을 해주었네요 또 POP구조를 선택했군요 ㅎㅎ 좋습니다.

2023-11-24 10:42 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/NetworkManager.swift
> +        URLSession.shared.dataTask(with: url) { data, response, error in
좋습니다

2023-11-24 10:42 UTC, merged