날씨 앱 [STEP 1] 도라, 밤삭
tasty-code/ios-weather-forecast pull request #28
Opened 2023-11-23 06:52 UTC by bamsak

# 날씨 앱

## 리뷰어
@zdodev

## 팀원:busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/bamsak"><img src="https://avatars.githubusercontent.com/u/114239407?v=4" width="90" height="90"></a> | <a href="https://github.com/KSK9820"><img src="https://avatars.githubusercontent.com/u/68066104?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@bamsak](https://github.com/bamsak) | [@KSK9820](https://github.com/KSK9820) 
| in SeSAC | 밤삭 | 도라

<br/>

## 프로젝트 파일 구조
```
├── Extension
│   └── Bundle+Extension.swift
├── Model
│   ├── CurrentWeather.swift
│   ├── NetworkError.swift
│   ├── WeatherURL.swift
│   └── WeeklyWeather.swift
├── Protocol
│   ├── URLFormattable.swift
│   └── URLProtocol.swift
├── Utility
│   ├── NetworkManager.swift
│   └── WeatherURLFormatter.swift
└── ViewController.swift
```
<br/>

## 프로젝트 설명
### 구현 내용

- [x]  파싱한 `JSON` 데이터와 매핑할 모델 설계
    - 현재 날씨 DTO CurrentWeather
    - 주간 날씨 DTO WeeklyWeather
- [x]  `CodingKeys` 프로토콜 활용
- [x]  `API` 서버와 통신할 인스턴스 역할을 수행할 타입 구현
    - NetworkManager 
- [x]  범용성과 재사용성, 유연성을 고려한 네트워킹 타입 구현vmfh
- [x]  라이브러리 없이 `URLSession`을 활용하여 구현
---
### 각 역할 설명
#### Protocol
- **URLProtocol**
    - 해당 프로토콜을 채택하는 타입이 `static 타입 프로퍼티`로 `url`을 변환하기 위한 `String` 타입을 `타입 프로퍼티`로 가지고 있게 정의한 프로토콜 입니다.
- **URLFormattable**
    - `URLFormattable`을 채택하는 타입이 `URLProtocol`을 따르는 타입을 `Generic`으로 받아(타입 제한) `URLProtocol`의 `static 타입 프로퍼티`의 값을 가지고 `URL타입으로 변환 시켜주는 역할`을 하게 해주는 프로토콜 입니다.
    - `associatedtype`을 사용하여 해당 프로토콜을 채택한 객체의 `Generic`으로 `URLProtocol`의 타입을 받아 의존을 객체간 직접 의존이 아닌 Protocol에 의존성을 갖게 했습니다.

---
#### Model
- **NetworkManager**
    - `URLFormatable` 프로토콜을 따르는 객체 와 URLSession을 내부 프로퍼티로 갖고 초기화 시점에 의존성 주입을 통해 초기화 하도록 하였습니다.
    
    ```swift
    let networkManager = NetworkManager(urlFormatter: WeatherURLFormatter<WeatherURL>())
    ```
    - 위의 방식처럼 초기화 시점에 `urlFormatter`를 주입해주어 `URLProtocol`과 `URLFormattable`을 채택한 타입에 따라 생성되는 URL에 네트워크 통신이 가능하도록 하였습니다.
    - `NetworkManager` 객체를 통해 `API`와 `URLSession`으로 통신할 수 있습니다.
---
#### Extension
- **Bundle**
    - `xcconfig` 파일을 통해 `API KEY`를 숨기고 `info.plist`를 통해 `xcconfig` 파일에서 정의한 `API KEY`값에 접근해서 사용할 수 있게 했습니다.

<br/>

## Trouble Shooting
### URLFormattable, URLFormatter, URLProtocol

<details>
    <summary>첫번째 구현 방식</summary>
<div markdown="1">
    
```swift=
struct URLFormatter: URLFormattable {
    typealias T = WeatherURL

    func makeURL(urlType: T, with queryDict: [String: String]) -> URL? {
        let urlString = "\(urlType)"
        var urlComponents = URLComponents(string: urlString)
        let queryItems = queryDict.map {
            URLQueryItem(name: $0.key, value: $0.value)
        }
        urlComponents?.queryItems = queryItems
        return urlComponents?.url
    }
}
let urlFormatter: any URLFormattable = URLFormatter<WeatherURL>()
urlFormatter.makeURL(urlType: .current // 이 부분에서 타입 제약을 주라는 컴파일러의 오류 메세지가 나옴
```
이렇게 하다보니 WeatherURL에만 국한된 프로토콜로 사용할 수 밖에 없었고.
URLFormattable 프로토콜 타입으로 객체 생성 후, makeURL을 호출했을 시,
파라미터의 urlType을 객체 초기화 시 `any URLFormattable` 타입으로 만들어지기 때문에 컴파일러가 추론할 수 없는 문제 발생하였습니다.

</div>
</details>

<details>
    <summary>두번째 구현 방식</summary>
<div markdown="1">
    
```swift=
protocol URLFormattable {
		func makeURL(path: String, with queries: [String: String]) -> URL?
}

//컴파일러가 인식을 못 하니까 타입을 제네릭으로 줌
struct URLFormatter<T: URLProtocol>: URLFormattable {
    func makeURL(path: String, with queries: [String: String]) -> URL? {
        let urlString = "\(T.url)"	
	var urlComponents = URLComponents(string: urlString)
	urlComponents?.path = "\(path)"
	let queryItems = queries.map {
	      URLQueryItem(name: $0.key, value: $0.value)
	}
	urlComponents?.queryItems = queryItems
	return urlComponents?.url
   }
}

struct WeatherURLFormatter: URLFormattable {
    private let defaultPath: String
    private let formatter: URLFormattable

    init(defaultPath: String = "/data/2.5/",
         formatter: URLFormattable = URLFormatter<WeatherURL>()) {
        self.defaultPath = defaultPath
        self.formatter = formatter
    }

    func makeURL(path: String, with queries: [String : String]) -> URL? {
        let weatherAPIPath = defaultPath + "\(path)"
        return formatter.makeURL(path: weatherAPIPath, with: queries)
    }
}
```
WeatherURLFormatter객체 내부에  프로퍼티로 URLFormatter객체를 생성하여 만드는 방식으로 변경

</div>
</details>

<details>
    <summary>최종 구현 방식</summary>
<div markdown="1">
    
```swift=
protocol URLFormattable {
     associatedtype T: URLProtocol

     var defaultPath: String {get}

     func makeURL(path: String, with queries: [String: String]) -> URL?
 }

extension URLFormattable {
     func makeURL(path: String, with queries: [String: String]) -> URL? {
         let urlString = "\(T.url)"
         var urlComponents = URLComponents(string: urlString)
         urlComponents?.path = "\(defaultPath)\(path)"
         let queryItems = queries.map {
             URLQueryItem(name: $0.key, value: $0.value)
         }
         urlComponents?.queryItems = queryItems
         return urlComponents?.url
     }
 }

struct WeatherURLFormatter<T: URLProtocol>: URLFormattable {
    
    var defaultPath: String
    
    init(defaultPath: String = "/data/2.5/") {
        self.defaultPath = defaultPath
    }
    
}
```

</div>
</details>
    
<br/>
    
## 궁금한 점
- 이번 프로젝트가 API 통신인 만큼 `Network Test` 코드를 작성해 보고싶었습니다.
 그리하여 `NetworkManager`를 채택하는 `Protocol`을 만들고, `URLSession`을 상속받는 `MockURLSession`과 `URLSessionDataTask`를 상속받는 `MockURLSessionDataTask`를 만들어 테스트 코드를 작성해보려고 했는데, 두 클래스의 `init()` 생성자가 iOS 13버전 이후로 deprecated 되었다는 컴파일러의 에러를 확인하였습니다.
    다른 방법을 확인해본 결과 `URLSession`관련 `Protocol`과 `URLSessionDataTask`관련 `Protocol`을 만들어 각각 해당 프로토콜을 따르게 한후, 각각의 Mock을 만들어서 `UnitTest`를 작성하는 방법을 찾았는데, `UnitTest`만을 위하여 해당 프로토콜을 만드는 것이 적당한 방법인지 아직 판단이 서질 않습니다.
- 또한 다른 `NetworkManager`가 만들어지지 않을 것 같은 판단이 드는데, 이러한 경우에도 `NetworkManager`가 채택할 `Protocol`을 구현하여 `NetworkManager`가 해당 `Protocol`을 따르게 한 후, 의존 관계를 역전 시켜주는 것이 좋은 지 고민이 됩니다.

2023-11-23 16:12 UTC, zdodev requested changes
안녕하세요. @bamsak , @KSK9820 !

날씨 앱 Step1 잘 진행해보셨네요!

모델 타입을 꼼꼼하게 구현하시고, 
apikey 보안에 대해서 생각해보신 점이 좋았습니다.👍

먼저 질문에 대한 제 생각을 적어보았습니다.

 1. 정답은 없는 것 같습니다. 개인의 생각에 따라 꼭 필요한 프로토콜이 될 수도 있고, 불필요할 수도 있지 않을까 싶습니다.
 다만, 네트워크에 의존하지 않는 테스트 코드를 작성하기 위해 프로토콜 정의가 필요하다면 불필요한 작업이 아니라고 생각합니다!
 오히려 외부 의존성이 필요한 기능(네트워크, DB, 라이브러리 등)에 직접 의존하지 않고 테스트 할 수 있는 방법을 연구하는 것도 좋을 것 같습니다!
 
 2. protocol을 사용하여 의존 관계를 역전할 필요는 없다고 생각합니다. 과도한 추상화는 프로그램 복잡도가 증가하고 가독성이 떨어질 수 있어 무조건적으로 사용하는 것은 지양하는 편입니다!

이외에도 여러 궁금증과 코멘트를 남겨보았습니다.
같이 의견 나눠보면 좋을 것 같습니다.😁

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Protocol/URLFormattable.swift
> +    associatedtype T: URLProtocol
`URLFormattable` 타입이 연관값으로 `URLProtocol` 을 가지게 하였을 때, 어떤 이점이 있을까요?
`url`과 `defaultPath`을 별개로 생각하고 서로 각각 재사용하기 위함인지 궁금합니다!

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Protocol/URLFormattable.swift
> +    var defaultPath: String {get}
다른 프로토콜과 컨벤션을 맞춰보는 것은 어떨까요?

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Protocol/URLProtocol.swift
> +}
`Swift`에서 제공하는 `URLProtocol` 타입과 이름을 동일하게 지정한 이유가 있을까요?
호스트 주소 `url`까지 추상화한 이유를 알 수 있을까요?

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/NetworkManager.swift
> +    func getData<T: Decodable>(path: String, with queries: [String: String], completion: @escaping (Result<T, Error>) -> Void) {
`URLSession`을 이용하여 네트워크 요청 구문(generic, jsondecoder)을 잘 작성해보셨네요.👍

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/NetworkManager.swift
> +            guard let response = response as? HTTPURLResponse else {return}
다른 `guard` 문에서 작성한 공백 컨벤션을 맞춰보는 것은 어떨까요?

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Extension/Bundle+Extension.swift
> +    }
`apikey` 유무에 따라서 apikey를 반환하거나 공백 문자열을 반환하도록 구현해보셨네요.
공백 문자열을 반환하도록 구현하신 이유가 궁금합니다!
공백 문자열을 반환하는 경우에는 앱(UI)에서 어떤 처리를 기대할 수 있을까요?

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +struct CurrentWeather: Decodable {
API의 모든 파라미터에 대한 모델을 구현해보셨네요.👍

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +    var cod: Int?
모든 프로퍼티를 옵셔널로 처리하신 이유가 궁금합니다.

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +    var lat: Double
API 문서에서 제공하는 단축어를 그대로 사용하기 보다는 전체 단어로 프로퍼티 이름을 지정해보는 것은 어떨까요?
의견이 궁금합니다!

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/WeeklyWeather.swift
> +struct WeeklyWeather: Decodable {
API의 모든 파라미터에 대한 모델을 구현해보셨네요.👍

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/NetworkError.swift
> +enum NetworkError: Error, CustomStringConvertible {
네트워크 에러 타입을 구현해보셨네요.👍

2023-11-23 16:12 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +}
모든 모델에 대한 타입이 전역적으로 선언되어 있네요. 
`Swift Nested Types`에 대해서 한번 알아보고 개선해봐도 좋을 것 같습니다.
지금도 좋습니다!

2023-11-24 00:59 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Protocol/URLFormattable.swift
> +    var defaultPath: String {get}
공백 수정하였습니다!

2023-11-24 01:00 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Utility/NetworkManager.swift
> +            guard let response = response as? HTTPURLResponse else {return}
공백 수정하였습니다~!

2023-11-24 03:55 UTC, bamsak commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +}
WeeklyWeather, CurrentWeather 각각 따로 사용하는 모델은 Nested Type으로 변경하고,
공통으로 사용하는 모델은 NameSpace로 분리하도록 변경 했습니다!

2023-11-24 05:14 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +    var lat: Double
해당 부분 수정했습니다. 
이 외의 단축어도 함께 수정하였습니다.

2023-11-24 05:23 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +    var cod: Int?
STEP1 진행 중이라 어떤 값들이 nil 값으로 들어올지 몰라 모든 프로퍼티를 옵셔널로 처리해두었습니다. 프로젝트 진행하며 확실한 값들은 옵셔널 처리를 하지 않는 방향으로 수정하겠습니다!

2023-11-24 05:45 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Protocol/URLFormattable.swift
> +    associatedtype T: URLProtocol
프로토콜에서 연관값으로 URLProtocol을 가지게하면, 범용으로 사용할 수 있되URLProtocol을 채택한 값만 사용할 수 있도록  제네릭에 타입제한을 둘 수 있는 이점이 있습니다.

2023-11-24 05:48 UTC, bamsak commented on WeatherForecast/WeatherForecast/Extension/Bundle+Extension.swift
> +    }
빈 문자열로 했을 때, 앱에서 UI처리가 따로 없이  Request 보내는 부분 response.statusCode관련해서 에러가 날 것 같은데,
이렇게 되면 개발자가 어떤 부분에서 에러가 잡히는지 잘 모를 것 같다는 판단이 들어
APIKey를 옵셔널 String 타입으로 바꾸고 APIKey를 뽑아서 사용할 때 에러처리 하도록 변경하겠습니다.

2023-11-24 06:26 UTC, bamsak commented on WeatherForecast/WeatherForecast/Protocol/URLFormattable.swift
> +    associatedtype T: URLProtocol
```swift
protocol URLFormattable {
    associatedtype T: APIBaseURLProtocol
    
    func makeURL(path: String, with queries: [String: String]) -> URL?
}

extension URLFormattable {
    func makeURL(path: String, with queries: [String: String]) -> URL? {
        let urlString = "\(T.baseURLString)"
        ......

protocol APIBaseURLProtocol {
    static var baseURLString: String { get }
}

```
```swift
struct WeatherURLFormatter: URLFormattable {
    typealias T = WeatherURL
}

enum WeatherURL: APIBaseURLProtocol {
    static let baseURLString = "https://api.openweathermap.org"
   .....
```
현재는 이렇게 수정했습니다!
`URLFormattable`을 채택하는 타입이 `associatedtype`의 `typealias`로 어떤 타입을 가지고 있게 하냐에 따라 URL을 포맷팅 해주는 역할을 프로토콜로 추상화를 통해 구현해보고 싶었습니다.
또한, 현 프로젝트에서는 하나의 API만 쓰이지만,
조금 더 확장성을 생각하여 어떠한 API에도 URL을 포맷팅해주는 역할을 구현해보고 싶었습니다.
그러기 위해 `generic`을 사용해야 했는데, 프로토콜에서는 `associatedtype`을 통해  해당 프로토콜이 채택하는 타입이 `generic`과 유사하게 활용하는 방법을 택했습니다.
`Protocol extension`을 통해 메소드 기본 구현하는 과정에서 포맷팅할 String 값에 접근하는 방법으로 
`associatedtype`에 `APIBaseURLProtocol`로 제약을 주었습니다.
이 과정에서 `APIBaseURLProtocol`를 따르는 객체는 타입프로퍼티로 해당 API의 `baseURLString`을 가지고 있게하고, `URLFormattable extension`의 `makeURL`메소드가 `baseURLString`값에 접근하여,
URL을 포맷팅해주는 기능을 구현하면 되겠다고 생각했습니다.
defaultPath는 재사용성이 없다고 판단하여 현재는 제거했습니다!

2023-11-26 15:08 UTC, zdodev approved these changes
안녕하세요. 도라, 밤삭!

프로젝트를 더 개선해보셨네요. 좋습니다!👍
궁금증에 대한 의견을 달아주신 점도 좋았습니다!

Step1 진행하시느라 고생하셨습니다.
이번 스텝은 여기서 마무리하도록 하겠습니다.🎉

2023-11-26 15:08 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +    }
프로퍼티 이름을 잘 바꿔보셨네요.👍

2023-11-26 15:08 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/CommonWeatherDTO.swift
> +enum CommonWeatherDTO {
전역적으로 선언된 모델을 모아서 구현해보셨네요.👍

2023-11-26 15:08 UTC, merged