날씨앱 [STEP2] 요한
tasty-code/ios-weather-forecast pull request #30
Opened 2023-11-27 02:48 UTC by dpwns1234

# 날씨 앱 [STEP2] 요한
리뷰어: @coryKim0829

안녕하세요 코리!
STEP2 PR 보냅니다. 잘 부탁드립니다!

## 파일구조📁
- Secrets.xcconfig
- Delegate
    - LocationDelegate
- Util
    - LocationDataManager
- Network
    - WeatherApiClient
    - WeatherNetworkManager
    - NetworkError
- Model
    - WeatherType
    - WeatherToday
    - WeatherForecast
    - WeatherCommonInformation
- Controller
    - WeatherViewController

## 구현내용
- [x] `CoreLocation`을 통해 현재 좌표 가져오기
- [x] `CoreLocation`을 통해 주소 가져오기
- [x] `URLSession`을 통해 API 호출 (HTTP GET 메서드 명시적 호출)
- [x] 전달받은 `JSON` 데이터 파싱 및 모델에 매칭

### Delegate 패턴을 사용하여 LocationDataManager와 WeatherNetworkManager를 통신하도록 구현

```swift 
// LocationDataManagerDelegate.swfit

protocol LocationDataManagerDelegate: AnyObject {
    func location(_ manager: LocationDataManager, didLoad coordinate: CLLocationCoordinate2D)
}
```

```swift
// LocationDataManager.swift 

final class LocationDataManager : NSObject {
    weak var locationDelegate: LocationDataManagerDelegate?
    ...
}
```

```swift 
// WeatherViewController.swift

final class WeatherViewController: UIViewController {
    private let networkManager = WeatherNetworkManager()
    private let locationDataManager = LocationDataManager()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        locationDataManager.locationDelegate = self
    }
}

extension WeatherViewController: LocationDataManagerDelegate {
    func location(_ manager: LocationDataManager, didLoad coordinate: CLLocationCoordinate2D) {
        networkManager.loadWeatherData(type: WeatherType.weatherToday, coord: coordinate)
    }
}
```

## 고민한 점
LocationDataManager의 lookUpCurrentAddress 메서드의 depth가 깊다고 생각되어 함수로 분리하려 하였습니다. 그래서 reverseGeocodeLocation()의 후행클로저를 함수로 분리하려 하였지만, lookUpCurrentAddress()의 인자인 completionHandler를 같이 넘겨줄 수 없어서 현재의 코드를 유지하였습니다.
```swift 
private func lookUpCurrentAddress(completionHandler: @escaping (CLPlacemark?) -> Void ) {
    if let lastLocation = locationManager.location {
        let geocoder = CLGeocoder()

        geocoder.reverseGeocodeLocation(lastLocation) { (placemarks, error) in
            if error == nil {
                guard let placemarks else { return }
                let firstLocation = placemarks[0]
                completionHandler(firstLocation)
            } else {
                completionHandler(nil)
            }
        }
    } else {
        completionHandler(nil)
    }
}
```

2023-11-27 16:24 UTC, corykim0829 requested changes
수고 많으셨습니다!

Manager 객체들로 분리해서 일을 처리하는 것은 좋으나 마무리까지 모두 Manager에서 처리되고 있어서 아쉽습니다!
아직 UI 구현은 아니지만, 그래도 데이터들을 컨트롤러에 전달해서 컨트롤러에서 print로 확인하면 좋을 것 같습니다!

delegate 사용도 잘 하시고, 조금만 더 정리하면 더 가독성 좋고 깔끔한 코드가 될 것 같습니다!

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +            lookUpCurrentAddress(completionHandler: viewCurrentAddress)
lookUpCurrentAddress 함수 인자로 viewCurrentAddress함수를 받는 부분이 조금 어색하네요!

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +                print(address)
데이터를 확인하는 것도 좋지만, 해당 데이터를 컨트롤러에게 어떻게 전달할지도 고민해보면 좋을 것 같습니다!

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +                    guard let placemarks else { return }
return 되는 경우의 예외 처리도 필요해보입니다

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +    private func lookUpCurrentAddress(completionHandler: @escaping (CLPlacemark?) -> Void ) {
이 함수 안에 if let이 많이 사용되는게 보이는데, guard let을 활용하면 조금 더 깔끔하게 정리할 수 있을 것 같아요! 이건 참고만 하세요!

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +            print("location 가져오기 실패")
이 부분도 예외 처리를 어떻게 컨트롤러에 전달할지도 고민해보면 좋을 것 같아요

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +                break
생략 가능한 break는 지워주세요

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +                // disableLocationFeatures()
예외 처리 고민해주시면 좋을 것 같아요!

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +        locationManager.allowsBackgroundLocationUpdates = false
주석도 좋지만, 함수로 분리해서 더 깔끔하게 정리하면 좋을 것 같습니다!

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Network/WeatherApiClient.swift
> +        guard let url = makeURL(coord: coord, weatherType: weatherType) else { throw NetworkError.invailedURL }
guard-else 뒤 대괄호 부분은 다음과 같이 줄바꿈을 해주세요 명확하게 예외 처리가 되는 부분을 줄바꿈으로 처리하면 가독성이 더 좋습니다
```Swift
else {
    ...
    return
}
```

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Network/NetworkError.swift
> +    case invailedURL
invalidURL 외에도 다른 에러 상황은 없을까요?

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Controller/WeatherViewController.swift
> +    func location(_ manager: LocationDataManager, didLoad coordinate: CLLocationCoordinate2D) {
delegate로 데이터 전달 구현을 잘하셨습니다! 👍

2023-11-27 16:24 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Controller/WeatherViewController.swift
> +        networkManager.loadWeatherData(type: WeatherType.weatherToday, coord: coordinate)
networkManager를 통해서 받은 데이터는 어떻게 전달할건지도 고민해보면 좋을 것 같아요

2023-11-28 08:15 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +            lookUpCurrentAddress(completionHandler: viewCurrentAddress)
currentAddress을 찾았을 때(= complete), viewCurrentAddress() 함수를 실행하라는 의미로 위와 같이 작성하였었습니다. 현재는 viewCurrentAddress() 를 ViewController로 이동하긴 했는데, 코리의 의도대로 수정했는지는 잘 모르겠습니다.
혹시 어떤 부분이 어색한지, 어떤 방향으로 수정해야하는지 알 수 있을까요?

2023-11-28 08:16 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +                print(address)
locationDelegate를 사용해서 데이터를 전달하고 address를 출력하는 해당 메서드를 viewController에서 실행하도록 수정하였습니다!

2023-11-29 06:11 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +                    guard let placemarks else { return }
completeHandler에 nil을 전달함으로써 VC에 있는 곳에서 에러처리 해주었습니다!

2023-11-29 06:12 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +            print("location 가져오기 실패")
해당 메서드를 ViewController에 옮기고, delegate로 전달하였습니다!

2023-11-29 07:01 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +                // disableLocationFeatures()
위치 권한을 거부했을 때는, 설정창으로 이동하도록 하여 권한을 허락하는 alert을 띄워주도록 수정하였습니다!

2023-11-29 07:15 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Controller/WeatherViewController.swift
> +        networkManager.loadWeatherData(type: WeatherType.weatherToday, coord: coordinate)
delegate 패턴으로 데이터를 뷰컨에 전달해주도록 수정하였습니다!

2023-11-29 07:53 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Network/NetworkError.swift
> +    case invailedURL
한 가지 궁금한 것이 있습니다! 저는 발생할 수 있는 에러들을 ViewController로 보내어 처리하려고 하였으나 throw를 날리기 어려운 상황이나 여러 어려움으로 한 곳이 아닌 여러 곳에서 do-catch를 해야하는 상황입니다. 
제 생각에는 발생할 수 있는 에러들을 throw 날리고 do-catch 구문을 Controller(ViewController)에서 혹은 한 곳에서 따로 처리를 하는 것이 깔끔하다고 생각하는데, 굳이 신경 쓸 필요 없는 것인지, 코리는 어떻게 생각하는지 궁금합니다!

2023-11-29 07:53 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +        locationManager.allowsBackgroundLocationUpdates = false
감사합니다! 함수로 분리하였습니다.

2023-11-29 14:59 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Util/LocationDataManager.swift
> +            lookUpCurrentAddress(completionHandler: viewCurrentAddress)
이번에 수정하신 lookUpCurrentAddress completion 파라미터를 클로저로 처리하신게 훨씬 깔끔하고 좋습니다!
잘 수정하셨습니다! 👍

2023-11-29 15:07 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Network/NetworkError.swift
> +    case invailedURL
지금 NetworkError가 발생하는 곳은 WeatherNetworkManager 밖에 없는 상황에서, WeatherNetworkManager의 loadWeatherData 함수를 호출할 때 발생할 수 있는 에러 상황에 대한 예외 처리를 loadWeatherData 이 함수 내에서 처리하고 이에 대한 결과값만 ViewController로 넘겨주면 좋을 것 같습니다!
ViewController는 데이터 또는 에러만 받아서 처리해주면 되니까요!

2023-11-29 15:12 UTC, corykim0829 approved these changes
수고 많으셨습니다!!

추가로 남겨드린 커멘트는 다음 스텝 진행하시면서 수정해주세요!!

항상 예외 처리를 고민하시는 습관을 가지시면 좋을 것 같습니다!

고생 많으셨어요!

2023-11-29 15:12 UTC, corykim0829 commented on WeatherForecast/WeatherForecast/Location/LocationDataManagerDelegate.swift
> +    func viewRequestLocationSettingAlert()
delegate를 잘 활용해서 ViewController와 데이터 전달을 잘 하고 계십니다! 👍
조금 아쉬운 점은 delegate의 함수명만 보고 조금 더 기능을 유추할 수 있도록 개선해보면 더 좋은 코드가 될 것 같습니다!

현재 Swift에서 주로 delegate 함수들의 네이밍을 어떻게 하는지 참고해서 수정해보면 더 좋을 것 같습니다!
현재 didLoad~ didComplete~ 만 보면 목적어가 정확하게 나타나지 않아서 가독성이 조금 아쉬운 것 같아요!

2023-11-29 15:12 UTC, merged

2023-11-30 02:29 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Location/LocationDataManagerDelegate.swift
> +    func viewRequestLocationSettingAlert()
didLoadCoordinate, didCompletePlacmark 로 수정하였습니다! 감사합니다 😊

2023-11-30 02:31 UTC, dpwns1234 commented on WeatherForecast/WeatherForecast/Network/NetworkError.swift
> +    case invailedURL
아하 이해했습니다! 에러에 대한 예외 처리는 그 곳에서, 결과 혹은 보여줄 결과(alert 등)는 뷰컨에서 처리하도록 수정하겠습니다!