날씨 앱 [STEP2] comdori, 뉴준성
tasty-code/ios-weather-forecast pull request #31
Opened 2023-11-27 08:26 UTC by comdori-wj

리뷰어: @forestjae

버드: @comdori-wj, @newJunsung

---

안녕하세요. 숲재! 

날씨 앱 STEP2 구현 완료했습니다.
코드 리뷰 부탁드립니다 🙇🏼‍♂️
### 구현내용

- [x] CoreLocation을 통해 현재 좌표 가져오기
- [x] CoreLocation을 통해 주소 가져오기
- [x] URLSession을 통해 API 호출 (HTTP GET 메서드 명시적 호출)
- [x] 전달받은 JSON 데이터 파싱 및 모델에 매칭

## 스크린샷
![Simulator Screenshot - iPhone 15 Pro - 2023-11-27 at 16.57.43](https://hackmd.io/_uploads/BJyz26WBa.png)

## 궁금한점

```swift
    guard let placemark = placemarks?.first, error == nil else {
        return
    }
    print(placemark)
```
```
한강로3가 1-1, 대한민국 서울특별시 용산구 한강로3가 1-1, 04370 @ <+37.53360300,+126.96341600> +/- 100.00m, region CLCircularRegion (identifier:'<+37.53362150,+126.96341860> radius 70.65', center:<+37.53362150,+126.96341860>, radius:70.65m)
```
- 위 코드의 출력 결과에는 용산구가 표시되는데  `CLPlacemark`의 `Getting the placemark details` 프로퍼티를 모두 출력해보아도 용산구는 찾을 수 없습니다. 구글링을 한 결과, 핸드폰 기기 간의 차이가 있다고 하여 여러 시뮬레이터에서 실행해보았지만, 결과는 모두 같았습니다. 용산구를 표시할 방법이 있는지 궁금합니다.
- 참고 : https://developer.apple.com/documentation/corelocation/clplacemark
https://velog.io/@yy0867/부스트캠프-기기별-CLPlacemark의-차이

2023-11-28 04:37 UTC, forestjae requested changes
수고 많으셨습니다 
코멘트 확인 부탁드려요

2023-11-28 04:37 UTC, forestjae commented on WeatherForecast/WeatherForecast/Protocols/WeatherUIDelegate.swift
> +protocol WeatherUIDelegate: UIViewController {
딜리게이트로 구현한 이유가 궁금합니다

2023-11-28 04:37 UTC, forestjae commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +    weak var delegate: WeatherUIDelegate?
weak은 어떤 역할을 하나요?

2023-11-28 04:37 UTC, forestjae commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +        var locationManager = CLLocationManager()
var로 설정하신 이유가 있나요?

2023-11-28 04:37 UTC, forestjae commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +            debugPrint("위도: \(location.coordinate.latitude), 경도: \(location.coordinate.longitude)")
이 메서드는 일반 print와 어떻게 다른가요?

2023-11-28 04:37 UTC, forestjae commented on WeatherForecast/WeatherForecast/ViewController.swift
>              .receive(on: DispatchQueue.main)
receive는 어떤 역할을 하나요?

2023-11-28 04:37 UTC, forestjae commented on WeatherForecast/WeatherForecast/ViewController.swift
>                      self.countryLabel.text = error.localizedDescription
강한 참조가 일어나고 있어요 arc에 대해 배우셨나요?

2023-11-28 04:39 UTC, forestjae commented
> ## 궁금한점
> 
> 
> 
> ```swift
> 
>     guard let placemark = placemarks?.first, error == nil else {
> 
>         return
> 
>     }
> 
>     print(placemark)
> 
> ```
> 
> ```
> 
> 한강로3가 1-1, 대한민국 서울특별시 용산구 한강로3가 1-1, 04370 @ <+37.53360300,+126.96341600> +/- 100.00m, region CLCircularRegion (identifier:'<+37.53362150,+126.96341860> radius 70.65', center:<+37.53362150,+126.96341860>, radius:70.65m)
> 
> ```
> 
> - 위 코드의 출력 결과에는 용산구가 표시되는데  `CLPlacemark`의 `Getting the placemark details` 프로퍼티를 모두 출력해보아도 용산구는 찾을 수 없습니다. 구글링을 한 결과, 핸드폰 기기 간의 차이가 있다고 하여 여러 시뮬레이터에서 실행해보았지만, 결과는 모두 같았습니다. 용산구를 표시할 방법이 있는지 궁금합니다.
> 
> - 참고 : https://developer.apple.com/documentation/corelocation/clplacemark
> 
> https://velog.io/@yy0867/부스트캠프-기기별-CLPlacemark의-차이
> 
> 
> 
>  

clplacemark를 print 해보셨나요? 현재 first로 첫번째 값을 취하고 있는데 혹시 나머지 값들은 어떤 건지 확인해보셨나요?

2023-11-28 04:48 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Protocols/WeatherUIDelegate.swift
> +protocol WeatherUIDelegate: UIViewController {
주소와 날씨예보를 추후 다른 화면에서 사용할 일이 있을수도 있어서 델리게이트로 만들었습니다.

2023-11-28 08:49 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +    weak var delegate: WeatherUIDelegate?
약한 참조를 하기 위해 `weak` 키워드를 사용했습니다.  메모리 누수가 날 수 있는 상황을 방지하고자 사용하고 바로 메모리 해제를 위하여 사용하였습니다. 참고로 메모리 누수가 계속 일어나면 어떤일이 발생하는지도 찾아보았는데 심각하면 앱이 강제로 종료된다는 것 까지 알게 되었습니다. 😅

2023-11-29 04:44 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +        var locationManager = CLLocationManager()
수정하겠습니다.

2023-11-29 05:21 UTC, newJunsung commented on WeatherForecast/WeatherForecast/ViewController.swift
>              .receive(on: DispatchQueue.main)
receive(on: _)는 Publisher가 어떤 일을 수행하고 나오는 산물에 대해 어디서 처리할 지를 결정하는 역할을 합니다.
헷갈릴 수 있는 개념은 subscribe(on: _)이 있습니다. subscribe는 구독, 취소 요청에 대한 것을 어디서 처리할 지 결정하는 역할을 합니다.

저희가 receive(on: DispatchQueue.main)를 한 이유는 sink에서 하는 클로저가 모두 UI의 업데이트와 관련된 일이고, UI업데이트는 메인 스레드에서 이루어져야하기 때문입니다.

2023-11-29 05:28 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +        var locationManager = CLLocationManager()
CLLocationManager()가 클래스로 선언되어 있기에 값을 변경해서 사용할 수 있습니다. 그렇기에 `상수`로 선언하여 새로운 메모리 주소 안에서 바꿔주는게 맞습니다.  `var`로 했을시
```swift
let locationManger: CLLocationManager = {
        var locationManager = CLLocationManager()
        locationManager.desiredAccuracy = kCLLocationAccuracyBestForNavigation
        locationManager.startUpdatingLocation()
        locationManager.requestWhenInUseAuthorization()
        locationManager = CLLocationManager() // locationManager 초기화 
        return locationManager
    }()
```
코드를 적으면 값이 초기화 될 수 있기 때문에 `let`로 해주는것이 맞습니다.

2023-11-29 05:56 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +            debugPrint("위도: \(location.coordinate.latitude), 경도: \(location.coordinate.longitude)")
`debugPrint` 메서드는 `값 타입` 및 `상세한 정보`가 표시된다고 알고 있습니다. 일반 프린트는 단순히 데이터만 출력합니다.
질문입니다.. 

현업에서 debugPrint를 많이 사용하시나요? 아니면 lldbd `po`를 많이 사용하시나요?

2023-11-29 06:05 UTC, comdori-wj commented
네 해보았습니다. 모든 프로퍼티를 출력하였지만 용산구는 찾을수 없었습니다.
 
<img width="1086" alt="스크린샷 2023-11-29 오후 3 04 40" src="https://github.com/tasty-code/ios-weather-forecast/assets/22284092/f632386e-6bff-4650-afcc-5ca4639c7c90">

2023-11-29 08:26 UTC, newJunsung commented on WeatherForecast/WeatherForecast/ViewController.swift
>                      self.countryLabel.text = error.localizedDescription
강한 참조에 대해서 알아보고 [weak self] 캡처리스트로 수정했습니다.

여기서 질문이 있는데,
```swift
{ [weak self] completion in
    guard let self = self else { return }
    
    switch completion {
    case .finished:
        return
    case .failure(let error):
        self.countryLabel.text = error.localizedDescription
    }
}
```
`guard let self = self else { return }` 여기서 언래핑한 self는 결국 같은 메모리를 가리키게 되어, RC가 증가할 수도 있다는 의문점이 들었습니다. 그렇게 되면 순환 참조에 대한 문제가 해결되지 않게 될 것으로 예상되는데 저희가 생각한 것이 맞나요?

2023-11-29 13:56 UTC, forestjae commented on WeatherForecast/WeatherForecast/Utils/WeatherLocationManager.swift
> +            debugPrint("위도: \(location.coordinate.latitude), 경도: \(location.coordinate.longitude)")
둘다 사용합니다. 디버그 콘솔, lldb 외에 자체적으로 만들어서 쓰는 별도 로그콘솔도 많이 사용합니다.

2023-11-29 14:02 UTC, forestjae commented on WeatherForecast/WeatherForecast/ViewController.swift
>                      self.countryLabel.text = error.localizedDescription
좋은 질문입니다~ 순환 참조는 RC를 증가시켜 일어나는게 아닌 서로 "강하게 참조" 하고 있을 때 일어납니다.

guard 구문으로 self를 언래핑하게 되면 같은 메모리를 가르켜 RC가 실제로 증가합니다. 하지만, 순환참조는 일어나지 않습니다.
이 구문이 실행되는 도중에 RC 값이 1 오르지만, 끝남과 동시에 RC가 -1 되기 때문입니다.

weak self 를 사용하지 않고 그냥 self 를 직접적으로 참조하게 되면, 클로저와 self 사이에 "강한 참조" 가 일어나게 되어 순환참조 문제가 발생합니다.

2023-11-29 14:14 UTC, merged