날씨 앱 [STEP2] Mango, 쫑
tasty-code/ios-weather-forecast pull request #33
Opened 2023-11-29 09:22 UTC by shlim0

# 날씨 앱

## 리뷰어
@jungseungyeo

## 팀원:busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/Dongjun-developer"><img src="https://avatars.githubusercontent.com/u/97822621?v=4" width="90" height="90"></a> | <a href="https://github.com/shlim0"><img src="https://avatars.githubusercontent.com/u/46235301?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@DongJun](https://github.com/Dongjun-developer) | [@JJong](https://github.com/shlim0) 
| in SeSAC | 망고 | 쫑

## 파일구조:file_folder:
```
WeatherForecast
├── APIKeyList.plist
├── Info.plist
├── Delegates
│   ├── AppDelegate.swift
│   ├── SceneDelegate.swift
│   └── UILocationDelegate.swift
├── Enums
│   └── WeatherAPI.swift
├── Errors
│   ├── APIError.swift
│   └── NetworkError.swift
├── Extensions
│   ├── Model+Extension.swift
│   ├── ModelCurrentWeather+Extension.swift
│   └── ModelFiveDaysWeather+Extension.swift
├── Models
│   └── Model.swift
├── Protocols
│   ├── KeyAuthenticatable.swift
│   ├── Networkable.swift
│   ├── RequestDataTaskable.swift
│   ├── RequestSessionable.swift
│   └── Requestable.swift
├── Utilities
│   ├── LocationManager.swift
│   ├── NetworkManager.swift
│   └── Networker.swift
└── ViewControllers
    └── ViewController.swift
```

### 프로젝트 설명
- 앱 실행시 사용자로부터 위치 권한을 획인하여 위치(위도, 경도)와 그에 따른 도로명 주소 및 날씨 API를 활용하여 날씨 정보를 가져옵니다.
<img width="1111" alt="0" src="https://github.com/tasty-code/ios-weather-forecast/assets/46235301/d60b948e-ff2e-44e3-9a1a-5168c0a4ebd8">

https://github.com/tasty-code/ios-weather-forecast/assets/46235301/6746d292-a426-47ea-9918-8321c1e4a697

https://github.com/tasty-code/ios-weather-forecast/assets/46235301/069fba2b-0a39-4d1b-a875-bc01500eaa72

https://github.com/tasty-code/ios-weather-forecast/assets/46235301/5bec375d-7034-44dd-b8a8-9feafd0aff1e

- 위치 정보를 한 번만 가져오기 위해 `LocationManager`를 싱글톤으로 접근하게 했습니다.

### 궁금한점 / 고민하는 점
1. ViewController로 위치(위도, 경도), 주소 정보, 날씨 정보를 보내주고 있으나, 비동기적으로 해당 정보들을 가져오고 있어 원하는 때에 해당 정보에 접근하면 `nil`로 표시됩니다. 이를 해결하는 방법을 잘 모르곘습니다.
<img width="1127" alt="image" src="https://github.com/tasty-code/ios-weather-forecast/assets/46235301/b2839656-4d73-4870-96fc-dd55c8a3c49c">

2. 위에서 언급한 정보들을 ViewController로 보내주려 completion handler를 계속해 사용하여 callback 지옥에 빠졌다가 결국 delegate로 선회하여 구현하였는데요. 언제 completion을 쓰는 게 나은지, delegate를 쓰는 게 나은지 잘 모르겠습니다. completion handler를 쓰는 것이 논리적으로 더 실행 흐름을 잘 파악할 수 있을 것 같아 해보았으나, 오히려 실행 흐름을 파악하기 정말 어려웠었습니다.

일례로, 다음과 같이 delegate를 사용하였습니다.

```swift
// LocationManager.swift
func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        guard let coordinate = manager.location?.coordinate else {
            return
        }
        
        manager.stopUpdatingLocation()
        delegate?.update(coordinate: coordinate) // 위치 정보를 ViewController로 넘겨줌
        fetchPlacemark()  // VC에서 돌아와 completion handler를 사용하지 않고 순차적으로 실행되도록 함 (주소 정보)
    }
```

3. `manager.stopUpdatingLocation()`가 주석처리 되어도 위치 정보를 한 번만 출력합니다. 싱글톤 구조로 바꾼 이후로는 이렇게 되는데요. 싱글톤 구조와 어떤 연관이 있는지 궁금합니다.
<img width="1113" alt="image" src="https://github.com/tasty-code/ios-weather-forecast/assets/46235301/e1d92ea5-de50-430b-8061-cdfd8c1868eb">

P.S. 화상 통화를 통해 추가적인 피드백 언제나 환영합니다.

2023-11-29 22:45 UTC, jungseungyeo requested changes
1. ViewController로 위치(위도, 경도), 주소 정보, 날씨 정보를 보내주고 있으나, 비동기적으로 해당 정보들을 가져오고 있어 원하는 때에 해당 정보에 접근하면 nil로 표시됩니다. 이를 해결하는 방법을 잘 모르곘습니다.

> 근본적인 문제는 API 내부에서 위치 권한을 요청하는 코드가 작성되어 있습니다. GPS는 주기적으로 값을 폴링을 통해 업데이트를 하기 떄문에 처음 실행하여도 동기적으로는 없는 시점이 처음에는 존재 할 수 밖에 없습니다. 따라서 위치 권한이 있고, 위치 값이 있는 상태가 보장을 해주고 요청을 보내는 방식으로 개발이 되어야 합니다. 

> 위의 방식을 하기 위해서는 비동기 콜백을 기다리고 요청 값이 오면 동작을 하게 하여 콜백, 콜백 구조가 되는데요. completion, delegate의 근본적으로 둘다 비동기 로직이기 때문에 큰 틀에서는 다르지 않는데요, 의존성 관점에서만 다른거라 동작이 다르게 되는 원리는 아닙니다. 제가 추천하는 방식은 completion을 쓰는게 좋다고 판단을 저도 하고 있는데요. 이렇게 된다면, `completion { networker.request { ...} }` 로 작성이 될 거같습니다. 

2. 위에서 언급한 정보들을 ViewController로 보내주려 completion handler를 계속해 사용하여 callback 지옥에 빠졌다가 결국 delegate로 선회하여 구현하였는데요. 언제 completion을 쓰는 게 나은지, delegate를 쓰는 게 나은지 잘 모르겠습니다. completion handler를 쓰는 것이 논리적으로 더 실행 흐름을 잘 파악할 수 있을 것 같아 해보았으나, 오히려 실행 흐름을 파악하기 정말 어려웠었습니다.

> 1번의 답변 처럼 흐름이 파악이 어려워 delegate를 사용했다고 하였는데요, delegate를 사용하면 현재 구조에서는 update 함수?에서 위치 값이 있는지 없는지 같은 경우를 체크해서 처리를 해주면 좋을거같습니다. 어느 방법을 사용해도 큰 문제는 없는데요. 동작의 있어서 현재 위치 값을 전달하는 방식을 보존 할 수 없는거같습니다. 위치 값을 있는 경우 전달을 주던지 아니면 없는경우 에러로 처리를 하던지 둘중 하나의 방법을 사용해야할거같습니다.

3. `manager.stopUpdatingLocation()`가 주석처리 되어도 위치 정보를 한 번만 출력합니다. 싱글톤 구조로 바꾼 이후로는 이렇게 되는데요. 싱글톤 구조와 어떤 연관이 있는지 궁금합니다.

> 이건 싱글톤이랑 상관이없을텐데.. 동작되는 코드를 전달해주시면 한번 확인 볼 수 있을거같은데요. 동작 되는 코드 전달부탁드립니다. ㅠ 전달해주시면 확인해보겠습니다.

2023-11-29 22:45 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +    static let shared = LocationManager()
싱글톤으로 작성된 이유가 있나요?

2023-11-29 22:45 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Enums/WeatherAPI.swift
> +        let locationManager = LocationManager.shared
여기서 위치 정보가 매니저가 있으면 안될거같아요. 
여기서 위치 정보를 가져오는 Manager를 의존한다면 api의 관계가 힘들어질거같습니다.

힘들어서 의존성을 주입해준 이유가 없어지게 됩니다.

2023-11-29 22:45 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Enums/WeatherAPI.swift
> +        let locationManager = LocationManager.shared
외부에서 위치정보를 넘겨주는 형태로 변경이 필요해보여요

2023-11-29 22:45 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Enums/WeatherAPI.swift
> +        let locationManager = LocationManager.shared
enum에서 위치 값을 전달하는 방식이 있을거같아요. case current(latitude: Double, longitude: Double)의 형태는 어떤가요?

2023-11-29 22:45 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Enums/WeatherAPI.swift
>              return nil
여기서 위치 권한을 없는 경우 에러처리가 어려워요. 개발을 핵심은 에러처리입니다. 에러가 발생 할 때 사용자에게 어떻게 잘 표시 할 수 있는지? 유지 보수를 할 수 있는지등을 고려해야합니다.

위치 권한이 없는 경우 해당 코드에서는 url이 왜 nil이 되는지 외부에서는 알기 어렵습니다. 이렇게 된다면 에러 코드를가 더 힘들어지겠죠? 

외부에서 위치 권한이 없는 경우 어떻게 동작이 되어야하는지 체크하고 해당 api를 호출하면 좋습니다. 

예를 들어 
- 위치 권한이 없는 경우 
- 위치 권한은 있지만 위치 값을 못 가져오는 경우
- 위치 값이 있는 경우

위의 경우 모두 같은 flow가 될 수 없겠죠?
값은 flow가 될려면 어디 가에서 위치 값이 없는 경우 고정을 넣을 줄지 안넣을지 판단을 해주어야 합니다. 

위치 권한이 없는 경우의 대해서 어떤 flow를 가져갈거면 없는 경우 사용자에게 어떻게 알려줄수있는지등을 고려해서 역할을 분리하면 좋을거같습니다.

2023-11-29 22:45 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +    static let shared = LocationManager()
싱글톤을 물어보는 이유는 싱글톤이 아니여도 해결이 가능할수있다는 생각이 들어서 질문을 드렸습니다. 

위치 권한을 싱글톤으로 관리 해야하는 이유가 있는지? 혹은 어떤 역할의 주기 위하여 채택했는지가 궁금했습니다.

싱글톤의 단점인 메모리 해지가 안되는 점, 싱글톤으로 되어 외부에서 쉽게 접근이 되어 의존성이 생기기 쉽다는 단점등을 고려했을떄
이 부분을 상회하는 장점이 있는지가 궁금합니다.

2023-12-01 05:00 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Enums/WeatherAPI.swift
> +        let locationManager = LocationManager.shared
의견 주신대로 반영하였습니다. 아무래도 `WeatherAPI`가 `LocationManager`를 갖고 있는 모습은 이상해 보입니다.

View Controller에서 `LocationManager` 인스턴스를 통해 위치 정보를 주입하도록 하였습니다.

```swift
// ViewController.swift
  let networker = Networker<Model.CurrentWeather>(request: 
  WeatherAPI.current(coordinate))
```

```swift
// WeatherAPI.swift
enum WeatherAPI {
    case current(_ coordinate: CLLocationCoordinate2D)
    case fiveDays(_ coordinate: CLLocationCoordinate2D)
}
```

2023-12-01 05:05 UTC, ehdwns0814 commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +    static let shared = LocationManager()
LocationManager는 weatherAPI enum에서 위치 값을 넘겨주는 기능과 GeoCoder를 통하여 좌표값을 주소값으로 돌려는 기능을 하는 메서드를 호출하는 곳에 객체를 각각 생성하기보다 싱글톤으로 작성하면 객체를 한 번만 생성해도 되어서 메모리를 절약할 수 있다고 생각하여 사용하였으나, 결합도를 증가시키고 Unit 테스트로 힘들게 하는 것 같아 싱글톤 패턴은 삭제하였습니다.

2023-12-01 05:32 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Enums/WeatherAPI.swift
>              return nil
얘기 주신 것처럼 `return nil`의 형태는 어디서 문제가 되는지 알기 어렵기 때문에 코드를 일일히 찾아가 봐야 한다는 애로사항이 있다고 깨달았습니다. 따라서, 에러를 더 명확히 표시하도록 반영했습니다.

위치 권한에 대한 Error 타입을 만들었습니다.
```swift
enum LocationError: Error {
    case failedFetchLocationError
    case noLocationError
    case noPlacemarkError
    case noLocationAuthorizationError
    case unknownLocationAuthorizationError
}
```
`LocationError`를 토대로 `LocationManager`에서
1. 위치 권한이 없는 경우 (`noLocationAuthorizationError`, `didFailFetchLocationError`)
2. 위치 권한은 있지만 위치 값을 못 가져오는 경우 (`noLocationError`)
3. 위치 값이 있는 경우 (`completion(.success((coordinate, address)))`)

같은 경우에 맞도록 에러 케이스를 사용했습니다.

위치 권한이 없을 때, 사용자에게 이를 알려야 하는데, `ViewController`에서 `error`를 받아 `UIView`에서 처리하면 될 것 같습니다.
 (View 구현은 Step3에서 진행됩니다)

또한, `WeatherAPI`에서 `KeyAuthenticatable`를 채택하여 `APIKey`를 사용하는데, 굳이 불필요한 `guard let`을 생략하기 위해 `KeyAuthenticatable` 내부에서 `error`를 `return` 하도록 하였습니다.

```swift
// KeyAuthenticatable.swift
 var APIKey: String {
        switch checkAPIKey() {
        case .success(let APIKey):
            return APIKey
        case .failure(let error):
            print(error)
            return error.localizedDescription
        }
    }
```

2023-12-01 05:40 UTC, shlim0 commented
> 1. ViewController로 위치(위도, 경도), 주소 정보, 날씨 정보를 보내주고 있으나, 비동기적으로 해당 정보들을 가져오고 있어 원하는 때에 해당 정보에 접근하면 nil로 표시됩니다. 이를 해결하는 방법을 잘 모르곘습니다.
> 
> > 근본적인 문제는 API 내부에서 위치 권한을 요청하는 코드가 작성되어 있습니다. GPS는 주기적으로 값을 폴링을 통해 업데이트를 하기 떄문에 처음 실행하여도 동기적으로는 없는 시점이 처음에는 존재 할 수 밖에 없습니다. 따라서 위치 권한이 있고, 위치 값이 있는 상태가 보장을 해주고 요청을 보내는 방식으로 개발이 되어야 합니다.
> 
> > 위의 방식을 하기 위해서는 비동기 콜백을 기다리고 요청 값이 오면 동작을 하게 하여 콜백, 콜백 구조가 되는데요. completion, delegate의 근본적으로 둘다 비동기 로직이기 때문에 큰 틀에서는 다르지 않는데요, 의존성 관점에서만 다른거라 동작이 다르게 되는 원리는 아닙니다. 제가 추천하는 방식은 completion을 쓰는게 좋다고 판단을 저도 하고 있는데요. 이렇게 된다면, `completion { networker.request { ...} }` 로 작성이 될 거같습니다.

delegate로 바꾼 구조를 completion handler를 사용하는 구조로 바꾸었습니다. 콜백이 연속되기 때문에(위치정보를 받은 후 이를 토대로 날씨 정보를 가져와야 하기 때문에) `ViewController` 내부 코드가 지저분해 보일 순 있으나, `코드만 봤을 때 위치 정보를 받은 후 날씨 정보를 가져온다`는 의미를 직관적으로 표현하기 때문에 더 나은 판단이라 생각했습니다. 물론 이전에 completion handler를 사용하는 것이 실행 흐름을 파악하기 어렵다고 답변드렸는데요, 다시 보니 너무 무분방하게 사용해서 그렇게 느끼지 않았을까 싶습니다.

**또한, 어떤 상황에서 delegate를 쓸지, completion handler를 쓸지 tip이 있다면 코멘트 부탁드립니다.** 찾아보니 무엇이 더 좋고 나쁘다는 의미가 아니라 상황에 따라 사용하는 것 뉘앙스 인데요. 이에 대한 감이 잘 오지 않습니다.

> 2. 위에서 언급한 정보들을 ViewController로 보내주려 completion handler를 계속해 사용하여 callback 지옥에 빠졌다가 결국 delegate로 선회하여 구현하였는데요. 언제 completion을 쓰는 게 나은지, delegate를 쓰는 게 나은지 잘 모르겠습니다. completion handler를 쓰는 것이 논리적으로 더 실행 흐름을 잘 파악할 수 있을 것 같아 해보았으나, 오히려 실행 흐름을 파악하기 정말 어려웠었습니다.
> 
> > 1번의 답변 처럼 흐름이 파악이 어려워 delegate를 사용했다고 하였는데요, delegate를 사용하면 현재 구조에서는 update 함수?에서 위치 값이 있는지 없는지 같은 경우를 체크해서 처리를 해주면 좋을거같습니다. 어느 방법을 사용해도 큰 문제는 없는데요. 동작의 있어서 현재 위치 값을 전달하는 방식을 보존 할 수 없는거같습니다. 위치 값을 있는 경우 전달을 주던지 아니면 없는경우 에러로 처리를 하던지 둘중 하나의 방법을 사용해야할거같습니다.

https://github.com/tasty-code/ios-weather-forecast/pull/33#discussion_r1411629673 에서 답변한 것 처럼 위치 값이 있는지를 체크하여 처리하도록 하였습니다!

2023-12-01 11:59 UTC, jungseungyeo approved these changes
망고, 쫑 고생하셨습니다.

제 의도의 맞게 수정이 된거같네요 ㅎㅎ 고생하셨습니다. 다음 스텝으로 진행부탁드립니다.

2023-12-01 11:59 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/ViewControllers/ViewController.swift
> +        locationManager.request { result in
좋습니다 ㅎㅎ

2023-12-01 11:59 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/ViewControllers/ViewController.swift
> +    private var model: Decodable?
이건 모델을 의존해도 괜찮을거같아요 ㅎㅎ

2023-12-01 11:59 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/ViewControllers/ViewController.swift
> +                let networker = Networker<Model.CurrentWeather>(request: WeatherAPI.current(coordinate))
이 네트워크 객체도 전역변수로 하면 어떤가요?

2023-12-01 11:59 UTC, merged

2023-12-01 13:37 UTC, shlim0 commented on WeatherForecast/WeatherForecast/ViewControllers/ViewController.swift
> +                let networker = Networker<Model.CurrentWeather>(request: WeatherAPI.current(coordinate))
이것도 반영하겠습니다!