[STEP2] JaeHyeok. Beom
tasty-code/ios-weather-forecast pull request #34
Opened 2023-11-30 02:43 UTC by SimJaeHyeok

# 날씨 앱 [STEP2] jaeHyeok, 범

리뷰어 : @jryoun1 (Jake)
안녕하세요 제이크 STEP2 PR 드립니다.

- 네트워크 없이 Unit 테스트를 하는 방법을 말씀해주신 키워드로 검색해 읽고있지만 unit 테스트를 작성하지 못했습니다. 시간이 조금 더 걸릴 것 같습니다.
- 위치 권한의 상태를 확인하는 것은 step2에서는 사용자가 새로운 날씨정보를 얻고 싶어서 조작할 ui가 없기 때문에 step2에서는 필요가 없고 step3에서 추가를 할 예정입니다.

## 구현사항
- 현재 위치의 위도와 경도를 알아냅니다.
- 위도와 경도를 활용해 현재 위치의 주소를 알아냅니다.
- 현재 위치의 날씨와 현재 위치의 5일 예보를 날씨 API를 통해 데이터를 요청하고 받아오는 기능을 구현합니다.

## 실행화면
<img src= "https://hackmd.io/_uploads/rJy3hvBBa.png" width="50%" height="50%"/>

## 질문사항🙋
- `CLPlacemark`에서 "용산구"처럼 구를 받아 오려했는데 애플 공식문서에 적힌 detail를 보여주는 프로퍼티는 '구' 관련 정보가 없고 나라, 시, 동, 지번, 우편번호는 존재를 하지만 '구'는 없는데 구를 표시할 수 있는 다른 방법이 있을까요?
- `APIRequestable` 과 `NetworkServiceable` 각각의 프로토콜을 큰 범주에서 보면 `NetworkService`에 `APIRequstable`이 있는게 맞다고 생각이 되는데 지금처럼 따로 분리해놓으면 가독성이 좋아지고 해당 부분을 빠르게 찾을 수 있다는 장점이 있습니다 두 가지 프로토콜을 하나로 합치는게 좋은 지 지금처럼 세세한 분리를 하는게 맞는 지 제이크의 의견이 궁금합니다.

2023-11-30 14:21 UTC, jryoun1 requested changes
고생하셨습니다 👏 👍 

몇가지 코멘트 남겨두었습니다 확인부탁드려요 🙏 

### 질문사항

> CLPlacemark에서 "용산구"처럼 구를 받아 오려했는데 애플 공식문서에 적힌 detail를 보여주는 프로퍼티는 '구' 관련 정보가 없고 나라, 시, 동, 지번, 우편번호는 존재를 하지만 '구'는 없는데 구를 표시할 수 있는 다른 방법이 있을까요?

지금으로서 CLPlacemark의 property들을 사용해서 구를 표시하기 어렵다면 우선은 시나 동까지만 나타내도 될 것 같아요. 구를 추가하고 싶다면 위도, 경도를 넘겨 구를 구해주는 api를 추가로 사용하거나 만약 서비스만의 서버가 따로 있다면 서버에서 해당 작업을 처리해주는 방향으로 진행을 하게 될 것 같네요. 
→ 즉, 지금 프로젝트에서는 그렇게 크게 중요한 부분은 아닌 것 같아서 넘어가셔도 괜찮을 것 같아요 👍 

> APIRequestable 과 NetworkServiceable 각각의 프로토콜을 큰 범주에서 보면 NetworkService에 APIRequstable이 있는게 맞다고 생각이 되는데 지금처럼 따로 분리해놓으면 가독성이 좋아지고 해당 부분을 빠르게 찾을 수 있다는 장점이 있습니다 두 가지 프로토콜을 하나로 합치는게 좋은 지 지금처럼 세세한 분리를 하는게 맞는 지 제이크의 의견이 궁금합니다.

두 분이 생각하시는 각각의 프로토콜의 역할은 무엇일까요? 
또한 지금은 왜 분리해 놓으셨는지, 두 개를 합쳤을 때의 역할은 무엇이며 합쳐야하는 이유가 무엇인지 궁금합니다 🙋‍♂️

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
> +}
모든 네트워크 서비스에서 사용할 수 있는 함수를 protocol로 빼셨군요 👏 
다만 지금의 경우도 다른 endpoint가 생긴다면 ~NetworkService 라는 객체가 계속해서 생성이 되어야할 것 같아요.

url만 받아서 URLSession을 통해 호출하는 역할을 가진 것이 NetworkServiceProvider가 된다면, 더 이상 endpoint가 추가된다고 했을 때 ~networkService자체는 생성되지 않고, endpoint객체를 추상화한 객체만이 추가되면 될 것 같습니다. 🙏🏻
```Swift
class NetworkServiceProvider {
     func fetch<T: Decodable>(url: URL, completionHandler: @escaping (Result<T, NetworkError>) -> Void) {
        URLSession.shared.dataTask(with: url) { data, response, error in
            handlingDataResponse(data: data, response: response, error: error, completionHandler: completionHandler)
        }.resume()
    }
}
```

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    }
일반적으로 함수들의 선언은 해당 함수를 사용하는 함수가 상위에서 호출되는 것 같아요! 
즉, locationManager()에서 getCurrentWeatherData, getForecastWeatherData 두 함수를 호출하고 있으니 locationManager() 이후에 getCurrentWeatherData, getForecastWeatherData가 위치하는게 더 자연스러운 것 같습니다 🙏

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        let longitude = location.coordinate.longitude as Double
location.coordinate.latitude의 타입이 어떤 타입일까요? 🙋‍♂️

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    private let location = CLLocationManager()
CLLocationManger 인스턴스를 사용해보셨군요 👏 💯 
location이라는 네이밍은 어색해보입니다!

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
여긴 함수 사이 줄바꿈이 없는 것 같습니다!

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecastTests/WeatherForecastTests.swift
> -    }
추후에 서버가 있을 때의 코드와 서버가 없었을 때의 코드도 한 번 비교해보시면 좋을 것 같아서 기존에 있던 코드는 당분간 냅둬도 상관없을 것 같아요! 
(서버가 없었을 때의 코드를 다 작성한 이후나 프로젝트가 끝나고나서 제거해도 될 것 같아요!)

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
> +
어떤 곳에서는 protocol선언 이후 줄바꿈이 있는 경우가 있고, 없는 경우가 있네요.
extension에서도 동일합니다! convention 확인 부탁드려요 🙏

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/GeoConverter.swift
> +    func convertToAddressWith(coordinate: CLLocation, completionHandler: @escaping (Result<String,GeoConverterError>) -> Void )
Void 뒤에 space가 있는 것 같네요!  아래 extension도 동일합니다! (completionHandler에서도 : 전에 space가 하나 더 있네요)

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/GeoConverter.swift
> +            guard let name = placemark.subLocality else { return }
여기서는 .failure를 호출하지 않고 그냥 return 해도 될까요?
추가로 하나의 guard 구문에 쓸 수 있을 것 같습니다 🙏

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/GeoConverter.swift
> +        let geoCoder = CLGeocoder()
CLGeocoder 인스턴스를 사용해보셨네요 👏

2023-11-30 14:21 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Models/Network/WeatherURLConfigration.swift
> +        guard let apiKey = createApiKey(name: "API_KEY") else { return "" }
apiKey가 없는 경우에는 빈 문자열을 반환해도 될까요? 🤔 
apiKey를 빈문자열로 해서 api 호출하면 실패하게 될텐데 실패하기 전에 막는것이 낫지 않을까요?

2023-12-01 00:59 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    }
말씀하신대로 코드 진행에 따라 배치하는게 옳다고 생각하여 수정하였습니다.

2023-12-01 01:01 UTC, silverjaehyeok commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        let longitude = location.coordinate.longitude as Double
<img width="344" alt="image" src="https://github.com/tasty-code/ios-weather-forecast/assets/142188004/8441532e-df10-471b-80af-160d1227593a">

타입이 다르다고 생각하여 캐스팅을 하였는데 `typealias`를 이용한 `Double` 타입이었습니다 수정하였습니다!

2023-12-01 01:03 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    private let location = CLLocationManager()
조금 더 명확하게 `locationManager`로 수정하였습니다!

2023-12-01 01:07 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
수정하였습니다.

2023-12-01 01:07 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
> +
줄바꿈 있는 걸로 통일하였습니다!

2023-12-01 01:08 UTC, silverjaehyeok commented on WeatherForecast/WeatherForecast/Protocols/GeoConverter.swift
> +    func convertToAddressWith(coordinate: CLLocation, completionHandler: @escaping (Result<String,GeoConverterError>) -> Void )
수정하였습니다!

2023-12-01 01:13 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Protocols/GeoConverter.swift
> +            guard let name = placemark.subLocality else { return }
말씀하신대로 `guard` 구문을 하나로 만들고 `completionHandler`로 에러처리를 하였습니다.

2023-12-01 07:59 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecastTests/WeatherForecastTests.swift
> -    }
확인했습니다!

2023-12-01 08:03 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
> +}
말씀해주신 NetworkServiceProvider로 다른 endpoint도 가능하게 변경하고 , apikey 에러와 url 에러를 체크하는 메서드를 APIRequestable로 옮겨놨습니다.

2023-12-01 08:05 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/Models/Network/WeatherURLConfigration.swift
> +        guard let apiKey = createApiKey(name: "API_KEY") else { return "" }
잘못된 apiKey이름을 입력하면 에러처리를 하도록 변경했습니다.

2023-12-01 08:11 UTC, snowy-summer commented on WeatherForecast/WeatherForecastTests/WeatherForecastTests.swift
> -    }
넵, 다시 복구 해놓았습니다. 
유닛 테스트를 진행할 때 네트워크라는 외부의 요소를 영향을 받지 않기 위한 것이 Mock형식으로 테스트 코드를 작성하는 이유라고 생각합니다. 그러면 점점 단계를 진행하면서 유닛 테스트를 진행할 때 계속 끝까지 네트워크의 연결없이 유닛 테스트를 작성하는 것인가요?

2023-12-01 08:17 UTC, SimJaeHyeok commented
두 분이 생각하시는 각각의 프로토콜의 역할은 무엇일까요?
또한 지금은 왜 분리해 놓으셨는지, 두 개를 합쳤을 때의 역할은 무엇이며 합쳐야하는 이유가 무엇인지 궁금합니다 🙋‍♂️
- URL을 만드는 기능과 네트워킹하여 데이터를 받아오는 기능을 가지고 있습니다. 두개를 합쳤을 때는 네트워킹이라는 큰 범주의 역할을 하게 됩니다. 네트워킹이라는 하나의 흐름을 파악할 수 있어서 하나로 합치고자 했었습니다만,  부분적인 기능을 찾을 때는 전체 흐름을 봐야한다는 불편함이 존재하였고 한 파일안에 프로토콜을 두 가지로 분류하여 작성하는 방법도 있었지만, 파일을 분리하여 한번에 원하는 기능을 찾을 수 있는 장점이 컸기 때문에 두 가지로 분류하는 게 맞는 것 같습니다.

2023-12-02 03:23 UTC, jryoun1 commented on WeatherForecast/WeatherForecastTests/WeatherForecastTests.swift
> -    }
넵 unit 테스트에서는 실제로 서버와 연결되는 것이 필수로 보이지는 않습니다. 
unit 테스트는 테스트하고자 하는 부분에 대해서 테스트를 진행하는 것인데, 예를 들어 네트워크 모듈을 테스트하고자할때 
- url을 잘 생성하는지
- response를 잘 파싱하는지
- response가 에러일 때 처리를 잘하는지 

등을 테스트하려고 했을 때 저 부분들에 대해서 독립적으로 테스트를 진행해야지, 실제 서버로부터 응답이 오는것(dependency)가 생긴 상태에서 테스트를 진행하게 되면 저 기능들만 독립적으로 테스트를 진행하지 못하게 됩니다. 
따라서 서버와의 dependency없이 mock을 사용해서 네트워크 모듈의 로직들이 잘 동작하는지 테스트를 진행해볼 수 있겠네요. 

물론 네트워크 모듈의 해당 로직들에 대한 테스트는 unit 테스트에서는 mock을 통해 진행할 수 있고, 그 이후에 api가 나왔다(지금의 경우는 open api니까 이미 존재)면 실제 api를 붙여서 테스트 코드를 돌려볼수도 있을 것 같네요. 
즉, test 코드에서 response로 mock을 주입받을지, 실제 서버로부터의 응답을 받을수 있도록 구현해놓는다면 더 좋겠지만 이 부분은 우선 mock으로 하는 테스트 이후에 필요하다면 진행해봐도 괜찮을 것 같네요.

2023-12-02 03:33 UTC, jryoun1 approved these changes
고생하셨습니다 대부분 잘 수정해주셔서 다음 step으로 넘어가도 될 것 같습니다.
step3도 화이팅입니다 🦾 

> APIRequestable 과 NetworkServiceable 각각의 프로토콜을 큰 범주에서 보면 NetworkService에 APIRequstable이 있는게 맞다고 생각이 되는데 지금처럼 따로 분리해놓으면 가독성이 좋아지고 해당 부분을 빠르게 찾을 수 있다는 장점이 있습니다 두 가지 프로토콜을 하나로 합치는게 좋은 지 지금처럼 세세한 분리를 하는게 맞는 지 제이크의 의견이 궁금합니다.
>> URL을 만드는 기능과 네트워킹하여 데이터를 받아오는 기능을 가지고 있습니다. 두개를 합쳤을 때는 네트워킹이라는 큰 범주의 역할을 하게 됩니다. 네트워킹이라는 하나의 흐름을 파악할 수 있어서 하나로 합치고자 했었습니다만, 부분적인 기능을 찾을 때는 전체 흐름을 봐야한다는 불편함이 존재하였고 한 파일안에 프로토콜을 두 가지로 분류하여 작성하는 방법도 있었지만, 파일을 분리하여 한번에 원하는 기능을 찾을 수 있는 장점이 컸기 때문에 두 가지로 분류하는 게 맞는 것 같습니다.

두 프로토콜의 역할이 같다면 혹은 해당 프로토콜을 채택하는 인스턴스가 모든 property, func를 가지고 관리해도 된다면 합치는 것이 낫겠지만, 지금으로서는 두 개의 프로토콜이 하는 역할이 다르다고 생각하기에 따로 관리하시는게 더 좋아 보이긴합니다! 정답은 없으니 두 분께서 합쳐도 보고 합쳤을 때와 분리했을 때의 차이를 경험해보셔도 좋을 것 같네요. 🙏

2023-12-02 03:33 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Models/Network/WeatherURLConfigration.swift
> +    init(weatherType: WeatherType,coordinate: CLLocationCoordinate2D){
coordinate 전에 space가 빠졌네요!

2023-12-02 03:33 UTC, merged