날씨 앱 [Step2] 도라, 밤삭
tasty-code/ios-weather-forecast pull request #37
Opened 2023-12-04 10:15 UTC by bamsak

# 날씨 앱

## 리뷰어
@zdodev

## 팀원:busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/bamsak"><img src="https://avatars.githubusercontent.com/u/114239407?v=4" width="90" height="90"></a> | <a href="https://github.com/KSK9820"><img src="https://avatars.githubusercontent.com/u/68066104?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@bamsak](https://github.com/bamsak) | [@KSK9820](https://github.com/KSK9820) 
| in SeSAC | 밤삭 | 도라

<br/>

## 프로젝트 파일 구조
```
├── Extension
│   └── Bundle+Extension.swift
├── Model
│   ├── APIDTO
│   │   ├── CommonWeatherDTO.swift
│   │   ├── CurrentWeather.swift
│   │   └── WeeklyWeather.swift
│   ├── CurrentLocationInfo.swift
│   ├── Error
│   │   ├── NetworkError.swift
│   │   └── QueryError.swift
│   ├── HTTP
│   │   └── HTTPMethod.swift
│   └── URL
│       └── WeatherURL.swift
├── Protocol
│   ├── APIBaseURLProtocol.swift
│   ├── CurrentLocationManagable.swift
│   ├── NetworkManagable.swift
│   ├── URLFormattable.swift
│   └── WeatherUpdateDelegate.swift
├── Utility
│   ├── CurrentLocationManager.swift
│   ├── LocationManager.swift
│   ├── NetworkManager.swift
│   └── WeatherURLFormatter.swift
└── ViewController.swift
```
<br/>

## 프로젝트 설명
### 구현 내용

- [x]  `CoreLocation`을 통해 현재 좌표 가져오기
- [x]  `CoreLocation`을 통해 주소 가져오기
- [x]  `URLSession`을 통해 API호출 (HTTP GET 메소드 명시적 호출)
- [x]  전달받은 `JSON` 데이터 파싱 및 모델에 매칭
---
### 각 역할 설명
#### Protocol
- **CurrentLocationManagable**
    - LocationManager에서 위치 변화가 감지되었을 때 위치 좌표(CurrrentLocationInfo)를 업데이트하는 역할을 하는 프로토콜 입니다.
- **NetworkManagable**
- **WeatherUpdateDelegate**
    - LocationManager의 CLLocationManager를 통해 받아온 위, 경도를 해당 프로토콜을 채택한 타입(ex: ViewController)에 전달하여 대신 일 처리를 해주는 프로토콜 입니다.

---
#### Model
- **CurrentLocationInfo**
    - 사용자의 현재 위치의 위, 경도 및 현재 위치의 주소 ex) 서울시 용산을 담아놓기 위한 모델 입니다.
    - 재사용성을 고려하여 위치 정보들을 구조체로 묶어주었습니다.
- **HTTPMethod**
    - get, post, put, delete같은 HTTPMetod를 열거해놓은 열거형
    - 현재 프로젝트엔 get만 사용할 것 같아 get만 추가 해놓았습니다.
---
#### Utility
- **LocationManager**
    - 사용자 기기의 GPS와 통신하는 역할을 해주는 객체입니다. 
    - CurrentLocationManagable, WeatherUpdateDelegate의 인스턴스를 프로퍼티로 가지고 있어, 위치 정보가 업데이트 되었을 때 순차적으로 CurrentLocationInfo를 업데이트하고 API Request를 보냅니다.
- **CurrentLoctionManager**
    - 현재 위치의 정보를 프로퍼티로 가지고 있고, 해당 프로퍼티의 값을 통해 API Request를 보내는 역할을 하는 객체입니다.
---
#### Error
- **QueryError**
    - Query의 파라미터 오류를 (좌표 정보가 없는 경우, APIKey 가 없는 경우) 2가지 케이스로 분류하였습니다.

<br/>

## Trouble Shooting

### 위치 정보를 받아오는 메소드가 비동기로 작동하여 API통신 메소드의 호출 시점 문제

- 위치를 요청하는 메소드가 비동기로 작동되기 때문에 현재 사용자의 위치 좌표(위, 경도)를 받아오기도 전에 API Request를 보내게 되어 response의 statuscode가 400번대로 잡혀 에러가 발생하는 문제가 있었습니다.
- 해당 시점을 맞추고자 delegate패턴을 통해 `locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation])` 메소드 구문 내에서 api를 통신해주는 메소드를 호출해주는 방식으로 하여 해결하였습니다.    

 
    
## 궁금한 점
- 사용자의 위치 허용 상태(authorizationStatus)가 denied일 경우, 사용자 기기의 GPS 활성화 상태에 따라 분기처리를 해주고 싶었습니다.
- 그리하여 `CLLocationManager.locationServicesEnabled()`라는 메소드를 통해
    - GPS가 활성 상태라면 true -> 앱의 권한을 설정하는 방법
    - GPS가 비활성 상태라면 false -> 기기 자체의 GPS의 설정하는 방법
    - 위의 두가지 방법으로 분기처리를 해주려고 했는데 해내지 못했습니다.
    - 호출 시점이 authorizationStatus를 확인 후 호출하라는 에러가 발생했고, 그에 다른 처리를 해주려고 했는데, mainThread에서 `CLLocationManager.locationServicesEnabled()`를 호출하면 View를 그리는 데에 문제가 생길 수 있다는 에러가 발생하였습니다.
        - 이 부분을 해소하기 위해 globalQueue로 보내고 DispatchGroup으로 묶어 처리를 하려고 했지만, 실행 중에 기기 자체의 GPS를 비활성화 하여도 권한이 변경되는 것은 아니어서 `locationManagerDidChangeAuthorization(_ manager: CLLocationManager)`가 재실행 되지 않아 그에 따른 이벤트를 발생시킬 수 없었습니다.
        - `그리하여 SceneDelegate의 sceneDidbecomeActive 메소드에서 `locationServicesEnabled()`메소드를 호출하려고 하니 다시 한번 authorizationStatus를 확인 후 호출하라는 에러가 발생하였습니다.
        - 이런 경우에는 denied 상태일 때, 어떠한 방식으로 분기처리를 해야하는지 궁금합니다.
        - 괜한 쓸데 없는 것에 묶여있는 거 아닌가 걱정이가 됩니다.. ㅠㅠ 
        - 어떻게든 해결해보고 싶어서 이거에 3~4일을 보냈습니다...

2023-12-05 12:40 UTC, zdodev requested changes
안녕하세요! @bamsak , @KSK9820 

날씨 앱 Step2 잘 진행해주셨습니다!
CoreLocation과 Delegate, 데이터 통신 부분까지 잘 구현해보셨네요!

중간에 위치 서비스 권한에 대한 많은 고민이 있었던거 같습니다!
괜한 기능에 묶여 있었다고 생각할 필요가 없습니다🙂 앱 사용 권한에 대해 시간을 많이 들인 만큼 다양한 케이스를 접할 수 있었고 공부도 많이 되었을 것 같습니다! 실제로도 많이 겪는 문제이기도 합니다.
'지금 스텝에서 전부 다 풀고 해결해야지!' 라기 보다는 스텝을 진행하면서 풀어나가면 더 좋지 않을까 싶습니다.
현재 스텝에서는 현재 위치에 대한 좌표와 주소, 날씨 데이터를 가져오는 것만으로 충분하지 않을까 싶습니다!👍

그 이외에 몇 가지 코멘트를 남겨보았습니다!
같이 의견 나눠보면 좋을 것 같습니다~

2023-12-05 12:40 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/LocationManager.swift
> +    private(set) var manager: CLLocationManager!
`let` 대신 `private(set)` 으로 선언하고 `!` 을 사용하신 이유가 있을까요?

2023-12-05 12:40 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/LocationManager.swift
> +        switch manager.authorizationStatus {
warning 이슈가 발생하고 있습니다. 해결해볼 수 있을까요?

2023-12-05 12:40 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/LocationManager.swift
> +    }
사용하지 않는 메서드는 정리해보는 것이 어떨까요?

2023-12-05 12:40 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/CurrentLocationManager.swift
> +    init(locationInfo: CurrentLocationInfo? = nil, networkManager: NetworkManagable) {
init에서 `locationInfo` 파라미터를 정의한 이유가 궁금합니다!

2023-12-05 12:40 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/HTTP/HTTPMethod.swift
> +}
HTTPMethod 타입을 구현해보셨네요.👍

2023-12-05 12:40 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Error/QueryError.swift
> +enum QueryError: Error, CustomStringConvertible {
QueryError 타입을 구현해보셨네요.👍

2023-12-05 12:40 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/CurrentLocationInfo.swift
> +    var district: String?
`var`로 선언하신 이유가 있을까요?

2023-12-06 01:29 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Model/CurrentLocationInfo.swift
> +    var district: String?
추후에 변경이 생길 것을 고려해서 `var`로 선언하였습니다. 하지만 변경될 요소가 없을 것 같아 `let`으로 수정하였습니다.

2023-12-06 01:33 UTC, bamsak commented on WeatherForecast/WeatherForecast/Utility/CurrentLocationManager.swift
> +    init(locationInfo: CurrentLocationInfo? = nil, networkManager: NetworkManagable) {
xcode에서 자동으로 만들어주는 initializer로 구현 했었는데,
생각해보니 `CurrentLocationManager`가 생성 시점해 locationInfo를 파라미터로 받아 생성할 일이 없을 것 같습니다.
이러한 부분도 꼼꼼하게 생각해보고 구현하도록 하겠습니다!

2023-12-06 01:34 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Utility/LocationManager.swift
> +        switch manager.authorizationStatus {
사용자가 앱의 위치 서비스 사용을 거부하면(denined) `didFailWithError` 메서드는 CLError.Code.denied 오류를 보고하기 때문에 default 케이스로 묶어주는 방식으로 warning 이슈를 해결하고자 했습니다.

2023-12-06 01:51 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Utility/LocationManager.swift
> +    }
이 메서드를 구현하지 않으면 위치 서비스를 사용하려고 할 때 Core Location에서 오류가 발생하기 때문에 임시적으로 구현한 상태였습니다. 
사용자가 앱의 위치 서비스 사용을 거부하면(.denined) 이 메서드는 CLError.Code.denied 오류를 보고하기 때문에 해당 메서드 내에서 .denied 상태일 때 메세지를 출력해주는 기능을 추가하였습니다.

2023-12-06 02:02 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Utility/LocationManager.swift
> +    private(set) var manager: CLLocationManager!
생성 시점에 값을 할당하고자 했는데,
생각해보니 굳이 그럴 필요가 없는 것 같아 선언하면서 바로 값을 할당하는 방식으로 변경하였습니다.

2023-12-06 15:48 UTC, zdodev approved these changes
안녀하세요. @bamsak , @KSK9820 !

프로젝트를 잘 개선해보셨네요!
코멘트에 대해 의견을 달아주신 점도 좋았습니다.👍

스텝 진행하시느라 고생하셨습니다.
Step2는 여기서 마무리할 수 있도록 하겠습니다!

2023-12-06 15:48 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/LocationManager.swift
> +        }
좋습니다👍

2023-12-06 15:48 UTC, merged