[STEP3] JaeHyeok, Beom
tasty-code/ios-weather-forecast pull request #42
Opened 2023-12-12 05:59 UTC by SimJaeHyeok

# 날씨 앱 [STEP3] jaeHyeok, 범

리뷰어 : @jryoun1 (Jake)
안녕하세요 제이크 STEP3 PR 드립니다.

## 구현사항
- Mock URL Session Unit Test 생성
- 앱의 UI를 구현합니다
- 오토레이아웃을 활용하여 코드로만 구현
- Collection View를 활용
- 화면을 위에서 아래로 끌었다 놓으면 정보를 새로고침합니다.
- 날씨 아이콘 추가

## 실행화면
![run](https://github.com/tasty-code/ios-weather-forecast/assets/142188004/05d3c7ce-eea0-415f-894c-c1986aa6a174)
![alert](https://github.com/tasty-code/ios-weather-forecast/assets/142188004/eedec877-562c-4ea5-aba6-6a8ef48cba7c)

## 고민사항
- UICollectionLayoutListConfiguration를 사용할 때 cell하고 header의 크기를 잡으려면 cell과 header의 내부 컨텐츠의 크기를 변경해야 하나요? 
- 위치 허용을 거부했을 때 Refresh를 하게되면 위치 허용을 수락해달라는 알러트를 띄우고 설정 창으로 이동하는 버튼을 만들었습니다.하지만 버튼을 탭 했을 경우 저희 앱의 설정창이 아닌 아이폰 설정창으로 넘어가는데 해당 버튼을 탭했을 때 저희 앱의 설정으로 이동시키는 방법이 있을까요?

2023-12-13 13:52 UTC, jryoun1 requested changes
step3 고생하셨습니다! 

전반적으로 convention에 대해서 신경써보시면 좀 더 가독성이 좋아질 것 같네요!
몇 가지 코멘트 남겨두었습니다. 확인부탁드려요 🙏 

### 질문에 대한 답변
> UICollectionLayoutListConfiguration를 사용할 때 cell하고 header의 크기를 잡으려면 cell과 header의 내부 컨텐츠의 크기를 변경해야 하나요?

질문해주신 내용이 잘 이해가 안 가는데, 좀 더 자세하게 설명해주시면 도움을 드릴 수 있을 것 같네요.
cell, header의 크기는 configuration에서 설정이 되었을 것이고, 그 크기에 맞춰서 내부 컨텐츠들의 레이아웃을 잡아주면 될 것 같은데 어떤 문제가 있을까요? 🙋‍♂️


> 위치 허용을 거부했을 때 Refresh를 하게되면 위치 허용을 수락해달라는 알러트를 띄우고 설정 창으로 이동하는 버튼을 만들었습니다.하지만 버튼을 탭 했을 경우 저희 앱의 설정창이 아닌 아이폰 설정창으로 넘어가는데 해당 버튼을 탭했을 때 저희 앱의 설정으로 이동시키는 방법이 있을까요?

[공식문서](https://developer.apple.com/documentation/uikit/uiapplication/1623042-opensettingsurlstring)를 확인해보면 해당 url이 UIApplication.openSettingsURLString 이 아닌 app의 설정으로 이동할 수 있는 custom deep link를 생성하라고 나와있습니다.
즉 이를 위해서는 해당 앱을 인지할 수 있는 scheme과 이 scheme이 있는 딥링크가 들어왔을 때 처리할 수 있는 코드가 있어야합니다.
이번 프로젝트에서는 크게 벗어나는 것 같아서 설정으로까지만 이동해도 괜찮을 것 같네요.

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Models/Network/NetworkServiceProvider.swift
> +    init(session: URLSessionProtocol) {
mock 으로 테스트하기 위해서 session 자체를 주입받도록 하셨군요! 👏
다만 실제로 app에서는 항상 URLSession.shared를 사용한다면 init에서 default 값을 할당해줘도 될 것 같습니다.
```Swift
init(session: URLSessionProtocol = URLSession.shared) { } 
```

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Models/Network/NetworkServiceProvider.swift
> +final class NetworkServiceProvider: NetworkServiceable {
final 키워드를 사용해보셨군요! 👏 
언제 사용하면 사용하신 이유가 궁금합니다 🙋‍♂️

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Models/Network/WeatherURLConfigration.swift
> +    var parameters: [String : String]?
[Swift dictionary](https://developer.apple.com/documentation/swift/dictionary) 공식문서의 예시를 보시면 [key: value] 이렇게 :를 사이에 양쪽에 space를 사용하지 않고 있습니다!
기본적으로 공식문서나 swift.org 문서의 convention을 따르면 다른 개발자들과 협업할 때 도움이 될 것 같네요 🙏

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
> +    func decoder<T:Decodable>(weatherType: T,data: Data) -> T?{
Generic 조건 뒤에 space가 없습니다! 
또한 함수 매개변수를 연결해주는 , 뒤에도 space가 빠진 것 같아요!
반환값 뒤에도 space가 빠졌습니다 🙏

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
>  }
decode 해주는 함수는 네트워크 모듈에서 가지고 있어야할까요? 🤔 
JSONLoader에도 있는 것 같은데 JSONLoader 객체를 사용하면 되지 않을까요?

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Protocols/URLSessionProtocol.swift
> +extension URLSessionDataTask: URLSessionDataTaskProtocol {}
네트워크 의존성 없이 테스트를 위한 protocol과 기본 구현을 해주셨군요 👏 💯

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/CollectionView.swift
> +final class CollectionView: UICollectionView {
collectionView라는 네이밍은 구체적이지 못한 것 같습니다. 
구체적으로 어떤 collectionView인지 네이밍할 필요가 있어보입니다.

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/CollectionView.swift
> +        super.init(frame: frame,collectionViewLayout: layout)
여기도 , 뒤에 space가 빠졌네요

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    private lazy var weatherCollectionView: CollectionView = CollectionView(frame: .zero, collectionViewLayout: createBasicListLayout())
CollectionView로 따로 view를 분리해서 구현하신 이유가 궁금합니다. 🙋‍♂️

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +class ForecastWeatherCell: UICollectionViewCell {
여기는 final이 없어도 될까요? 🤔

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
horizontalStackView처럼 내부에서 무언가를 선언해주어야하는 것이 아니라면, 
아래처럼 바로 선언해줄 수 있을 것 같은데 위와같이 구현하신 이유가 궁금합니다. 🙋‍♂️
```Swift
let weatherImageView = UIImageView()
```

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
view를 선언함에 있어서 lazy var에 대해서도 공부를 해보시면 좋을 것 같네요! 
- [글1](https://stackoverflow.com/questions/47367454/swift-lazy-var-vs-let-when-creating-views-programmatically-saving-memory) , [글2](https://theswiftdev.com/lazy-initialization-in-swift/), [글3](https://baked-corn.tistory.com/45)

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
내부에 있는 UI 객체들은 외부에서 접근될 일이 있을까요? 🤔

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +        horizontalStackView.translatesAutoresizingMaskIntoConstraints = false
이 코드는 위에서 horizontalStackView를 선언하는 클로저 내에서 선언해줄 수 있을 것 같아요

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +
불필요한 줄바꿈이 있습니다

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +
🚨 여기도 있네요

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +
여기도 다른 곳과는 다르게 줄바꿈이 있네요 🚨
프로젝트 전반적으로 convention에 대해서 신경써보시면 좋을 것 같네요.

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +        }
캡처리스트를 사용해보셨군요 👏 
캡처리스트를 사용하신 이유가 궁금합니다! 
또한 strong 참조가 되는데 문제는 없을까요?

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/HeaderCollectionReusableView.swift
> +    }()
반복되는 것 같은데 이를 함수로 만들 수 있을 것 같습니다.
hint: 함수를 extension을 통해서 구현하면 더 깔끔할수도 있겠네요 👍

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    private lazy var locationManager = CLLocationManager()
lazy var를 사용해보셨군요! 👏 
해당 키워드는 언제 사용하며 왜 사용할까요? 🙋‍♂️

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        print(error.localizedDescription)
지금은 에러에 대한 처리들을 전부 print만 하고 있는데, 이러한 부분은 추후에 개선이 되면 좋겠네요.
해당 print는 개발자가 실제로 디버깅할 때만 보일 것 같네요!

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        }
사용자가 거절을 했음에도 refresh할 때마다 사용자에게 물어보는건 좋지 않은 UX인 것 같네요 🙏

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        networkServiceProvider.fetch(url:imageURL) { (result: Result<Data, NetworkError>) in
: 뒤에 space가 빠졌네요

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        networkServiceProvider.fetch(url:imageURL) { (result: Result<Data, NetworkError>) in
여기도요 🚨

2023-12-13 13:52 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +}
지난번에도 한 번 말씀드렸는데, 위에서부터 코드를 읽을 때 가능하면 사용되는 함수가 먼저 선언되면 가독성이 좀 더 좋을 것 같네요! 
해당 부분에 관련해서는 클린코드라는 책의 `수직 거리`에 대해서 찾아보시면 도움이 될 것 같아요.

2023-12-13 14:01 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        networkServiceProvider.fetch(url:imageURL) { (result: Result<Data, NetworkError>) in
지금은 image의 사이즈가 작아서 빠르게 사진을 받아오지만, 이미지의 사이즈가 커지거나 네트워크 상태가 좋지 않아서 이미지를 다운하는데 오래걸려서 제때 그려주지 못하게 되면 문제가 발생할 것 같은데 해당 방법에 대해서는 어떻게 처리할 수 있을까요? 🙋‍♂️

2023-12-14 00:55 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Models/Network/NetworkServiceProvider.swift
> +    init(session: URLSessionProtocol) {
확인하고 수정하였습니다!

2023-12-14 01:01 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Models/Network/NetworkServiceProvider.swift
> +final class NetworkServiceProvider: NetworkServiceable {
지금 상황에서는 더 이상의 상속이 필요없다고 생각하여 붙였습니다.

2023-12-14 01:06 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Models/Network/WeatherURLConfigration.swift
> +    var parameters: [String : String]?
네 확인하고 수정하였습니다!

2023-12-14 01:11 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
> +    func decoder<T:Decodable>(weatherType: T,data: Data) -> T?{
확인하고 수정하였습니다!

2023-12-14 01:12 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        networkServiceProvider.fetch(url:imageURL) { (result: Result<Data, NetworkError>) in
확인하고 수정하였습니다!

2023-12-14 01:13 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        networkServiceProvider.fetch(url:imageURL) { (result: Result<Data, NetworkError>) in
확인하고 수정하였습니다!

2023-12-14 01:15 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/CollectionView.swift
> +        super.init(frame: frame,collectionViewLayout: layout)
수정하였습니다!

2023-12-14 01:17 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +class ForecastWeatherCell: UICollectionViewCell {
위에 말씀드린 것처럼 범과 함께 생각했을 때 셀을 더 이상 상속할 것 같지 않아서 붙였습니다!

2023-12-14 01:18 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +
저희가 변동사항이 있을 때 주의깊게 컨벤션을 확인못하고 있는 것 같습니다. 코드 작성할 때부터 한줄 한줄 신중하게 작성하겠습니다.

2023-12-14 01:19 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +
수정하였습니다!

2023-12-14 01:22 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +
코드 작성할 때 조금 더 주의 깊게 작성하겠습니다.

2023-12-14 04:34 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Protocols/NetworkServiceable.swift
>  }
말씀 하신대로 기존에 Test 코드에서 사용하던 jsonLoader 파일 가져와서 약간의 수정 후에 두곳에 범용성있게 사용하게끔 수정하였습니다.

2023-12-14 04:40 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/CollectionView.swift
> +final class CollectionView: UICollectionView {
weatherCollectionView로 직관적이게 수정하였습니다.

2023-12-14 04:55 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
바로 위에 위치한 horizontalStackView 처럼 혹시 속성값에 변경이 있을경우 수정을 해주기 위해서 기존의 상태로 만들었습니다. 
속성의 변경이 없다면 바로 선언하는 식으로 만들고 변경이 있을 경우에 수정하는 편이 좋은 것 일까요?

2023-12-14 05:11 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    private lazy var weatherCollectionView: CollectionView = CollectionView(frame: .zero, collectionViewLayout: createBasicListLayout())
기존의 UICollectionView를  쓰는 경우 ViewController에서 identifier등록과 레이아웃 설정 등을 ViewController내부의 함수나 UIcollectionView의 Convenience init을 통해 설정해줘야 한다고 생각해서 따로 파일을 생성했습니다. 
생성을 하고 보니 backgroundView도 view파일을 따로 만들어 주어야 하나 생각을 했지만 정확히 어떤게 옳은지 선택을 못했습니다.
 그래서, view controller이 오로지 view를 controll만 하는 역할인 것인가? view의 레이아웃을 설정하는 것도 view controller의 역할인 것인가?  이런 의문점들이 있습니다.

2023-12-14 05:13 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
말씀하신대로 메서드로 관리하기때문에 접근될 일이 없기 때문에 접근 제어자 private를 붙였습니다!

2023-12-14 05:48 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +}
최대한 흐름에 맞게 배치 하였습니다.

2023-12-14 08:25 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
기존에 알고있던 lazy var의 단점이  thread safe하지 않다는 것 때문에 언제는 사용하고 언제는 사용하지 말아야 하나 생각하고 있었습니다. 글을 읽어보고 이해한 내용은  UI요소는 어차피 main thread에서 초기화를  해야 하기 때문에 lazy var의 단점인 not thread safe를 신경을 안써도 되는 것 인가요??
추가적으로 항상 존재하는 가장 큰 뷰의 경우에는 lazy var로 사용을 하는 것이 let으로 선언하는 것보다 메모리적 이점이 별로 없을까요?

2023-12-14 08:28 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        }
refresh 할 때마다 알러트를 띄운 이유는 유저가 사용하겠다는 의지가 있다는 것으로 생각을 해서 조금더 편하게 위치권한을 수정하라고 알러트를 넣은 것인데 제이크가 주신 조언을 고민하다가 초기화면에서만 알러트를 띄우면 될 것 같아서 허용을 하지 않았을 경우 메인화면에서만 알러트가 등장하게 수정하였습니다.

2023-12-15 02:43 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        networkServiceProvider.fetch(url:imageURL) { (result: Result<Data, NetworkError>) in
memory cache를 통해서 기존에 받아왔던 아이콘의 경우에는 네트워크 통신을 안하고 cache에서 바로 받아올 수 있도록 수정했습니다.

2023-12-15 02:45 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +        horizontalStackView.translatesAutoresizingMaskIntoConstraints = false
넵 알겠습니다.

2023-12-15 06:08 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Models/Network/NetworkServiceProvider.swift
> +final class NetworkServiceProvider: NetworkServiceable {
관련해서는 final 키워드를 사용함으로서 얻는 성능 이점에 대해서도 확인해보시면 좋을 것 같습니다. 

[wwdc16 - Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/)
[reducing dynamic dispatch](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#reducing-dynamic-dispatch)

2023-12-15 06:12 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    private lazy var weatherCollectionView: CollectionView = CollectionView(frame: .zero, collectionViewLayout: createBasicListLayout())
우선 view를 따로 분리해서 관리하는 측면에 대해서 고민해보시면 좋을 것 같아요.
해당 화면에서만 사용하는 view를 굳이 viewController에서 분리해서 선언해놓을 필요가 있을까요? 

만약 해당 view를 AVC, BVC, CVC와 같이 다양한 vc에서 사용한다고 할 때 이때는 view를 따로 분리하지 않는다면 각 VC마다 중복되는 코드가 들어가게 될 것 같습니다. 따라서 주로 이렇게 재사용이 될 수 있는 경우에는 view를 따로 분리해서 생성하는 것 같네요. 이외에도 규칙을 정해놓는다면 그 규칙에 맞춰서 view를 분리할 수도 있을 것 같고요. 

두 분께서도 view를 분리하는데에 있어서 어떤 경우에 분리하는것이 좋은지에 대해서 고민해보시면 좋을 것 같네요.

2023-12-15 06:13 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
넵 변경이 있다면 그때가서 위와 같은 형태로 수정하거나 해도 될 것 같아 보이네요. 🙏

2023-12-15 06:32 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/HeaderCollectionReusableView.swift
> +    }()
extension UILabel을 사용해 함수를 구현해서 반복을 줄였습니다.

2023-12-15 06:33 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +    }()
lazy var를 사용함으로서 항상 보여지지 않는 view의 경우 (예를들어 유저가 버튼을 눌러야지 나타나거나, 펼치기를 눌렀을 때 보여지는 뷰)들의 경우에는 실제로 필요할때 초기화가 되는 것이 메모리적으로 조금 더 이점이 있을 수 있을 것 같네요.
반면 그렇지 않는 경우에는 읽어보신 것 처럼 큰 이점이 없다고 나와있긴하네요! 

또한 기존에 self에 관련된 정보를 넘겨야할 때 코드를 깔끔하게 작성할 수 있는 정도의 장점도 있을 것 같네요.
```Swift
let view: CustomView
func viewDidLoad() {
   view = CustomView(self.frame) 
}

// lazy var를 쓰는 경우
lazy var view = CustomView(self.frame) 
```
모든 UI를 lazy로 선언하라는 의미에서 확인해보라고 말씀드린 것은 아니였고, 한 번 알아보시면 좋을 것 같아서 추천드렸었습니다. 🙏

2023-12-15 06:43 UTC, jryoun1 reviewed
수정해주신 부분 확인했습니다. 👍🏻👏
추가로 코멘트 몇 가지 남겨두었습니다.

2023-12-15 06:43 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Utility/IconCacheManager.swift
> +final class IconCacheManager {
이 캐시매니저는 icon만 caching하는 걸까요? 🤔 
다른 이미지들도 캐싱할 수 있을 것 같아서 좀 더 범용적인 네이밍이 좋을 것 같습니다. 
내부 함수와 파라미터명도 같이 확인해주세요.

2023-12-15 06:43 UTC, jryoun1 commented on WeatherForecast/WeatherForecast/Utility/JsonLoder.swift
> +
줄바꿈이 두 줄있네요.

2023-12-15 06:43 UTC, jryoun1 commented on WeatherForecast/WeatherForecastTests/WeatherForecastTests.swift
> +    }
네트워크 의존성 없이 테스트 코드를 작성해보셨군요 👏💯

2023-12-15 06:43 UTC, jryoun1 commented on WeatherForecast/WeatherForecastTests/WeatherForecastTests.swift
> +
이 공백들은 의도하신 걸까요? 
해당 property들은 왜 여기서 선언되었을까요? 🤔

2023-12-15 06:44 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +    private lazy var locationManager = CLLocationManager()
생성되는 시점에 메모리에 올라가는 키워드로 알고있습니다. 그래서 UI요소는 필요할 때 초기화를 해주면 된다고 생각해서 lazy var로 변경을 하였고 Manger들은 처음부터 필요하다고 생각해서 let으로 선언을 했습니다.

2023-12-15 06:45 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/View/WeatherViewController.swift
> +        print(error.localizedDescription)
알겠습니다 ㅎㅎ

2023-12-15 08:13 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/View/ForecastWeatherCell.swift
> +        horizontalStackView.translatesAutoresizingMaskIntoConstraints = false
수정했습니다!

2023-12-15 08:21 UTC, SimJaeHyeok commented on WeatherForecast/WeatherForecast/Utility/JsonLoder.swift
> +
수정하였습니다!

2023-12-15 08:28 UTC, snowy-summer commented on WeatherForecast/WeatherForecastTests/WeatherForecastTests.swift
> +
step2 pr때 네트워크 통신을 하는 코드로 작성했던 테스트 코드로 분리해서 구분을 하려고 공백을 주었습니다. //MARK: - 로 수정하도록 하겠습니다.

2023-12-15 08:29 UTC, snowy-summer commented on WeatherForecast/WeatherForecast/Utility/IconCacheManager.swift
> +final class IconCacheManager {
CacheManager로 수정을 하였고 다른 이미지들도 캐싱이 가능하도록 파라미터와 함수명을 변경하였습니다.

2023-12-15 09:03 UTC, jryoun1 approved these changes
고생하셨습니다.

2023-12-15 09:24 UTC, snowy-summer commented
질문해주신 내용이 잘 이해가 안 가는데, 좀 더 자세하게 설명해주시면 도움을 드릴 수 있을 것 같네요.
cell, header의 크기는 configuration에서 설정이 되었을 것이고, 그 크기에 맞춰서 내부 컨텐츠들의 레이아웃을 잡아주면 될 것 같은데 어떤 문제가 있을까요? 🙋‍♂️
- 기존의 list를 사용했던 compositional layout에서 cell의 크기가 header와 비슷하여 
- cell의 레이아웃을 변경을 해주었는데 크기가 변경된 상태로 실행은 되지만 콘솔에서 충돌이 일어났다는 오류가 떠있었습니다. 
- 다른 레이아웃의 조건을 살펴보다 이유를 모르겠어서 일단은 list가 없는 layout으로 변경을 했습니다.
- 다시 한번 list로 하고 오토 레이아웃을 다시 잡아볼 예정입니다.

2023-12-16 11:06 UTC, merged