날씨 앱 [STEP3] comdori, 뉴준성
tasty-code/ios-weather-forecast pull request #43
Opened 2023-12-12 06:31 UTC by comdori-wj

# 날씨 앱 [STEP3] comdori, 뉴준성
리뷰어: @forestjae
버드: @comdori-wj, @newJunsung
---

안녕하세요. 숲재! 

날씨 앱 STEP3 구현 완료했습니다.
컬렉션뷰 구현하는데 시간이 오래걸렸습니다. 😔
코드 리뷰 부탁드립니다 🙇🏼‍♂️
### 구현내용

- [x] 오토레이아웃을 활용한 코드로만 구현
- [x] 컬렉션 헤더 뷰 활용
- [x] 컬력션 커스텀 셀 구현
- [x] Refresh Control 활용
- [x] NSCache를 활용한 컬렉션 뷰 셀의 이미지 지연 로딩 문제 해결
- [x] DataFormatter 등을 활용한 날짜 표현

## 스크린샷
![Simulator Screen Recording - iPhone 15 Pro - 2023-12-12 at 15 13 28](https://github.com/tasty-code/ios-weather-forecast/assets/22284092/fd8a25b1-b665-4f06-a9b8-8b7bd8149878)

## 궁금한점
- ViewController의 코드를 보시면 아시겠지만, ViewController에서 너무 많은 역할을 하고 있다고 생각합니다. 이 ViewController에서 뷰를 그리는 역할과 서버로부터 데이터를 뽑아오는 역할을 나누고 싶은데 어떻게 나눠야 할까요?
(제가 생각한 방법은 UIView를 만들고, ViewController에서 뷰를 그리는 코드를 UIView에다 이전 시키는 것입니다.)
- 프레임워크 또는 라이브러리를 여러 파일에다 적용하고 있는데, 저는 이 또한 결합도를 높이는 것이라고 생각합니다(ex. import CoreLocation이 여러 파일에 적용되고 있습니다.). 이 상황에서 만약 다른 라이브러리를 사용해야하는 상황이 온다면(ex. CoreLocation이 더 이상 쓰면 안되는 프레임워크가 됐다고 가정), 여러 파일들을 수정해야 합니다. 라이브러리로 인한 결합도를 어떻게 해야 줄일 수 있을까요?

2023-12-12 16:25 UTC, forestjae requested changes

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Extensions/Date.swift
> +    }
포매터는 스태틱, 메서드는 일반 메서드로 적용하신 이유가 궁금해요

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Extensions/UIViewComponentsConvenienceInitializers.swift
> +}
각각의 익스텐션을 파일 분리하는걸 추천드립니다.

보통 `UIView+Extension` 이런식으로 네이밍합니다.

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +    let icon: String
icon이 String인게 어색한 것 같습니다. 네이밍 고려해주세요!

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Networks/WeatherHTTPClient.swift
> +            .tryMap { (data, httpResponse) in
👍

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Utils/WeatherImageCache.swift
> +            }
이 구문은 어떤 역할을 하나요?

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +class ViewController: UIViewController {
이 클래스는 이름이 왜 ViewController인가요?

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    }()
이런 코드들을 extension으로 분리하시면 코드량을 줄일 수 있습니다.

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    }
```swift
@objc
pirvate func ddd
```

이런식으로 정리하면 깔끔합니다.

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +            }
URL을 여기서 구성하지 말고 다른 곳에서 하면 좀 더 정돈된 코드가 될 것 같습니다.

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    }
sink 블럭 내부의 코드가 너무 많아요. 메서드로 분리 해보세요!

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +        guard let weatherURLRequest = urlManager.configureURLRequest(lat: coordinate.latitude, lon: coordinate.longitude, apiType: .weather) else { return }
guard let 처리는 모아서 최 상단에서 하는게 좋습니다. 그래야 불필요한 작업을 하지 않아요.

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +                let test = CurrentWeatherInfo(address: addressString, icon: current!.weathers.first!.icon, mainInfo: current!.mainInfo)
강제언래핑은 어떤경우에서든 지양해주세요

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    func updateLocationWeather(_ coordinate: CLLocationCoordinate2D, _ addressString: String) {
이 메서드의 역할이 좀 난해한데 어떤 역할을 하는지 설명 부탁드려요~

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/WeatherCollectionViewCell.swift
> +final class WeatherCollectionViewCell: UICollectionViewCell {
커스텀 클래스를 만드셨군요 👍

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/WeatherCollectionViewCell.swift
> +    }
외부에서 사용될 일 없는 메서드에는 private을 붙여주세요

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/WeatherHeaderCollectionViewCell.swift
> +class WeatherHeaderCollectionViewCell: UICollectionReusableView {
헤더를 cell이라고 이름 붙일 필요가 있을까요?

2023-12-12 16:25 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/WeatherHeaderCollectionViewCell.swift
> +    }
접근제어자 체크해주세요

2023-12-12 16:27 UTC, forestjae commented
고생많으셨습니다.

> ## 궁금한점
> * ViewController의 코드를 보시면 아시겠지만, ViewController에서 너무 많은 역할을 하고 있다고 생각합니다. 이 ViewController에서 뷰를 그리는 역할과 서버로부터 데이터를 뽑아오는 역할을 나누고 싶은데 어떻게 나눠야 할까요?

weather 정보를 가져오는 역할을 담당하는 객체를 하나 만들면 뷰컨의 역할이 많이 줄어들 것 같네요.

> * 프레임워크 또는 라이브러리를 여러 파일에다 적용하고 있는데, 저는 이 또한 결합도를 높이는 것이라고 생각합니다(ex. import CoreLocation이 여러 파일에 적용되고 있습니다.). 이 상황에서 만약 다른 라이브러리를 사용해야하는 상황이 온다면(ex. CoreLocation이 더 이상 쓰면 안되는 프레임워크가 됐다고 가정), 여러 파일들을 수정해야 합니다. 라이브러리로 인한 결합도를 어떻게 해야 줄일 수 있을까요?

CoreLocation을 뷰가 그리는데 필요한 정보를 프로퍼티로 가지는 새로운 타입으로 변환하는 단계를 거치게 되면 위와 같은 문제가 해결됩니다.

2023-12-13 02:25 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/WeatherHeaderCollectionViewCell.swift
> +class WeatherHeaderCollectionViewCell: UICollectionReusableView {
### 셀에 대해서 찾아봤는데 보통 셀은 표처럼 쓰였을 때 사용하는거죠?
![image](https://github.com/tasty-code/ios-weather-forecast/assets/22284092/6004aa37-d612-4a6e-8974-54f578668769)

2023-12-13 02:37 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Extensions/UIViewComponentsConvenienceInitializers.swift
> +}
왜 이렇게 네이밍을 하나 찾아보니 과거 옵젝 시절 `ClassName+ExtensionName` 으로 사용한다는 것을 알게 되었습니다.
앞으로도 확장할 일이 생기면 저런식의 네이밍을 따라야겠습니다 ☺️

2023-12-14 01:24 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/WeatherCollectionViewCell.swift
> +    }
네 수정하겠습니다.

2023-12-14 01:28 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/WeatherHeaderCollectionViewCell.swift
> +    }
네 수정하겠습니다.

2023-12-14 04:34 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    }
수정하였습니다.

2023-12-14 06:17 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Extensions/Date.swift
> +    }
`Extensions`은 저장된 속성이 포함된 프로퍼티는 사용할수 없습니다. 따라서 `static`키워드를 붙였고, 일반 메서드를 사용한 이유는 Date를 String으로 형변환 할 수 없기 때문에 적용하였습니다.

더나아가 참고로
```swift
func asFormattedString() -> String {
    let formatter = DateFormatter()
    formatter.locale = Locale(identifier: "ko-KR")
    formatter.dateFormat = "MM/dd(E) HH시"
    return formatter.string(from: self)
}
```
를 사용하면 포매터를 사용할때마다 생성하기 때문에 오버헤드가 발생할 가능성도 있기에 사용하지 않았습니다.

2023-12-14 06:28 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +    let icon: String
`iconID`가 적절해보여서 변경해보았습니다. 마음에 안드신다면 어떤 네이밍이 어울릴까요? 🙃

2023-12-14 07:01 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +        guard let weatherURLRequest = urlManager.configureURLRequest(lat: coordinate.latitude, lon: coordinate.longitude, apiType: .weather) else { return }
네 위로 올리겠습니다.

2023-12-14 07:26 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    func updateLocationWeather(_ coordinate: CLLocationCoordinate2D, _ addressString: String) {
위치가 변경될때마다 현재날씨, 5일치 예보를 받아오는 역할을 하고 있습니다.

2023-12-15 02:30 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +class ViewController: UIViewController {
날씨 앱에 맞게 `WeatherViewController`로 변경하였습니다.

2023-12-15 02:33 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    }()
네 분리하였습니다.

2023-12-15 08:15 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +                let test = CurrentWeatherInfo(address: addressString, icon: current!.weathers.first!.icon, mainInfo: current!.mainInfo)
넵 옵셔널 바인딩 처리 하였습니다.

2023-12-18 01:18 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Utils/WeatherImageCache.swift
> +            }
캐시에 이미지가 저장이 되있다면 비동기적으로 아이콘 이미지를 불러오는 역할을 합니다.

2023-12-18 02:37 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +            }
네 기존에 만든 URL매니저로 옮겼습니다.

2023-12-18 07:14 UTC, comdori-wj commented on WeatherForecast/WeatherForecast/Views/ViewController.swift
> +    }
분리 조치 하였습니다.

2023-12-19 11:54 UTC, forestjae commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +    let icon: String
좋은것 같습니다 :)

2023-12-19 11:56 UTC, forestjae commented on WeatherForecast/WeatherForecast/Views/WeatherHeaderCollectionViewCell.swift
> +class WeatherHeaderCollectionViewCell: UICollectionReusableView {
네 맞습니다~ 일반적으로 UITableViewCell이나 UICollectionViewCell 클래스를 사용하거나 이를 상속받은 클래스를 활용해서 뷰를 만들때만 Cell이라고 이름 붙입니다.

2023-12-19 11:56 UTC, forestjae approved these changes

2023-12-19 11:56 UTC, merged