날씨 앱 [STEP 3] 밤삭, 도라
tasty-code/ios-weather-forecast pull request #46
Opened 2023-12-18 01:42 UTC by bamsak

# 날씨 앱

## 리뷰어
@zdodev

## 팀원:busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/bamsak"><img src="https://avatars.githubusercontent.com/u/114239407?v=4" width="90" height="90"></a> | <a href="https://github.com/KSK9820"><img src="https://avatars.githubusercontent.com/u/68066104?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@bamsak](https://github.com/bamsak) | [@KSK9820](https://github.com/KSK9820) 
| in SeSAC | 밤삭 | 도라

<br/>

## 프로젝트 파일 구조
```
├── AppDelegate.swift
├── Controller
│   └── ViewController.swift
├── Extension
│   ├── Bundle+Extension.swift
│   └── DateFormatter+Extension.swift
├── Model
│   ├── APIDTO
│   │   ├── CommonWeatherDTO.swift
│   │   ├── CurrentWeather.swift
│   │   └── WeeklyWeather.swift
│   ├── CurrentLocationInfo.swift
│   ├── Error
│   │   └── NetworkError.swift
│   ├── HTTP
│   │   └── HTTPMethod.swift
│   └── URL
│       ├── Implementation
│       │   ├── WeatherDataURL.swift
│       │   └── WeatherImageURL.swift
│       └── Interface
│           └── APIBaseURLProtocol.swift
├── SceneDelegate.swift
├── Utility
│   ├── ImageCache
│   │   └── NSCacheMananger.swift
│   ├── Location
│   │   ├── Implemetation
│   │   │   ├── CurrentLocationManager.swift
│   │   │   └── LocationManager.swift
│   │   └── Interface
│   │       ├── CurrentLocationManagable.swift
│   │       └── LocationRequestDelegate.swift
│   ├── Network
│   │   ├── Implementation
│   │   │   └── NetworkManager.swift
│   │   └── Interface
│   │       └── NetworkManagable.swift
│   ├── URLFormat
│   │   ├── Implementation
│   │   │   ├── WeatherImageURLFormatter.swift
│   │   │   └── WeatherURLFormatter.swift
│   │   └── Interface
│   │       └── URLFormattable.swift
│   └── Weather
│       ├── Implementation
│       │   ├── WeatherDataManager.swift
│       │   └── WeatherImageManager.swift
│       └── Interface
│           ├── ImageUpdatable.swift
│           ├── WeatherDataDelegate.swift
│           └── WeatherUpdateDelegate.swift
└── View
    ├── CurrentHeaderView.swift
    ├── MainWeatherView.swift
    ├── Protocol
    │   ├── ReuseIdentifiable.swift
    │   └── UIUpdatable.swift
    └── WeeklyWeatherCell.swift
```
<br/>

## 프로젝트 설명
### 구현 내용

- [x]  `컬렉션 뷰 헤더 뷰의 활용`
- [x]  `컬렉션 뷰 커스텀 셀의 구현`
- [x]  `Refresh Control의 활용`
- [x]  `컬렉션 뷰 셀의 이미지 지연 로딩 문제 해결`
- [x]  `DateFormatter 등을 활용한 날짜 표현`
---
### 각 역할 설명
#### Protocol
- **UIUpdatable**
    - 현재 날씨와 주간 날씨 정보를 받아온 후, UICollectionView에서 업데이트를 하기 위한 프로토콜 정의하였습니다.
- **WeatherUpdateDelegate**
    - 현재 날씨와 주간 날씨 정보를 Request해서 받은 Response를 디코딩하는 프로토콜을 정의하였습니다.
    - 디코딩 후에 UICollectionView를 업데이트하기 위해 `UIUpdateble`의 함수를 Main 스레드에서 호출합니다.
- **WeatherDataDelegate**
    - UICollectionView의 각 Cell에 입력될 데이터를 가공 후 `MainWeatherView`에 넘겨주는 프로토콜 정의하였습니다.
- **WeatherImageDelegate**
    - `NSCacheManager`의 임시 저장소에 해당 이미지 파일이 있는 경우 캐시에 저장된 파일을 사용하고, 없는 경우 API Request하는 프로토콜 정의하였습니다.
---

#### Utility
- **WeatherDataManager**
    - 기존에는 `NetworkManager`와 `ViewController`의 `Delegate`메소드로 네트워크 통신을 했지만, API통신을 하고 날씨 Data를 관리해주는 역할을 해주는 객체로 분리하여 관리하도록 했습니다.
- **WeatherImageManager**
    - `WeatherDataManager`가 받아온 날씨 Data를 기반으로 이미지를 받아와 관리하는 역할을 하는 객체입니다.

- **NSCacheManager**
    - 받아온 이미지를 NSCache를 통해 메모리 캐싱하는 역할을 하는 객체입니다.
    - 캐싱된 이미지를 관리하기 위해 메모리에 해당 객체가 메모리에 존재해있어야 된다 생각하여 싱글톤으로 구현했습니다.
    
---

<br/>

## Trouble Shooting
1. 기존 STEP2에서는 `NetworkManager`가 `URLFormatter`를 가지고 있는 방식에서 각 WeatherData와 Image를 관리해주는 객체로 분리함으로써 각 객체에 그에 따른 `URLFormatter`를 가지게 하도록 변경했습니다.
2. Image를 View에 업데이트하는 방식을 escaping closure로 UIImage를 파라미터로 받는 방식을 통해 업데이트 하는 방식으로 구현했습니다.
 
<br/>
    
## 궁금한 점
- `ViewController`나 각 객체들이 무거워지는 것이 싫어서 최대한 역할분리를 하려고 노력했습니다. 그러다보니 지금은 `ViewController`의 역할이 실질적으로 각 객체들에게 협력이 필요한 객체를 전달해주는 역할만 하게 되었습니다. `ViewController`가 이 역할만을 수행하는 것이 맞는지 맞는건지 잘 모르겠습니다. MVC라고 할 수 있을 까요?
- `WeatherDataManager`가 API통신으로 데이터를 받아오는 역할을 하고 해당 데이터를 가지고 있다보니, View에다가 해당 Data를 Delegate메소드로 전달해주는 역할도 하고 있습니다. 제가 느끼기엔 두가지 역할을 가지고 있는 것 같기도 하고 아닌 것 같기도 하는 느낌이 듭니다.

2023-12-18 16:34 UTC, zdodev requested changes
안녕하세요. @bamsak, @KSK9820 !

Step 3 진행하시느라 고생하셨습니다!

먼저 질문에 대한 제 생각을 적어보았습니다.

- `ViewController`가 Delegate 패턴을 사용해서 뷰와 모델 서로의 참조를 전달만 하고 있어서 현재로서는 지금과 같은 역할만 할 수 밖에 없지 않나 싶습니다. (뷰가 직접 데이터를 요청하고, 네트워크 타입이 뷰에게 데이터를 전달하는 구조가 된 것 같습니다.) 뷰, 컨트롤러, 모델의 역할을 더 명확하게 나누면 좋을 것 같습니다~
- 말씀해주신 것 처럼 `WeatherDataManager` 타입도 두 가지 역할을 동시해 수행하고 있다고 생각이 듭니다!

이외에 현재 앱 실행 시 스크롤이 되지 않거나, 많은 버벅임이 발생하고 있습니다.
해당 이슈를 먼저 수정해볼 수 있을까요?

다른 부분에 대한 코멘트는 따로 적어보았습니다! 
확인 부탁드립니다.

2023-12-18 16:34 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +    private lazy var weatherImageManager = WeatherImageManager(networkManager: networkManager)
`init`을 사용하는 대신 `lazy var` 를 사용하신 이유가 궁금합니다!

2023-12-18 16:34 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/WeeklyWeatherCell.swift
> +    private lazy var cellStack: UIStackView = {
`cellStack` 이라는 이름이 추상적인것 같습니다. 보다 구체적인 이름으로 수정해볼 수 있을까요?

2023-12-18 16:34 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/WeeklyWeatherCell.swift
> +        ])
뷰 추가와 오토레이아웃을 적용할 때 `contentView`를 사용한 뷰와 `Cell 자체뷰`를 같이 사용하신 이유가 있을까요?

2023-12-18 16:34 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/MainWeatherView.swift
> +    }()
`asset backgroundImage warning`이 발생하고 이미지가 출력되지 않습니다. 수정해볼 수 있을까요?

2023-12-18 16:34 UTC, zdodev commented on WeatherForecast/WeatherForecast/Utility/ImageCache/NSCacheMananger.swift
> +final class NSCacheManager {
`NSCache`를 이용해서 캐싱기능을 구현해보셨네요.👍

2023-12-19 11:01 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/View/WeeklyWeatherCell.swift
> +    private lazy var cellStack: UIStackView = {
label과 Image를 갖고 있어 labelImageStack으로 변경하였습니다.

2023-12-19 11:03 UTC, bamsak commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +    private lazy var weatherImageManager = WeatherImageManager(networkManager: networkManager)
`weatherManager`와   `weatherImageManager`가 `NetworkManager`를 각각 다른 인스턴스를 가지기 보단 하나의 인스턴스를 공유하는 게 낫다고 생각이 들었습니다. 그리하여 ViewController에서 `NetworkManager`를 생성하여 주입해주는 방식을 택하였는데, `lazy`키워드를 사용하지 않았을 시 `networkManager`와 생성시점이 동일하여 주입해주지 못하기 때문에 `weatherManager`와   `weatherImageManager`를 사용 시점에 메모리에 올려주는 `lazy`키워드를 사용하여 주입하는 방식을 택했습니다!

2023-12-19 11:03 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/View/WeeklyWeatherCell.swift
> +        ])
custom view들이 contentView에 넣어줘야 하기 때문에, 모든 요소를 가지고 있는 containerView를 contentView에 addSubview 해주었습니다. 그리고 내부에 들어간 요소들의 constraint를 contentView에 설정하였습니다.

2023-12-19 11:04 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/View/MainWeatherView.swift
> +    }()
해당 부분 수정하였습니다. 확인 부탁드립니다 :)

2023-12-19 15:03 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/Implementation/ViewController.swift
> +}
뷰(컬렉션뷰, 셀)에서 데이터를 받아오는 부분을 Delegate를 통해 ViewController로 이동해보셨네요!

2023-12-19 15:03 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +    private lazy var weatherImageManager = WeatherImageManager(networkManager: networkManager)
다음과 같은 코드를 한번 생각해보았습니다!

```swift
init() {
    weatherManager = WeatherDataManager(networkManager: networkManager, currentLocationManager: CurrentLocationManager())
    weatherImageManager = WeatherImageManager(networkManager: networkManager)
    
    super.init(nibName: nil, bundle: nil)
}
```

2023-12-19 15:04 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/MainWeatherView.swift
> +    }()
이미지가 잘 보이고 있습니다!😁

2023-12-19 15:10 UTC, zdodev approved these changes
안녕하세요! @bamsak , @KSK9820 !

Step3 잘 개선해보셨네요!
이전에 발견된 문제는 개선되어 잘 동작하는 것을 확인했습니다!
그리고 뷰, 모델, 컨트롤러 역할을 보다 나눠서 작성하려고 하신 점이 좋았습니다!

코멘트만 확인하고 넘어가면 될 것 같습니다. 고생하셨습니다!

2023-12-19 15:11 UTC, merged