WeatherForecast [STEP 1] d.o., Lust3r
tasty-code/ios-weather-forecast pull request #5
Opened 2023-03-21 08:39 UTC by llimental

안녕하세요! 소대(@zdodev)! 이번 프로젝트를 함께 하게 된 d.o., Lust3r입니다!

이번 Step의 요구사항인 API의 호출 및 데이터 파싱을 처리하기 위해 다방면으로 학습을 했습니다.

많은 고민 끝에 스텝을 완료하게 되었는데, 보시고 이런 점은 추가로 보면 좋을 것 같다 하는 부분 알려주신다면 더 학습해보도록 하겠습니다!

리뷰 잘 부탁드립니다! 감사합니다! 🙇🏻🙇🏻

## 🧑🏼‍💻 작업 목록

**[ STEP 1 ] 모델/네트워킹 타입 구현**

- [x]  [Open Weather Map에서 제공하는 날씨 API](https://openweathermap.org/)의 데이터 형식을 고려하여 모델 타입을 구현
- [x]  앱에서는 현재 날씨를 보여주는 기능과 5일 예보를 보여주는 기능 모두 갖춤
- [x]  API를 통해 전달받은 JSON 데이터를 활용할 수 있도록 모델 타입을 구현
- [x]  [Open Weather Map에서 제공하는 날씨 API](https://openweathermap.org/)의 데이터를 실제로 받아올 수 있는 네트워킹 타입을 구현

## 📚 학습 키워드 및 학습 내용

### 1. CodingKey

> 출처: Apple 공식문서 - CodingKey([https://developer.apple.com/documentation/swift/codingkey](https://developer.apple.com/documentation/swift/codingkey))
> 
- A type that can be used as a key for encoding and decoding.
- 프로젝트에서 사용할 프로퍼티의 이름과 JSON 데이터를 통해 넘어오는 데이터 명이 다르기 때문에 이를 맞춰주기 위해 CodingKey를 사용했습니다

### 2. URLSession

> 출처: swift 공식문서 - URLSession([https://developer.apple.com/documentation/foundation/urlsession](https://developer.apple.com/documentation/foundation/urlsession))
> 
- An object that coordinates a group of related, network data transfer tasks.
- URL 주소로부터 데이터를 다운로드하고 엔드포인트에 데이터를 업로드하기 위한 API를 제공
- API를 사용하여 앱이 실행되고 있지 않을 때 또는 iOS에서 앱이 일시 중단된 동안 백그라운드 다운로드를 수행할 수도 있음
- 이번 프로젝트에서는 API 호출 String을 URL로 URLRequest를 만들고, 이를 가지고 URLSession을 사용하여 JSON 데이터를 받는 작업을 진행했습니다

## 🤔 고민과 해결

### 1.    API 호출 및 데이터 저장 로직 함수화

- 현재 스텝에서 서로 다른 url에 대하여 호출해야 하고, 추후에 추가적인 url 호출이 필요한 경우를 위해 해당 로직을 함수화하여 사용하고자 하였습니다
    - `dataTask()` 에서 `Result Type`을 통해 결과값을 전달합니다
    - 메서드를 사용하는 곳에서 결과값을 저장하는 로직을 작성할 수 있습니다
- 제네릭 함수 정의시 추론이 되지 않는 경우 Type을 파라미터에 작성하여 오류를 피할 수 있다는 것을 알게 되었습니다

**기존코드**

```swift
private func callAPI() {
    guard let currentWeatherBaseURL = URL(string: currentWeatherKey) else { return }
    let weatherURLRequest = URLRequest(url: currentWeatherBaseURL)
        
    let currentWeatherTask = URLSession.shared.dataTask(with: weatherURLRequest) { data, response, error in
        if let data = data {
            do {
                try self.currentWeather = JSONDecoder().decode(CurrentWeather.self, from: data)
            } catch {
                print(error)
            }
        }
    }
    currentWeatherTask.resume()
}
```

**변경코드**

```swift
func dataTask<T: Decodable>(URLRequest: URLRequest, myType: T.Type, completion: @escaping (Result<T,Error>)->()) {
        let myTask = URLSession.shared.dataTask(with: URLRequest) { data, response, error in
            if let data = data {
                guard let decodedData = self.decode(jsonData: data, type: myType) else { return }
                completion(.success(decodedData))
            } else if let error = error {
                completion(.failure(error))
            }
        }
        myTask.resume()
    }
```

### 2. API 호출 키 은닉화

- 바로 API key를 사용하고 push를 하면 키가 공개되기 때문에 은닉화할 방법을 찾아야 했습니다.
- gitignore와 다른 방법을 찾아봤으나 이번에 적용한 방법은 plist를 만들고, 해당 파일의 변경사항을 추적하지 않도록 워크트리에서 제외하였습니다.

### 3. 네트워킹 타입 구현

- 학습 후 기능 구현까지는 오래 걸리지 않았으나 공통적으로 사용하는 코드를 분리하고, 별도의 네트워킹 타입을 구현하는 데에서 많은 어려움이 있었습니다.
긴 고민 끝에 URL 처리를 위한 String 작업을 하는 URLProtocol과 URLSession 작업을 하는 NetworkTaskProtocol을 만들었습니다.
그리고 그 둘을 채택하고, 위도 경도 프로퍼티와 모델 인스턴스를 가지고 API를 호출하는 NetworkManager를 만들어 역할을 위임하였습니다.
이를 통해 ViewController는 NetworkManager 인스턴스만을 가지고 있을 수 있게 되었습니다.

## 🙋🏻 질문 거리

### 1.  프로그램의 구조에 대한 질문

```swift

 ── WeatherForecast
    ├── AppDelegate.swift
    ├── Info.plist
    ├── Model
    │   ├── Forecast.swift
    │   └── Weather.swift
    ├── Network
    │   ├── NetworkManager.swift
    │   └── Protocol
    │       ├── NetworkTaskProtocol.swift
    │       └── OpenWeatherURLProtocol.swift
    ├── SceneDelegate.swift
    ├── ViewController.swift
    ├── WeatherForecast++Bundle.swift
    └── WeatherInfo.plist
```

기존에 ViewController 에 `callAPI()` 를 포함한 모든 저장속성과 메서드가 존재하였는데요
- `NetworkTaskProtocol` : dataTask 로직을 분리
- `OpenWeatherURLProtocol` : url 값 관리 및 URLRequest 에 필요한 URL 제공
- `NetworkManager` : 위의 두 개의 프로토콜을 채택하며, 네트워크 모델 타입의 저장속성을 가집니다. 네트워크 요청 및 데이터 저장의 역할을 가집니다.

ViewController에서 `var netWorkManager: NetworkManager()`  형태로 데이터 통신의 역할을 가지는 객체로 구현하였습니다. ViewController에 코드가 최소한을 존재하도록 역할과 책임을 나누고 고민하였는데요! 혹시 이렇게 구현한 방식이 자연스러운지?? 어색한 부분이 있다면 어떤 부분일까요?? 소대가 보시기에 어떠실까요?

### 2. 모델 구현에 대한 질문

- 처음에 API 데이터를 가지고 어떤 값이 반환되는지 확인한 후 모델을 작성했는데, 커밋을 진행하면서 종종 형식 오류가 발생했습니다.
파싱된 데이터를 보니 처음에 확인했던 형식과는 차이점이 있어서 다시 모델을 작성하였습니다.
그런데 이처럼 API 파싱 데이터가 바뀌게 되면 지금처럼 작은 프로젝트에서는 모델을 바꿔도 큰 영향이 없지만 큰 프로젝트에서는 모델이 변경되면 많은 부분에 영향을 미칠 것이라 생각됩니다.
현업에서는 이렇게 API를 사용할 때 모델을 어떻게 구현하시는지, 그리고 변경사항이 있을 때 어떻게 처리하시는지 궁금합니다!

2023-03-22 12:54 UTC, zdodev requested changes
안녕하세요. @llimental , @doshkor !

Step 1 구현 잘 진행해주셨습니다!
범용성과 유용성에 대해서 많이 고민하신 것 같습니다.👍

질문에 대해 제 생각을 적어보았습니다.

❓ 프로그램의 구조에 대한 질문

- `ViewController` 에서 모든 역할을 수행하는 것보다 지금과 같이 구현한 것이 더 자연스럽다고 생각합니다.👍

❓ 모델 구현에 대한 질문

- 모델은 보통 서버에서 작성, 사용하는 API 문서에 따라 구현합니다. 만약 모델 변경이 생길 경우, 모바일에서도 코드 수정이 불가피할 수 있습니다. 이런 부분은 초기 설계와 커뮤니케이션이 하나의 방법이 될 것 같습니다!

이외에도 몇 가지 궁금증을 남겨보았습니다.
확인 부탁드립니다!

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Forecast.swift
> +}
서버의 파라미터명(단축어, 범용적인 용어 등)을 그대로 사용하기 보다는 이해하기 쉬운 프로퍼티명으로 변경해보는 것은 어떨까요?
다른 구조체도 확인해보면 좋을 것 같습니다.

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Forecast.swift
> +struct City: Codable {
모델 프로퍼티를 정의할 때 `Weather` 는 `Nested` 형태로 정의하고 `Forecast` 의 경우 외부에 정의하신 이유가 궁금합니다!

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Weather.swift
> +    let cod: Int
서버의 파라미터명(단축어, 범용적인 용어 등)을 그대로 사용하기 보다는 이해하기 쉬운 프로퍼티명으로 변경해보는 것은 어떨까요?
다른 구조체도 확인해보면 좋을 것 같습니다.

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/Model/Weather.swift
> +        let sunrise, sunset: Int
한 줄에 여러 프로퍼티를 선언할 때와 하나의 프로퍼티를 선언할 때의 기준이 궁금합니다!

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/Network/NetworkManager.swift
> +    func callAPI() {
현재 날씨와 5일 예보 날씨 요청을 분리해봐도 좋을 것 같습니다!

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/Network/Protocol/NetworkTaskProtocol.swift
> +protocol NetworkTaskProtcol {
`Protocol` 과 `Protocol Extension` 을 잘 구현해보셨네요👍

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/Network/Protocol/OpenWeatherURLProtocol.swift
> +    var lon: Double { get }
단축어보다는 전체이름을 사용하는 것은 어떨까요?

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/ViewController.swift
> +    let networkManager = NetworkManager()
네트워크 통신과 ViewController 의 역할을 잘 나누었다고 생각합니다!

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/ViewController.swift
> +class ViewController: UIViewController{
오타가 있는 것 같습니다!

2023-03-22 12:54 UTC, zdodev commented on WeatherForecast/WeatherForecast/WeatherForecast++Bundle.swift
> +        guard let key = resource["API_KEY"] as? String else { fatalError("WeatherInfo.plist에 API_KEY설정을 해주세요.") }
`fatalError` 과 같이 강제종료 방식으로 에러처리를 한 이유가 있을까요?

2023-03-23 02:43 UTC, doshkor commented on WeatherForecast/WeatherForecast/Model/Forecast.swift
> +}
`Enum CodingKeys: String, CodingKey {}` 이용하여 프로퍼티명을 보다 명확하게 변경하였습니다..!

해당 커밋: 85cd18c

2023-03-23 02:43 UTC, doshkor commented on WeatherForecast/WeatherForecast/Model/Weather.swift
> +    let cod: Int
`Enum CodingKeys: String, CodingKey {}` 이용하여 프로퍼티명을 보다 명확하게 변경하였습니다..!

해당 커밋: 85cd18c

2023-03-23 02:43 UTC, doshkor commented on WeatherForecast/WeatherForecast/Model/Forecast.swift
> +struct City: Codable {
수정하였습니다👍

2023-03-23 02:49 UTC, llimental commented on WeatherForecast/WeatherForecast/Model/Weather.swift
> +        let sunrise, sunset: Int
같은 타입의 프로퍼티는 묶어서 선언하도록 수정하였습니다!🙌🏻

해당 커밋: 65d0879

2023-03-23 06:04 UTC, llimental commented on WeatherForecast/WeatherForecast/Network/Protocol/NetworkTaskProtocol.swift
> +protocol NetworkTaskProtcol {
감사합니다!

2023-03-23 06:06 UTC, llimental commented on WeatherForecast/WeatherForecast/Network/Protocol/OpenWeatherURLProtocol.swift
> +    var lon: Double { get }
모델 구조체 수정하면서 프로퍼티명도 좀 더 가독성 있게 변경해보았습니다!

해당 커밋: 85cd18c

2023-03-23 06:07 UTC, llimental commented on WeatherForecast/WeatherForecast/ViewController.swift
> +    let networkManager = NetworkManager()
감사합니다!

2023-03-23 06:12 UTC, doshkor commented on WeatherForecast/WeatherForecast/Network/NetworkManager.swift
> +    func callAPI() {
`callWeatherAPI()`, `callForecastAPI()` 함수로 분리했습니다.!

해당 커밋: 23a6b63

2023-03-23 06:15 UTC, llimental commented on WeatherForecast/WeatherForecast/Network/Protocol/OpenWeatherURLProtocol.swift
> +    var lon: Double { get }
해당 프로퍼티명 명확하게 변경했습니다!

해당 커밋: ad90bee

2023-03-24 07:18 UTC, llimental commented on WeatherForecast/WeatherForecast/ViewController.swift
> +class ViewController: UIViewController{
수정했습니다 감사합니다

2023-03-24 07:21 UTC, llimental commented on WeatherForecast/WeatherForecast/WeatherForecast++Bundle.swift
> +        guard let key = resource["API_KEY"] as? String else { fatalError("WeatherInfo.plist에 API_KEY설정을 해주세요.") }
API Key를 숨기는 과정에서 예제 코드를 그대로 사용했던 것 같습니다.
NetworkError 구현하면서 API 관련 에러를 사용하도록 변경했습니다!

해당 커밋: d240e06

2023-03-24 16:02 UTC, zdodev approved these changes
안녕하세요. @llimental , @doshkor !

코드를 잘 개선해보셨네요! 좋습니다👍

Step 1 진행하시느라 고생하셨습니다!🎉

2023-03-24 16:02 UTC, zdodev commented on WeatherForecast/WeatherForecast/Network/NetworkManager.swift
> +    private func callWeatherAPI()  {
접근제어 처리를 잘 적용해보셨네요!👍

2023-03-24 16:02 UTC, zdodev commented on WeatherForecast/WeatherForecast/WeatherForecast++Bundle.swift
> +        guard let resource = NSDictionary(contentsOfFile: file) else { throw NetworkError.apiResource }
강제 종료 방식을 개선해보셨네요!👍

2023-03-24 16:02 UTC, zdodev commented on WeatherForecast/WeatherForecast/Network/NetworkManager.swift
> +        callForecastAPI()
요청 API 를 잘 분리해보셨네요!👍

2023-03-24 16:02 UTC, merged