날씨 앱 [STEP 4] 밤삭, 도라
tasty-code/ios-weather-forecast pull request #50
Opened 2023-12-21 02:28 UTC by bamsak

# 날씨 앱

## 리뷰어
@zdodev

## 팀원
| 프로필 사진 | <a href="https://github.com/bamsak"><img src="https://avatars.githubusercontent.com/u/114239407?v=4" width="90" height="90"></a> | <a href="https://github.com/KSK9820"><img src="https://avatars.githubusercontent.com/u/68066104?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@bamsak](https://github.com/bamsak) | [@KSK9820](https://github.com/KSK9820) 
| in SeSAC | 밤삭 | 도라

<br/>

## 프로젝트 파일 구조
```
├── AppDelegate.swift
├── Controller
│   └── ViewController.swift
├── Extension
│   ├── Bundle+Extension.swift
│   └── DateFormatter+Extension.swift
├── Model
│   ├── APIDTO
│   │   ├── CommonWeatherDTO.swift
│   │   ├── CurrentWeather.swift
│   │   └── WeeklyWeather.swift
│   ├── CurrentLocationInfo.swift
│   ├── Error
│   │   └── NetworkError.swift
│   ├── HTTP
│   │   └── HTTPMethod.swift
│   └── URL
│       ├── Implementation
│       │   ├── WeatherDataURL.swift
│       │   └── WeatherImageURL.swift
│       └── Interface
│           └── APIBaseURLProtocol.swift
├── SceneDelegate.swift
├── Utility
│   ├── ImageCache
│   │   └── NSCacheMananger.swift
│   ├── Location
│   │   ├── Implemetation
│   │   │   ├── CurrentLocationManager.swift
│   │   │   └── LocationManager.swift
│   │   └── Interface
│   │       ├── CurrentLocationManagable.swift
│   │       └── LocationRequestDelegate.swift
│   ├── Network
│   │   ├── Implementation
│   │   │   └── NetworkManager.swift
│   │   └── Interface
│   │       └── NetworkManagable.swift
│   ├── URLFormat
│   │   ├── Implementation
│   │   │   ├── WeatherImageURLFormatter.swift
│   │   │   └── WeatherURLFormatter.swift
│   │   └── Interface
│   │       └── URLFormattable.swift
│   └── Weather
│       ├── Implementation
│       │   ├── WeatherDataManager.swift
│       │   └── WeatherImageManager.swift
│       └── Interface
│           ├── ImageUpdatable.swift
│           ├── WeatherDataDelegate.swift
│           └── WeatherUpdateDelegate.swift
└── View
    ├── CurrentHeaderView.swift
    ├── MainWeatherView.swift
    ├── Protocol
    │   ├── ReuseIdentifiable.swift
    │   └── UIUpdatable.swift
    └── WeeklyWeatherCell.swift
```
<br/>

## 프로젝트 설명
### 구현 내용

- [x]  `UIAlertController를 통한 필드 입력받기`
- [x]  `동적인 매개변수(parameter) 대응을 위한 네트워킹 타입 구현`

---
### 각 역할 설명
#### Protocol
- **AlertDelegate**
    - `Alert`를 띄우는 프로토콜을 정의하였습니다.
    - 해당 프로토콜을 `ViewController`에서 채택하여 `Alert`를 띄우는 메서드를 구현하였으며, Button이 있는 `MainWeatherView`에서 해당 프로토콜을 delegate로 받아 메서드를 사용합니다.
---

#### 구현영상
![weather2](https://github.com/tasty-code/ios-weather-forecast/assets/114239407/494b6d47-4931-4ae1-ba29-f7f2dee55ba3)

2023-12-21 16:29 UTC, zdodev requested changes
안녕하세요! @bamsak , @KSK9820 !

Step4 진행 잘해주셨습니다!
사용자 입력에 따라 날씨를 잘 표시해줍니다!
간단하게 잘 구현해보셨네요👍

간단한 코멘트를 남겨보았습니다🙂

2023-12-21 16:29 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/Implementation/ViewController.swift
> +    func showLocationSettingAlert() {
`UIAlertController`를 잘 구현해보셨네요.👍

2023-12-21 16:29 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/Implementation/ViewController.swift
> +            guard let latitude = alert.textFields?[0].text, let longitude = alert.textFields?[1].text else { return }
뷰컨트롤러에 `location`을 가져온 이유가 있을까요? `locationManager`에 처리를 맡기는 것은 어떨까요?

2023-12-21 16:29 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/Interface/AlertDelegate.swift
> +protocol AlertDelegate: AnyObject {
`AlertDelegate`로 이름을 지으신 이유가 궁금합니다!

2023-12-21 16:29 UTC, zdodev commented on WeatherForecast/WeatherForecast/View/CurrentHeaderView.swift
> +    }
Delegate 패턴으로 이벤트를 전달해보셨네요.👍

2023-12-22 02:16 UTC, KSK9820 commented on WeatherForecast/WeatherForecast/Controller/Interface/AlertDelegate.swift
> +protocol AlertDelegate: AnyObject {
Alert를 표시한다는 의미에서 AlertPresentable로 변경하였습니다.

2023-12-22 02:17 UTC, bamsak commented on WeatherForecast/WeatherForecast/Controller/Implementation/ViewController.swift
> +            guard let latitude = alert.textFields?[0].text, let longitude = alert.textFields?[1].text else { return }
locationManager내부에서 CLLocation으로 변환하여 Request보내는 작업으로 변경했습니다!

2023-12-22 15:00 UTC, zdodev approved these changes
안녕하세요. @bamsak , @KSK9820 !

Step4 개선을 잘 진행해보셨네요!
각 스텝별로 고민의 흔적이 정말 많이 보였던 프로젝트였습니다!
지금까지 날씨앱 잘 진행해주셨습니다!👍👍
고생하셨습니다!

2023-12-22 15:00 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/Implementation/ViewController.swift
> +            self?.locationManager.changeLocation(latitude: latitude, longitude: longitude)
`location` 처리를 잘 넘겨보셨네요!👍

2023-12-22 15:00 UTC, zdodev commented on WeatherForecast/WeatherForecast/Controller/Interface/AlertPresentable.swift
> +protocol AlertPresentable: AnyObject {
`AlertPresentable`도 괜찮습니다!👍

2023-12-22 15:00 UTC, merged