날씨 앱 [STEP4] Mango, 쫑
tasty-code/ios-weather-forecast pull request #51
Opened 2023-12-21 10:13 UTC by shlim0

# 날씨 앱 

## 리뷰어
@jungseungyeo

## 팀원:busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/Dongjun-developer"><img src="https://avatars.githubusercontent.com/u/97822621?v=4" width="90" height="90"></a> | <a href="https://github.com/shlim0"><img src="https://avatars.githubusercontent.com/u/46235301?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@DongJun](https://github.com/ehdwns0814) | [@JJong](https://github.com/shlim0) 
| in SeSAC | 망고 | 쫑

## 파일구조:file_folder:
```
WeatherForecast
├── Enums
│   ├── ImageAPI.swift
│   └── WeatherAPI.swift
├── Errors
│   ├── APIError.swift
│   ├── LocationError.swift
│   ├── NetworkError.swift
│   ├── WeatherForecastCellError.swift
│   └── WeatherForecastHeaderViewError.swift
├── Extensions
│   ├── CLLocationDegrees+Extension.swift
│   ├── DateFormatter+Extension.swift
│   ├── Model+Extension.swift
│   ├── ModelCurrentWeather+Extension.swift
│   ├── ModelFiveDaysWeather+Extension.swift
│   └── UIImageView+Extension.swift
├── Models
│   └── Model.swift
├── Protocols
│   ├── Cacheable.swift
│   ├── KeyAuthenticatable.swift
│   ├── Networkable.swift
│   ├── RequestDataTaskable.swift
│   ├── RequestSessionable.swift
│   └── Requestable.swift
├── Utilities
│   ├── CacheManager.swift
│   ├── LocationManager.swift
│   ├── Locator.swift
│   ├── NetworkManager.swift
│   └── Networker.swift
├── ViewControllers
│   └── WeatherForecastViewController.swift
└── Views
    ├── WeatherForecastCell.swift
    ├── WeatherForecastHeaderView.swift
    └── WeatherForecastView.swift
```

## 프로젝트 설명

`CoreLocation` 프레임워크를 통해 현재 위치를 가져온 뒤, 해당 위치를 기반으로 날씨 정보를 가져옵니다.
- 현재 위치를 기반으로 날씨앱이 날씨 정보를 가져옵니다.

## 실행 화면 스크린샷
<img width="996" alt="image" src="https://github.com/tasty-code/ios-weather-forecast/assets/46235301/11ee47dd-a9dc-401d-a2e3-d21c74493e75">

<img width="400" alt="image" src="https://github.com/tasty-code/ios-weather-forecast/assets/46235301/5d92261c-f67c-4533-b149-1294835a75dc
">

![currentLocationButton](https://github.com/tasty-code/ios-weather-forecast/assets/46235301/90f02534-7253-46f2-a286-a974fc32065d)

![locationChangerefresh](https://github.com/tasty-code/ios-weather-forecast/assets/46235301/0380150b-7296-4a76-b3f0-74167233d90c)

### 변경사항 
- `NSCache`를 사용해 이미지 캐싱을 구현했습니다.
- 사용자가 특정 위치를 입력해 이에 대한 날씨 정보를 가져옵니다.
    - refresh시 현재 위치에 대한 날씨 정보를 가져옵니다. 저희 나름의 정책으로, 특정 위치에 날씨 정보를 refresh를 하는 방향과 현재 위치에 대한 날씨 정보를 refresh를 계속해서 하는 방향 중 후자로 선택했습니다. 사용자 입장에서 테스트 용도로 잠깐 특정 위치에 대한 날씨 정보를 확인하고 refresh시 현재 위치를 가져오는 게 더 나은 방향이라 판단했습니다.
- `group.leave()`시 날씨앱이 crash 나는 버그를 수정했습니다.
    - `DispatchGroup`을 함수 내부에서 사용할 때, `completion`이 끝나고 다시 `completion`에 진입할 때 바뀌지 않아서 생기는 문제였습니다.
    
        ```swift
        func request(coordinate: CLLocationCoordinate2D?, completion: @escaping LocationCompletion){

            locationCompletion = completion
            coordinate == nil ? manager.requestLocation() : fetchPlacemark(for: coordinate)
        //  locationCompletion = completion  // 기존 코드 위치
        }
        ```

### 궁금한점 / 고민하는 점

2023-12-21 23:58 UTC, jungseungyeo requested changes
쫑, 망고 고생하셨습니다.

디스코드에서 많은 이야기하는 거 처럼 기능 구현의 대해서 잘 구현을 하였지만 객체의 역할, 부여, 의존성등을 고려하는 모습에서 힘들어 하는 모습을 보았습니다.

이러한 부분을 개선하고 적용하면 좋을거같아 글보다는 디스코드로 이야기를 전달드렸습니다. 추후에 Object 책을 읽고 객체가 무엇이고 역할을 어떻게 부여하면 좋은지 참고해보시면 좋을거같아요. 

고생하였습니다.

2023-12-21 23:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Protocols/Cacheable.swift
> +    func store(with imageID: String, image: UIImage)
어제 디코에서 이야기한거처럼 역할을 부여하고 하나의 기능을 사용하는것을 추천드립니다.

2023-12-21 23:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +        coordinate == nil ? manager.requestLocation() : fetchPlacemark(for: coordinate)
어제 이야기한거처럼 빌드, 코드점핑등 코드 흐름과 역할을 주고 기능으로 POP구조를 가능하다면 적용하면 좋겠습니다. :)

2023-12-21 23:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +            completion(.success((location.coordinate, address)))
placemarks 값이 두번 오는 경우가 있어 크래시가 나고 있어요. 크래시가 발생하지 않게 수정하고 적용하면 좋겠습니다. 적용할떄 completeion이 한번만 콜백을 주게 하면 될거같아요. 

어제는 한번만 사용하고 nil 처리 하게 임시로 적용하였는데요. 좋은 방법은 아니나 시간상 그렇게 해결해도 될거같아요.

2023-12-21 23:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/ViewControllers/WeatherForecastViewController.swift
> +    private func configureWeatherData() {
이 함수가 매우 massive한 느낌입니다. 그 이유는 어제 디코에서 이야기 한 내용인데요. DispatchGroup을 잘 사용하지 못하는 느낌과 requestData함수의 콜백으로 다음 값을 진행하면 좋을거같아요.

2023-12-21 23:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/ViewControllers/WeatherForecastViewController.swift
> +    private func requestData(group: DispatchGroup) {
DispatchGroup을 의존하지 않고 넘겨주면 좋을거같아요.

2023-12-21 23:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/ViewControllers/WeatherForecastViewController.swift
> +        group.wait()
어제 디코에서 이야기한 내용입니다. 이것도 DispatchGroup를 의존하지 않는 함수로 적용하면 좋겠습니다.

2023-12-21 23:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Views/WeatherForecastCell.swift
> +            }
이미지 처리의 대해서 어제 디코에서 이야기 한 내용처럼 역할을 주고 시키는 코드를 작성하면 좋겠습니다.

2023-12-22 07:17 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Protocols/Cacheable.swift
> +    func store(with imageID: String, image: UIImage)
OOP - `묻지 말고 시켜라(TDA 원칙)`을 만족하지 않았던 문제를 해결했습니다.

`UIImageView+extension.swift` 내부에서 이미지를 불러올 때 cache 이미지를 가져올 지, 네트워킹을 통해 이미지를 가져올지 결정하도록 하였습니다.

```swift
import UIKit

extension UIImageView {
    static func load(from imageType: String, completion: @escaping (UIImage) -> Void) {
        let networkManager: NetworkManagerable = NetworkManager()
        
        if let image = CacheManager.shared.loadImage(with: imageType) {
            completion(image)
        } else {
            networkManager.fetchImage(request: ImageAPI(imageType: imageType)) { (result: Result<UIImage, NetworkError>) in

                switch result {
                case .success(let image):
                    DispatchQueue.main.async {
                        completion(image)
                    }
                case .failure(let error):
                    print(error)
                }
            }
        }
    }
}
```

따라서, `WeatherForecastCell`과 `WeatherForecastHeaderView`에서 다음과 같이 더욱 편리하게 사용할 수 있게 되었습니다.
```swift
UIImageView.load(from: imageType) { image in
     configure()
}
```

2023-12-22 07:17 UTC, ehdwns0814 commented on WeatherForecast/WeatherForecast/Views/WeatherForecastCell.swift
> +            }
```swift
UIImageView.load(from: imageType) { [weak self] image in
            guard let self = self else { return }
            configure(image: image, date: dateString, temperatureCurrent: temperatureCurrent)
}
```
`load` 메서드 내에서 분기 처리를 해주었습니다.

```swift
extension UIImageView {
    static func load(from imageType: String, completion: @escaping (UIImage) -> Void) {
        let networkManager: NetworkManagerable = NetworkManager()
        
        if let image = CacheManager.shared.loadImage(with: imageType) {
            completion(image)
        } else {
            networkManager.fetchImage(request: ImageAPI(imageType: imageType)) { (result: Result<UIImage, NetworkError>) in
                switch result {
                case .success(let image):
                    DispatchQueue.main.async {
                        completion(image)
                    }
                case .failure(let error):
                    print(error)
                }
            }
        }
    }
}

```

2023-12-22 07:22 UTC, shlim0 commented on WeatherForecast/WeatherForecast/ViewControllers/WeatherForecastViewController.swift
> +    private func configureWeatherData() {
불필요하게 `DispatchGroup`이 전달되었다는 느낌에 저희도 동의합니다. 또한, 불필요하게 `DispatchQueue`가 남발된 느낌이 있었는데요. 각 기능마다 함수로 분리하여 callback(completion)하도록 하였습니다. 이전보다 더 나은 코드 흐름을 구성했습니다.

```swift
   func configureWeatherData() {
        let group = DispatchGroup()
        
        group.enter()
        fetchLocationData {
            group.leave()
        }
        
        group.notify(queue: .global(qos: .userInteractive)) { [weak self] in
            guard let self = self else { return }
            guard let coordinate = coordinate else { return }
            
            group.enter()
            fetchCurrentWeatherData(coordinate: coordinate) {
                group.leave()
            }
            
            group.enter()
            fetchFiveDaysWeatherData(coordinate: coordinate) {
                group.leave()
            }
            
            group.wait()
            fetchUI()
        }
    }
```

```swift
extension WeatherForecastViewController: Locatable {
    func fetchLocationData(completion: @escaping () -> Void) {
        requestData(coordinate: coordinate) { [weak self] coordinate, placemark in
            self?.coordinate = coordinate
            self?.placemark = placemark
            completion()
        }
    }
}

extension WeatherForecastViewController: Networkable {
    private func fetchCurrentWeatherData(coordinate: CLLocationCoordinate2D, completion: @escaping () -> Void) {
        fetchWeatherData(request: WeatherAPI.current(coordinate)) { (result: Model.CurrentWeather) in
            self.currentWeathermodel = result
            completion()
        }
    }
    
    private func fetchFiveDaysWeatherData(coordinate: CLLocationCoordinate2D, completion: @escaping () -> Void) {
        fetchWeatherData(request: WeatherAPI.fiveDays(coordinate)) { (result: Model.FiveDaysWeather) in
            self.fiveDaysWeatherModel = result
            completion()
        }
    }
}
```

2023-12-22 07:23 UTC, shlim0 commented on WeatherForecast/WeatherForecast/ViewControllers/WeatherForecastViewController.swift
> +        group.wait()
https://github.com/tasty-code/ios-weather-forecast/pull/51#discussion_r1434792924 를 참고해주세요!

2023-12-22 07:23 UTC, shlim0 commented on WeatherForecast/WeatherForecast/ViewControllers/WeatherForecastViewController.swift
> +    private func requestData(group: DispatchGroup) {
https://github.com/tasty-code/ios-weather-forecast/pull/51#discussion_r1434792924 를 참고해주세요!

2023-12-22 07:27 UTC, ehdwns0814 commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +            completion(.success((location.coordinate, address)))
```swift
extension LocationManager: CLLocationManagerDelegate {
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        guard let coordinate = manager.location?.coordinate else {
            locationCompletion?(.failure(LocationError.noLocationError))
            return
        }
        
        manager.stopUpdatingLocation()
        fetchPlacemark(for: coordinate)
    }
```
completion = nil 처리 후에 
stopUpdatingLocation()처리 해주었습니다.

2023-12-22 07:37 UTC, shlim0 commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +        coordinate == nil ? manager.requestLocation() : fetchPlacemark(for: coordinate)
기존 구조는 `VC` <-> `Locator` <-> `LocationManager` (및 `VC` <-> `Networker` <-> `NetworkManager`) 간 코드 점핑을 하는 구조였습니다. 역할을 분리하고자 하는 것은 좋지만, depth가 깊어지는 느낌을 지울수가 없었는데요.

중간 계층인 `Locator`를 삭제하고 `Locatable`을 추가했습니다. 또, `Locatable`내부에서 `LocationManagerable` 인스턴스를 통해 사용할 수 있도록 `VC`에서 `LocationManager` 인스턴스를 만들게 하였습니다.
(`Networker`와 `NetworkManagerable`도 동일)

```swift
// WeatherForecastViewController.swift
final class WeatherForecastViewController: UIViewController {
    let locationManager: LocationManagerable = LocationManager()
    let networkManager: NetworkManagerable = NetworkManager()
```
```swift
// WeatherForecastViewController.swift
extension WeatherForecastViewController: Locatable {
    func fetchLocationData(completion: @escaping () -> Void) {
        requestData(coordinate: coordinate) { [weak self] coordinate, placemark in
            self?.coordinate = coordinate
            self?.placemark = placemark
            completion()
        }
    }
}
```
```swift
// Locatable.swift
protocol Locatable: AnyObject {
    var locationManager: LocationManagerable { get }

    func requestData(coordinate: CLLocationCoordinate2D?,completion: @escaping (CLLocationCoordinate2D, CLPlacemark) -> Void)
}

extension Locatable {
    func requestData(coordinate: CLLocationCoordinate2D?,completion: @escaping (CLLocationCoordinate2D, CLPlacemark) -> Void) {

        locationManager.request(coordinate: coordinate) { result in
            switch result {
            case .success((let coordinate, let placemark)):
                completion(coordinate, placemark)
            case .failure(let error):
                print(error)
            }
        }
    }
}
```swift
protocol LocationManagerable {
    func request(coordinate: CLLocationCoordinate2D?, completion: @escaping LocationCompletion)
}

extension LocationManagerable {
    func request(coordinate: CLLocationCoordinate2D?, completion: @escaping LocationCompletion) { }
}

final class LocationManager: NSObject, LocationManagerable { ... }
```

2023-12-22 10:24 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/ViewControllers/WeatherForecastViewController.swift
> +    private func configureWeatherData() {
좋습니다 :)

2023-12-22 10:26 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Views/WeatherForecastCell.swift
> +            }
좋습니다. ㅎㅎ 

더 좋은 방법으로 `(completion: @escaping (UIImage) -> Void)` 을 넘겨주지 말고 `self.image = image` 로 외부에 알려주지 않아도 될거같아요 ㅎㅎ

2023-12-22 10:26 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Utilities/LocationManager.swift
> +        coordinate == nil ? manager.requestLocation() : fetchPlacemark(for: coordinate)
어제 이야기 한 거 처럼 잘 적용되었네요 ㅎㅎ 좋습니다.

2023-12-22 10:28 UTC, jungseungyeo approved these changes
고생하셨습니다. 

이번 프로젝트에서 이야기한 protocol을 활용하는 방법을 앞으로도 잘 적용하였으면 좋겠습니다.
고생하셨습니다.

2023-12-22 10:28 UTC, merged