WeatherForecast [STEP2] Mason, Logan
tasty-code/ios-weather-forecast pull request #7
Opened 2023-03-22 08:37 UTC by sloDevz

> 안녕하세요 라자냐~! 😆(@wonhee009) 최강 Team Melo의 Mason과 Logan입니다.!! 이번 스탭의 요구사항이 저번 스탭에 비해 큰 발전은 없었기 때문에 생각보다 어렵지 않게 스탭을 마무리 지을 수 있었습니다. 단지 Clean Architecture 를 감안하여 설계하는 과정에서 생각보다 난해한 부분이 많았기 때문에 앞으로도 많은 공부가 필요하구나 생각했던 스탭이었습니다. 그럼 이번 리뷰도 잘 부탁드려요!🤗
> 

# ✅ 요구사항 & 체크리스트

- [x]  현재 위치의 위도와 경도를 알아냅니다.
- [x]  위도와 경도를 활용해 현재 위치의 주소를 알아냅니다.
- [x]  현재 위치의 날씨와 현재 위치의 5일 예보를 날씨 `API`를 통해 데이터를 요청하고 받아오는 기능을 구현합니다.

# **⁉️ 고민과 해결**

### 1️⃣ LocationManager를 관리하는 객체 분리

- 사용자의 위치를 받아오는 기능에 대해서는 날씨 앱 특성상 사용자의 위치를 계속해서 업데이트 할 필요는 없다 생각하여 필요할 때만 위치를 받아오는 것으로 구현 했습니다.
- 공식문서 참고하여 스스로 `locationManager`의 `delegate`를 처리하는 `LocationDataManager`를 만들어서 구현했습니다.
    
    > [https://developer.apple.com/documentation/corelocation/configuring_your_app_to_use_location_services](https://developer.apple.com/documentation/corelocation/configuring_your_app_to_use_location_services)
    > 
- 구현 초기엔 `fetchLocation` 후에 델리게이트 방식으로 넘어오는 데이터를 다시 VC로 넘기는 과정에서 `completionHandler` 로 `closure` 를 할당하여 처리하는 식으로 구현했었습니다.
    
    ```swift
    // 구현 초기 -> CompletionHandler 로 처리
    final class LocationDataManager: NSObject, CLLocationManagerDelegate {
    		let locationManager = CLLocationManager()
        private var locationUpdateCompletion: ((CLLocation) -> Void)?
    
    		// completion을 할당하고 위치를 요청함
    		func requestLocation(completion: @escaping (CLLocation?) -> Void) {
            locationUpdateCompletion = completion
            locationManager.requestLocation()
        }
    
    		// 완료된 후, completion에 넘기고 nil을 할당해서 해제해줌
    		func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
            guard let location = locations.last else { return }
            locationUpdateCompletion?(location)
            locationUpdateCompletion = nil
        }
    
    // ViewController
    class ViewController: UIViewController {
    		// 호출 시...
    		locationDataManager.requestLocation { [weak self] location in
    				self?.location = location
        }
    ```
    
    > 이렇게 메모리 누수를 방지하기 위해 `didUpdateLocations` 로 결과값이 넘어온 뒤, `completion`에 nil을 할당해주었습니다.
    > 
- 하지만 사용자 위치 권한 설정도 동일한 로직으로 작성할 때 문제가 발생했는데, 
사용자 권한에 대한 delegate 메서드는 프로그램이 시작되고 얼마 지나지 않아 알아서 불리는 메서드의 특징을 지니기 때문에 `completion` 이 바로 nil이 되는 현상이 발생했습니다.
    
    > flag 를 두거나, 시간을 체크하는 등 여러 우회방법이 있긴 하겠지만 본질적인 해결이 아니라 생각했습니다.
    > 
- 고민끝에 해당 LocationDataManager의 delegate를 설정하자는 판단을 하게 되었습니다.
- `CLLocationManager` 객체의 delegate를 처리하는 LocationDataManager의 delegate를 설정하는 것이 비효율적인게 아닌가 라는 생각이 들었지만, 
내부 처리를 추상화하여 원하는 데이터만 뷰컨트롤러로 넘길 수 있다는 데서 장점이 있다고 판단했기에 진행 해 보았습니다.
- 어느정도 스탭을 마무리 하는 단계에서 주소를 받아오는 `geoCoder`의 역할도 `LocationDataManager` 에게 맡기기 적합하다고 생각해서 해당 기능도 `LocationDataManager`에게 부여했습니다.
    
    > `LocationDataManager` → 위치를 관리함, `CLGeocoder` → 위치에 따른 주소를 받아옴
    > 
    - `geoCoder` 의 역할을 `LocationDataManger`가 함꼐 맡게한 것에 대하여 어떻게 생각하는지 궁금해요!

### 2️⃣ OSLog 활용

- 지금까지는 `error`와 여러가지 출력확인을 `print`로만 처리해줬었는데 이번 스탭에서는 OSLog 를 처음 학습해서 사용해봤습니다. 애플이 권장하는 로깅 방식이고, 나중에 검색할 수 있게 장치에 보관된다는 장점을 가지고 있다고 하여 앞으로도 적극 활용해볼 예정입니다.
- OSLog 의 메시지로는 `StaticString` 만을 허용하기 때문에 swift의 string interpolation 으로는 메시지를 작성할 수 없다고 하여 우회하는 방식으로 Objective-C의 string interpolation 방식인 `“%@”`을 사용하여 출력하도록 구현하였습니다.
- `os_log()` 를 해줄 때 마다 매번 위의 코드를 작성해주는 것이 비효율적이라 생각해서, 전역 함수로 정의하고 전역 함수를 `LogUtil` 이라는 파일 내부에 넣어주었는데 보통 현업에서는 어떤식으로 사용하시는지 궁금합니다.
    
    > Google Analytics.. 같은
    > 
    
    ```swift
    func log(_ log: OSLog, error: Error) {
        os_log(.error, log: log, "%@", error.localizedDescription)
    }
    ```
    

## 궁금한 점

> URLSession에서 HTTP메서드는 왜 String인지 궁금합니다.
> 
- 해당 HTTP메서드의 항목들을 저희는 Enum으로 한정지어서 입력할 수 있도록 구현했습니다.
- 문득 들었던 생각이 어째서 `URLRequest`의 `httpMethod` 프로퍼티를 `Enum`으로 하지 않고 `String`으로 했을까라는 의문이 생겼습니다.
- 나름대로 알아 본 결과는 혹시모를 앞으로의 변화에 대응하는 경우 (ex 항목이 추가될 수 있는 경우) 
`String`으로 처리하는 경우가 많다는 것을 알게되었습니다.
- 하지만 9개의 HTTP메서드가 추가되는 경우는 없을 것 같아 충분히 설명이 되지 않는 느낌이었습니다.
- “그냥 애플이 그렇게 만들었으니까~” 라고 생각할 수도 있지만, 라자냐의 개인적인 의견이 궁금했습니다!
(아주 중요한 부분은 아니지만… 단순한 호기심에 질문드렸습니다!)

2023-03-23 00:16 UTC, wonhee009 requested changes
수고하셨습니다. 코멘트 남겨두었으니 확인 부탁드려요.

HTTPMethod에 대해 생각해본적은 없는데.... 말씀해주신 부분도 일리가 있네요.
`하지만 9개의 HTTP메서드가 추가되는 경우는 없을 것 같아 ` 사실 이 부분은 아무도 장담할 수 없지 않을까요?
또한, 서비스를 개발할때도 어디까지 확장될지 예상하기 어려워 버전 대응을 위해 enum을 정의할때 unknown과 같은 타입을 정의할 때도 있습니다.
(이후 스펙 변화로 인해 response에 새로운 값이 추가되고 이 값을 구버전에서는 어떤 enum type인지 알 수 없음을 대비하기 위해)

2023-03-23 00:16 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Networking/Service/Interface/ServiceProtocol.swift
>  protocol ServiceProtocol {
`ServiceProtocol`은 어떤 역할을 하는 친구로써 네이밍된걸까요?
내부 메서드의 역할을 봐서는 해당 프로토콜은 네트워크 관련한 역할만 갖을 수 있을거 같아 `ServiceProtocol`이라는 네이밍이 너무 제네럴하지 않나 싶습니다.

2023-03-23 00:16 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +        }
guard문에는 early exit의 의미도 있어 해당 위치에서의 guard문 사용이 조금 어색한거 같습니다.
guard문이 상단에 위치하면 안되는 로직일까요?

2023-03-23 00:16 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +        fetchLocation()
`fetchLocation()`을 viewDidLoad에서도 호출하고 있는데 viewDidLoad에서는 허용에 대한 조건문이 없는거 같습니다.
없어도 되는건가요?

2023-03-23 00:16 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Manager/LocationDataManager.swift
> +final class LocationDataManager: NSObject, CLLocationManagerDelegate {
`Data`는 어떤 의미로 붙은 네이밍인가요?

2023-03-23 00:16 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Manager/LocationDataManager.swift
> +    private let geocoder = CLGeocoder()
geoCoder의 역할도 여기보다는 따로 분리하는게 낫지 않을까 생각합니다.
해당 구조체와 geoCoder의 역할이 다르다고 생각하거든요.

2023-03-23 00:16 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Util/LogUtil.swift
> +import OSLog
현업에서는 로그 (크래시 로그 등등)를 개발자만 보지 않고 기획/운영 등에서 함께 확인하는 경우가 생기기 때문에 (서버에서 볼 때도 있고요...) 좀 더 접근하기 편한 Firebase 등등을 활용하는 편입니다.

2023-03-23 06:57 UTC, sloDevz commented on WeatherForecast/WeatherForecast/Util/LogUtil.swift
> +import OSLog
감사합니다!

2023-03-23 06:57 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Networking/Service/Interface/ServiceProtocol.swift
>  protocol ServiceProtocol {
Service의 역할이 Networking 으로 한정될 것 같아서, 굳이 protocol 추상화를 하지 않아도 된다고 판단하였고,
protocol 을 삭제 해 주었습니다 :)

> 해당 커밋: f0b5358

2023-03-23 06:58 UTC, sloDevz commented on WeatherForecast/WeatherForecast/Manager/LocationDataManager.swift
> +    private let geocoder = CLGeocoder()
geoCoder역할을 `AddressManager` 라는 개체로 분리했습니다~

2023-03-23 06:58 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +        }
guard가 상단에 위치하게 되면 delegate 설정이 되지 않고 early-exit 이 되어 하단에 위치 해 주었는데,
guard문의 early exit 성격을 고려했을 때, "만약 권한이 없으면 -> 권한을 요청한다" 라는 if 문으로 처리하는 것이 의미적으로도 더 적합하다 판단하여 if문으로 수정하였습니다.

> 해당 커밋: 87464dc

2023-03-23 07:08 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Manager/LocationDataManager.swift
> +final class LocationDataManager: NSObject, CLLocationManagerDelegate {
공식문서의 예시 코드를 보고 가져온 네이밍이었는데, 곰곰히 생각 해 보니 현재는 로케이션 "데이터" 매니저의 역할을 하고 있진 않은 것 같았습니다.
받아온 location를 Coordinate로 변환 해 주는 작업이 종종 일어나는데, 이것을 해당 `LocationDataManager` 가 해준다면 좋을 것 같다고 판단해서 리팩터링 했고, 네이밍도 적절해보였습니다.

> 해당 커밋: 7fd4ae1

2023-03-24 01:30 UTC, qwerty3345 commented on WeatherForecast/WeatherForecast/Controller/ViewController.swift
> +        fetchLocation()
`didAuthorized`가 매번 불리기 때문에, 
fetchLocation을 viewDidLoad에서 호출하는 것이 불필요하다 판단되어 삭제하였습니다.

2023-03-24 03:05 UTC, wonhee009 approved these changes
수고하셨습니다~ 다음 스텝 진행 부탁드려요.

2023-03-24 03:05 UTC, merged