날씨 앱 [STEP 1, 2] iyeah, Avery
tasty-code/ios-weather-forecast pull request #9
Opened 2023-03-23 08:00 UTC by iyeahh

> 안녕하세요 콘 ! (@protocorn93)
날씨 앱 (무려 5주)을 함께하게 된 iyeah, Avery예요!
요즘 따뜻한 봄 날씨 만끽하고 계신가요~? 🌷
저희는 미리 말씀드렸듯 Step 1, 2를 함께 구현하여 PR 보내드려요.
부족하겠지만 열심히 공부하며 콘의 리뷰와 함께 성장하고 싶어요!
잘 부탁드려요 감사해요 🫡

## ☝🏻 STEP 1: 모델/네트워킹 타입 구현

- [x] Open Weather Map에서 제공하는 날씨 API의 데이터 형식을 고려하여 모델 타입을 구현해요.
- [x] 앱에서는 현재 날씨를 보여주는 기능과 5일 예보를 보여주는 기능 모두 갖추고 있어요.
    - https://api.openweathermap.org/data/2.5/weather
    - https://api.openweathermap.org/data/2.5/forecast
- [x] API를 통해 전달받은 JSON 데이터를 활용할 수 있도록 모델 타입을 구현해요.
    - 날씨 정보를 받아오는 포멧은 JSON을 사용해요.
    - 날씨 정보는 위도/경도를 사용하여 받아와요.
    - CodingKeys 프로토콜을 활용해요.
- [x] Open Weather Map에서 제공하는 날씨 API의 데이터를 실제로 받아올 수 있는 네트워킹 타입을 URLSession을 활용해서 구현해요.

## ✌🏻 STEP 2: 위치정보 확인 및 날씨 API 호출

- [x] CoreLocation을 활용하여 현재 위치의 위도와 경도를 알아내요.
- [x] CoreLocation과 위도,경도를 활용하여 현재 위치의 주소를 알아내요.
- [x] 현재 위치의 날씨와 현재 위치의 5일 예보를 날씨 API와 URLSession을 통해 데이터를 요청하고 받아오는 기능을 구현해요.
    - 전달받은 JSON 데이터 파싱 및 모델에 매칭해요.
    - HTTP GET 메서드를 명시적으로 호출해요.

## 🐶 PR Point
### 1️⃣　API 호출 키 은닉화

이번 프로젝트로 서버 연결을 처음 진행해보았어요. 그런데 날씨 Open API를 사용하기 위해서는 개인 키를 발급받아서 쿼리 파라미터로 넣어줘야 했는데 이때 저희의 개인 키를 숨기기 위해서 `gitignore`에 활용하기로 했어요. 😊

현재 날씨앱 프로젝트 파일 구조는 이렇게 생겼어요. 우리는 Network 레이어에 `SecretKey.swift` 파일을 `gitignore`에 추가해서 git에서 추적되지 않도록 했어요.
```
├── Application
│   ├── AppDelegate.swift
│   └── SceneDelegate.swift
├── Assets.xcassets
│   ├── AccentColor.colorset
│   │   └── Contents.json
│   ├── AppIcon.appiconset
│   │   └── Contents.json
│   └── Contents.json
├── Base.lproj
│   ├── LaunchScreen.storyboard
│   └── Main.storyboard
├── Info.plist
├── Model
│   ├── Coordinate.swift
│   ├── Forecast.swift
│   └── Weather.swift
├── Network
│   ├── NetworkConfig.swift
│   ├── NetworkError.swift
│   ├── NetworkService.swift
│   └── SecretKey.swift
└── View
    └── ViewController.swift
```

`SecretKey` 파일은 구조체로 만들었고, static 변수로 선언해서 appId에 접근할 수 있도록 했어요.

```swift
struct SecretKey {
    static let appId = "abcde12345"
}
```

이 방법 외에도 github에 API Key 숨기는 여러 방법에 대해 알아보았지만, 가장 간편한 방식이라고 생각하여 이 방식으로 진행했어요.
콘은 평소에 이 방식에 대해 어떻게 생각하시는지 궁금해요~!

### 2️⃣ SwiftLint 적용
이번 프로젝트에서 외부 라이브러리를 사용할 수 없지만 유일하게 허용된 것이 바로 `SwiftLint` 였어요.
저희는 컨밴션을 맞추기 위해 적용했고, 적절히 커스텀하여 사용했어요. 😇

```
excluded:
- WeatherForecast/Application/AppDelegate.swift
- WeatherForecast/Application/SceneDelegate.swift
- WeatherForecastUITests
- WeatherForecastTests

disabled_rules:
- trailing_whitespace

identifier_name:
  excluded:
    - dt
    - id
```

특히 위와 같이 `AppDelegate`와 `SceneDelegate`같은 경우 현재 추가로 코드를 작성해서 사용하고 있지는 않지만 다음 스탭에서 사용할 수 있기 때문에 기본주석을 지우는 것보다는 `SwitLint` 룰 적용 제외하는 것이 더 나을 것 같다고 판단하였어요.

`SwitLint`를 적용하면서 아래와 같은 코드 수정을 진행해보았어요.

`코드 변경 전`
![](https://i.imgur.com/0iT0AxX.png)

![](https://i.imgur.com/OgAAuQQ.png)

날씨 네트워크 연결 코드에요.
한 줄에 120자 넘게 작성하여 Line Length 경고가 뜨고 있어요. 

`코드 변경 후`
![](https://i.imgur.com/yHcDStM.png)

![](https://i.imgur.com/vlZumuV.png)

에러를 없애기 위해 여러 방식으로 코드를 변경할 수 있지만 저희는 함수 호출시 넘기는 `Coordinate` 파라미터가 중복적으로 등장한다고 생각했고, 앞에 라벨을 생략하기 위해 `_`를 추가하는 방식으로 변경했어요!

## 🙋🏻‍♀️ 질문 사항
### 확장성 있는 코드에 대한 고민

API를 호출하는 함수 구현 시 날씨 API에 국한되지 않고 어느 API도 통신할 수 있는 확장성 있는 코드를 구현에 대해 고민했어요.
현재는`Coordinate`를 파라미터로 받아 제한된 코드가 구현되지 않았나 싶어요.
`httpMethod`를 switch문으로 다양한 메서드를 분기처리하는 것도 고민해보았는데 아직은 요구사항에 `HTTP GET 메서드 명시적 호출`로 적혀 있어 진행하진 않았어요.
🤔 고민해서 최대한 리팩토링을 해봤는데 확장성을 넓히려면 어떻게 수정하면 좋을지 조언 부탁드려요!

<br>

2023-03-24 09:49 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 

## 코멘트 

뷰컨트롤러를 최대한 멍청하게 만들어보시는건 어떨까요? 비즈니스 로직은 별도의 객체가 담당하도록 구조를 생각해보시면 좋을 것 같아요.

## 질문 사항

1. gitignore를 활용해볼 수도 있어요. 다만 이는 로컬에서만 혼자서만 작업할 때는 용이하겠지만, 다른 동료들이 각자의 장비로 작업한다면 그 파일을 공유하는 방법에 대해서도 고민이 필요하겠네요.  물론 저장소 자체를 `private`으로 전환해도 괜찮구요.

2. 확장성 있는 코드에 대해 고민해주시고 계신데, 가장 좋은 것은 계층(layer)를 잘 나누는 것이에요. 현재 네트워킹 코드를 보면 코어로직에 도메인이 묻어있어요. 확장이 어렵고 유지보수도 쉽지 않을거에요. 네트워킹 코드는 오직 네트워크와 관련된 코드만 위치해야해요. (기본적인 요청, 에러처리, 등) 

[이 글](https://malcolmkmd.medium.com/writing-network-layer-in-swift-protocol-oriented-approach-4fa40ef1f908)을 한번 읽어보시면 감이 오실 수 있어요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Model/Coordinate.swift
> +    let lon, lat: Double?
개인적으론 개행으로 구분해주는게 가독성에 더 좋다고 생각해요

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Model/Forecast.swift
> +    let city: City
`Forecast` 뿐만아니라 현재 모델들을 보면 네트워킹 DTO를 비즈니스 로직이나 화면을 그리는데그대로 사용되는거롤 보여지는데요. 

DTO와 도메인 모델, 뷰모델을 분리할게 아니라면 변수명을 보고도 역할을 바로 알 수 있도록 변수명 수정이 필요해보여요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Model/Weather.swift
> +struct Sys: Decodable {
모델명만 보았을 땐 `Sys`가 어떤걸 의미하는지 모르겠어요

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Network/NetworkService.swift
> +    static let shared = NetworkService()
`NetworkService`를 싱글톤으로 구현한 이유가 있을까요? 싱글톤일 필요가 없어보이는데 말이죠!🤔

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Network/NetworkService.swift
> +    func fetchForecastAPI(_ coordinate: Coordinate, completion: @escaping APICompletion<Forecast>)
`-API`는 붙여주지 않아도 될 것 같아요! `APICompletion`도 마찬가지로 `API-`를 붙여주지 않아도 될 것 같아요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Network/NetworkService.swift
> +    }
`URLRequest` 객체를 활용하면 query parameters를 구성해보시면 좋을 것 같아요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Network/NetworkService.swift
> +    }
`Double` `extension`으로 `fileprivate`으로 구현해도 좋을 것 같네요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/View/ViewController.swift
> +final class ViewController: UIViewController {
뷰 컨트롤러의 의존성을 생성 시점에 주입해줄 수 있으면 좋을 것 같아요. 스토리보드를 사용하면서도 생성 시점에 의존성을 주입해줄 수 있는 방법이 있는데, 찾아보시고 적용해보시면 좋을 것 같아요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/View/ViewController.swift
> +    private let locationManager = CLLocationManager()
애플이 제공하는 구현체임에도 불구하고 보통 한번 wrapping을 해주곤해요. 물론 때에 따라 오버엔지니어링이 될 수도 있기 때문에 잘 선택해주시면 되지만 학습의 관점에선 괜찮은 것 같아요. 대표적으론 `URLSession`이 될 수 있을 것 같은데요. 

`URLSession`을 쓰다가 `Alamofire`를 쓰기로 의사결정이 되었을 때 어떻게 하면 기존 코드에 수정을 최소화하면서 바꿔 사용할 수 있을까에 대해서 고민해보시는거죠. 

이를 여기에 대입해보면 `ViewController.swift`에서 `import CoreLocation`을 제거해볼 수 있을까에 대해서도 한번 고민해보시면 이후에 많은 도움이 될 수 있을 것 같아요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/View/ViewController.swift
> +        NetworkService.shared.fetchWeatherAPI(Coordinate(lon: coordinate.lon, lat: coordinate.lat)) { result in
`NetworkService`도 외부에서 주입해줄 수 있으면 좋을 것 같네요.

2023-03-24 09:49 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/View/ViewController.swift
> +final class ViewController: UIViewController {
1. scene delegate에서 programatically하게 화면 구성하기 [링크](https://pavankataria.medium.com/how-to-programmatically-setup-your-app-with-scene-delegate-in-swift-b0aab1949b)
2. [instantiateInitialViewController(creator:)](https://developer.apple.com/documentation/uikit/uistoryboard/3213988-instantiateinitialviewcontroller)

2023-04-03 12:29 UTC, devxsby commented on WeatherForecast/WeatherForecast/View/ViewController.swift
> +final class ViewController: UIViewController {
저희가 다음 스탭에서 스토리보드를 사용하지 않고 코드 베이스로 뷰를 짜기 때문에 스토리보드는 제거했어요~!
좋은 공부 소스 주셔서 감사해요 🌟 👍🏻

2023-04-03 13:58 UTC, devxsby commented
@protocorn93 
> 콘 안녕하세요 ~! 🐶🌟
리뷰 남겨주신 것 잘 봤어요 !! 너무 잘 남겨주셔서 감사합니다 ㅎㅎ 덕분에 또 많이 배웠어요!!!
우선 저번에 따로 말씀 드린 것처럼 이번 풀리퀘에 mvvm+clean architecture 구조로 리팩하는 것을 진행해봤어요.
우선 코멘트 남겨주신 것에 대해 크게 바뀐 리팩사항에 대해 간단히 말씀드릴게요!

### 1. 클린아키텍처를 반영하여 계층(layer)을 갖도록 개편했어요.
<img width="376" alt="스크린샷 2023-04-03 21 21 58" src="https://user-images.githubusercontent.com/80062632/229507777-d021322b-3ee2-423f-afdd-bfd31a59884d.png">

![image](https://user-images.githubusercontent.com/80062632/229534753-398815a2-3b21-439b-8303-f52b43c1f12a.png)

[참고 프로젝트](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM)를 보면서 각 레이어의 역할을 이렇게 구성했어요.
- Domain Layer = Entities + Use Cases + Repositories Interfaces
- Data Repositories Layer = Repositories Implementations + API (Network) + Persistence DB
- Presentation Layer (MVVM) = ViewModels + Views

데이터 바인딩은 클로저와 컴플리션 핸들러를 사용했어요.

3 layer(data, domain, presentaion)외에 core와 application을 가져요.
특히 application의 DIContainer에서 뷰 생성에 관한 의존성을 주입해주고 있어요.
```swift
final class DIContainer {
    
    func makeWeatherForecastVC() -> WeatherForecastViewController {
        let service = NetworkService()
        let repository = WeatherForecastRepository(service: service)
        let usecase = WeatherForecastUseCase(repository: repository)
        let viewmodel = WeatherForecastViewModel(usecase: usecase)
        let weatherForecastVC = WeatherForecastViewController()
        weatherForecastVC.viewModel = viewmodel
        return weatherForecastVC
    }
}
```
아키텍처 적용에 관한 부분은 아직 학습 중이라 리뷰 받을 부분이 더 많을 것으로 기대돼요!! 편하게 의견주세요. 😊🚀

### 2. 뷰컨트롤러에서 import CoreLocation를 하지 않도록 `CoreLocationManager`를 만들었어요.

뷰 컨트롤러에서 위도, 경도 정보에 대한 정보를 알 필요 없이 뷰 모델에서 도메인 레이어에 있는 `CoreLocationManager`객체를 갖도록 했어요.
`CoreLocationManager`는 킬로미터 단위로 변경 시 현재 위치의 위도, 경도를 알려줘요.
그런데 `CoreLocationManager`를 어느 레이어에 둘 지 잘 모르겠는데 이 부분에 관해서 콘의 견해가 궁금해요 !!! 🤔

```swift
import Foundation

import CoreLocation

// MARK: - Protocols

protocol LocationUpdateProtocol: AnyObject {
    func locationDidUpdateToLocation(location: CLLocation)
}

final class CoreLocationManager: NSObject {
        
    private let locationManager = CLLocationManager()
    
    weak var delegate: LocationUpdateProtocol?
    
    override init() {
        super.init()
        self.setUpLocationManager()
    }
}

// MARK: - Methods

extension CoreLocationManager {
    private func setUpLocationManager() {
        locationManager.delegate = self
        locationManager.desiredAccuracy = kCLLocationAccuracyKilometer
        locationManager.requestWhenInUseAuthorization()
        locationManager.startUpdatingLocation()
    }
}

// MARK: - CLLocationManagerDelegate

extension CoreLocationManager: CLLocationManagerDelegate {
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        guard let currentLocation = locations.last else { return }
        delegate?.locationDidUpdateToLocation(location: currentLocation)
    }
    
    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
        print("Location update failed with error: \(error.localizedDescription)")
    }
}

```

2023-04-04 02:04 UTC, protocorn93 reviewed
전체적인 앱 구조를 변경하는게 쉬운 작업은 아닌데, 두 분 모두 고생하셨어요! 학습하고 노력하신 흔적이 보여서 좋네요! 

다만 아키텍처에는 정답은 없다는걸 아시면 좋겠어요. 회사, 팀 그리고 서비스 및 기능마다 상황이 다르기 때문에 학습한 아키텍처가 지향하는 바가 무엇인지를 잘 이해하는 것이 중요해요. 

단순히 모양을 따라하는 것이 아키텍처는 아니기에 공부하고 적용하면서 "이게 정말 여기서 적절한걸까?" 계속 따져보고 고민해보면서 자신의 생각을 정리해보는 연습을 해보시면 좋을 것 같아요.

--- 

## 질문 사항

> 그런데 CoreLocationManager를 어느 레이어에 둘 지 잘 모르겠는데 이 부분에 관해서 콘의 견해가 궁금해요 !!!

어떤 계층이라기보단 특정 역할을 수행하는 객체인데요. 서비스 객체로 보시고 적절하게 디렉토리 구조만 잘 정의해주시면 될 것 같아요. 

보통 이런 서비스 객체는 usecase 혹은 상위 레벨의 객체가 의존할 수 있는 객체라고 생각되요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Application/DIContainer/DIContainer.swift
> +        weatherForecastVC.viewModel = viewmodel
뷰컨트롤러 의존성도 생성자를 통해 주입해보시면 좋을 것 같아요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Data/DTO/ForecastResponseDTO.swift
> +    }
하위 타입들을 inner type으로 구현한 이유가 있을까요~?

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Data/DTO/ForecastResponseDTO.swift
> +    }
`Coord`를 포함해서 몇몇 DTO는 `WeatherResponseDTO`에서도 함께 사용되는데 단독 DTO 모델로 빼는게 어떨까 싶어요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Data/Network/Service/NetworkService.swift
> +}
네트워크 레벨에선 도메인(`WeatherResponseDTO` etc)을 몰라야 할 것 같아요. `Decodable`한 제네릭 타입을 반환할 수 있으면 좋을 것 같네요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Interfaces/Repositories/WeatherForecastRepositoryInterface.swift
> +}
Repository가 Entity를 알기보단, DTO를 전달하고 좀 더 상위 계층에서 적절하게 Entity로 변환해서 사용하는게 좋을 것 같아요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Entities/ForecastEntity.swift
> +}
Entity가 `Decodable`을 따를 필요가 있을까요?

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Data/Repositories/WeatherForecastRepository.swift
> +                print(error.localizedDescription)
에러도 completion handler로 전달되어 에러 처리가 들어가면 좋을 것 같아요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Entities/ForecastEntity.swift
왠만하면 개별 파일로 분리해주시는게 좋아요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Usecases/CoreLocationManager.swift
> +    func locationDidUpdateToLocation(location: CLLocation)
CLLocation도 한번 감싸면 좋을 것 같아요. 공식 문서를 보면 

```swift
typealias CLLocationDegrees = Double
```

이기 때문에 

```swift 
struct Location { 
  let latitude: Double 
  let longitude: Double
}
```

위 객체를 사용하면 CoreLocation 노출은 완전히 제거할 수 있을 것 같아요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Usecases/CoreLocationManager.swift
> +protocol LocationUpdateProtocol: AnyObject {
프로토콜 네이밍은 위임의 성격이 강하기 때문에 `-Delegate` 가 되면 좋을 것 같아요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Usecases/CoreLocationManager.swift
> +        print("Location update failed with error: \(error.localizedDescription)")
에러 전달 인터페이스도 프로토콜에 추가되면 좋을 것 같아요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Usecases/WeatherForecastUseCase.swift
> +final class WeatherForecastUseCase {
UseCase도 추상화가 되면 좋겠네요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Domain/Usecases/WeatherForecastUseCase.swift
> +    }
UseCase는 한 가지의 명확한 비즈니스 로직을 하는게 좋아요. 현재는 Repository와 크게 다른게 없어보여요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Presentation/MainScene/ViewModel/WeatherForecastViewModel.swift
> +    private let usecase: WeatherForecastUseCase
UseCase의 사용이 필수는 아니라고 생각해요. 현재는 하는 역할이 Repository와 다르다고 생각하진 않아요. DTO > Entity로의 변환은 ViewModel에서 해도 무방해보여요. 

현재 단계에선 뷰모델이 Repository를 직접 의존하고 있어도 무방해보여요.

2023-04-04 02:04 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Presentation/MainScene/ViewModel/WeatherForecastViewModel.swift
> +    var loadForecastEntity: ((ForecastEntity) -> Void)!
강제 언랩핑은 지양해주세요

2023-04-04 06:46 UTC, devxsby commented on WeatherForecast/WeatherForecast/Data/DTO/ForecastResponseDTO.swift
> +    }
원래 의도는 하위 타입을 inner type으로 나타냄으로 `WeatherResponseDTO`와 `ForecastResponseDTO`에 있는 dto임을 명확히 하고자 했어요.
하나의 dto는 서버에서 보내주는 형식 그대로를 나타내고 싶어서 반복되는 dto와 상관없이 inner type으로 나타냈어요 🤔
하지만 각각의 익스텐션으로 하위 타입을 가져서 동일한 DTO를 보일러 플레이트 코드로 만들어버리기 때무에 삭제를 할 수 있다고 생각했어요!
따라서 밑에 달아주신 코멘트와 같이 반영해서 [b103a2b 커밋에 수정사항](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/b103a2b9c46de357f598e0159061271d8e226b50)에 반영했어요!! 🍀

2023-04-04 06:52 UTC, devxsby commented on WeatherForecast/WeatherForecast/Domain/Entities/ForecastEntity.swift
> +}
이 부분은 제 실수네요! Entity가 Decodable을 따를 필요 없습니당! ㅎㅎ [e143d43](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/e143d43ce270634636c1c4f9419f97d3c59056f5)에 수정해서 반영했어요~! 감사해요!

2023-04-04 07:21 UTC, devxsby commented on WeatherForecast/WeatherForecast/Domain/Entities/ForecastEntity.swift
엔티티와 dto 파일 모두 개별 파일로 분리했어요.
> 반영 커밋:  [1d3f91d](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/1d3f91d01c44db310b3eaa3b756876de516695a7)

2023-04-04 07:25 UTC, devxsby commented on WeatherForecast/WeatherForecast/Domain/Usecases/CoreLocationManager.swift
> +protocol LocationUpdateProtocol: AnyObject {
그렇네요!! 프로토콜 네이밍에 관해 어려웠는데 피드백 감사해요 😊 
> 반영 커밋: [1d3f91d](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/1d3f91d01c44db310b3eaa3b756876de516695a7)

2023-04-04 07:39 UTC, devxsby commented on WeatherForecast/WeatherForecast/Domain/Usecases/CoreLocationManager.swift
> +    func locationDidUpdateToLocation(location: CLLocation)
좋은 의견 감사해요!! 👍🏻
타입 축약형인건 인지하고 있었는데 이거를 저희만의 `Location`이라는 새로운 타입을 사용하는 것과 다른 분들이 봤을 때 `CLLocation` 타입을 명시하고 사용하는게 더 알아보기 좋다고 생각했어요.
그런데 콘이 말씀하신대로 수정하면 뷰모델에서 CoreLocation 노출을 제거할 수 있어 더 옳은 방향인 것 같아요!
리뷰 반영해서 수정할게요 ~!! 
> 반영 커밋: [8bea444](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/8bea44476f1a1e4e22f3297872ddb346a4be6e37)

2023-04-04 08:07 UTC, devxsby commented on WeatherForecast/WeatherForecast/Presentation/MainScene/ViewModel/WeatherForecastViewModel.swift
> +    var loadForecastEntity: ((ForecastEntity) -> Void)!
넵 유의하겠습니다!!
> 반영커밋: [6194483](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/61944836577c3498d37e460128158e85a2c81dca)

2023-04-05 00:51 UTC, devxsby commented on WeatherForecast/WeatherForecast/Domain/Usecases/WeatherForecastUseCase.swift
> +final class WeatherForecastUseCase {
네! 프로토콜로 Usecase 추상화 시켰어요~! 
> 반영 커밋: [b423cc5](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/b423cc5db536bfc3de35ac7d61b6428956d86c94)

2023-04-05 02:35 UTC, devxsby commented on WeatherForecast/WeatherForecast/Domain/Usecases/CoreLocationManager.swift
> +        print("Location update failed with error: \(error.localizedDescription)")
네~!! 감사해요 😇
> 반영 커밋: [49e9006](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/49e9006c7a3dc48d91c49fc940733b422ddd328a)

2023-04-06 12:34 UTC, devxsby commented on WeatherForecast/WeatherForecast/Data/Network/Service/NetworkService.swift
> +}
넵!! 🙌🏻
콘이 말씀하신대로 기존의 코드를 리팩 했어요~!
![image](https://user-images.githubusercontent.com/80062632/230378338-9a854820-87ad-4fbf-9172-6b91bf68599c.png)
![image](https://user-images.githubusercontent.com/80062632/230378356-52cc160d-1b3e-41d7-9405-55ccb506e7d8.png)
데이터 레이어의 네트워킹 서비스에는 `performRequest` 메서드만 두고 원래 있던 fetchWeather, fetchForecast 메서드는 삭제하고 레포지토리에서 네트워크 객체를 갖고 URLRequest를 만들어 넘기고 응답으로 오는 Decodable을 Reponse로 변환했어요!
레포지토리에서는 completion으로 DTO를 전달하기만 하고 유즈케이스에서 `toDomain` 메서드와 함께 가공해서 Entity로 가공했어요.
좋은 의견 너무 감사해요 🐣

> 반영 커밋 : [22cfbd8](https://github.com/tasty-code/ios-weather-forecast/pull/9/commits/22cfbd8019d60b6074c82afed57c7e9b1bb0434b)

2023-04-09 13:49 UTC, devxsby commented on WeatherForecast/WeatherForecast/Presentation/MainScene/ViewModel/WeatherForecastViewModel.swift
> +    private let usecase: WeatherForecastUseCase
말씀하신 부분에 충분히 공감해요!
콘이 말씀하신대로 유즈케이스에서 하는 역할이 별로 없어서 없앨까 생각해보니 현재 위도, 경도를 받아오는 LocationManager의 역할을 유즈케이스에서 처리할 수 있겠다고 생각해서 유즈케이스를 없애지 않도록 리팩해봤어요.
이 부분 다시 확인해주시고 의견 부탁드려요 !! 🤔
현재 구조는 이렇게 구성되어있어요.
- 인프라스트럭처 레이어에 LocationManager를 두고, 유즈케이스에서만 위치 정보를 받아와요.
- 뷰컨, 뷰모델에서는 위치 정보에 대해 알 수 없고 유즈케이스에서 얻은 위도, 경도 정보를 레포지토리에 넘겨서 api를 호출해요.

2023-04-10 00:28 UTC, protocorn93 commented on WeatherForecast/WeatherForecast/Presentation/MainScene/ViewModel/WeatherForecastViewModel.swift
> +    private let usecase: WeatherForecastUseCase
네! 전 좋은 것 같아요! 👍

2023-04-10 00:39 UTC, merged